package com.algora.app.feature.interviewprep.quiz

import com.algora.app.core.data.model.Difficulty
import com.algora.app.core.data.model.Figure
import com.algora.app.core.data.model.FigureEdge
import com.algora.app.core.data.model.FigureGraphNode
import com.algora.app.core.data.model.FigureNode
import com.algora.app.core.data.model.FigureShape
import com.algora.app.core.data.model.FigureSpan

// Advanced interview sets: the rounds after the warm-ups. The last two sets are all scenarios — a
// product or constraint problem stated the way an interviewer would, with the solve in the
// explanation — because at this level the hard part is recognising the pattern, not recalling it.

internal val advancedGraphsSet = Quiz(
    id = "advanced_graphs_set",
    title = "Advanced Graphs Round",
    description = "Weighted paths, cycles, components and spanning trees — pick the algorithm the graph calls for.",
    questions = listOf(
        QuizQuestion(
            prompt = "Single-source shortest paths when every edge weight is non-negative:",
            options = listOf(
                "Dijkstra with a min-heap — O((V + E) log V)",
                "Plain BFS — O(V + E)",
                "DFS, keeping the smallest sum seen per node",
                "Bellman-Ford — the only correct choice once edges have weights",
            ),
            correctIndex = 0,
            patternTag = "Shortest Path",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Non-negative weights mean the closest unsettled node can never get closer later, so Dijkstra settles each node once. BFS is only right when all weights are equal; Bellman-Ford is correct but O(V·E).",
            linkedTopicId = "dijkstras_algorithm",
            linkedTopicLabel = "Dijkstra's Algorithm",
        ),
        QuizQuestion(
            prompt = "The graph has negative edge weights and you must report a negative cycle if one exists:",
            options = listOf(
                "Bellman-Ford — if a V-th round still relaxes an edge, a negative cycle exists",
                "Dijkstra — it re-visits nodes when a weight is negative",
                "Topological sort",
                "Prim's algorithm",
            ),
            correctIndex = 0,
            patternTag = "Shortest Path",
            difficulty = Difficulty.ADVANCED,
            explanation = "Any shortest path uses at most V − 1 edges, so V − 1 rounds of relaxing every edge settle all distances. If round V still improves something, a cycle keeps lowering the cost. Dijkstra can return wrong answers with negative edges.",
            linkedTopicId = "bellman_ford",
            linkedTopicLabel = "Bellman-Ford Algorithm",
        ),
        QuizQuestion(
            prompt = "Every edge weighs either 0 or 1. The fastest shortest-path approach:",
            options = listOf(
                "0-1 BFS with a deque — push 0-edges to the front, 1-edges to the back — O(V + E)",
                "Dijkstra is required — O(E log V)",
                "Plain BFS that ignores the weights",
                "Floyd-Warshall — O(V³)",
            ),
            correctIndex = 0,
            patternTag = "Shortest Path",
            difficulty = Difficulty.ADVANCED,
            explanation = "A 0-edge keeps the same distance, so it goes to the front; a 1-edge adds one, so it goes to the back. The deque stays sorted by distance without a heap. Dijkstra also works, but it is not required and is a log factor slower.",
            linkedTopicId = "shortest_path_pattern",
            linkedTopicLabel = "Weighted Shortest Path",
        ),
        QuizQuestion(
            prompt = "Scenario: n courses with prerequisite pairs (a needs b). Can a student finish them all?",
            options = listOf(
                "Kahn's topological sort — if fewer than n courses are dequeued, there is a cycle",
                "BFS from course 0 and check that every course is reached",
                "Union-find over the prerequisite pairs",
                "Sort courses by their number of prerequisites",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Topological Sort",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: build edges b → a and count in-degrees. Queue every course with in-degree 0; pop one, decrement its neighbours, and queue any that reach 0. If all n come out, an order exists. Union-find ignores direction, so it cannot tell a cycle from a diamond.",
            linkedTopicId = "topological_sort",
            linkedTopicLabel = "Topological Sort",
            figure = Figure(
                caption = "Prerequisites (b → a: take b before a)",
                shape = FigureShape.Graph(
                    nodes = listOf(
                        FigureGraphNode("Intro", 0.1f, 0.5f),
                        FigureGraphNode("DS", 0.4f, 0.18f),
                        FigureGraphNode("Math", 0.4f, 0.82f),
                        FigureGraphNode("Algo", 0.7f, 0.5f),
                        FigureGraphNode("ML", 0.92f, 0.18f),
                    ),
                    edges = listOf(
                        FigureEdge(0, 1, directed = true),
                        FigureEdge(0, 2, directed = true),
                        FigureEdge(1, 3, directed = true),
                        FigureEdge(2, 3, directed = true),
                        FigureEdge(3, 4, directed = true),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: friendships are added live, and users keep asking \"are A and B in the same friend group?\" Best structure:",
            options = listOf(
                "Union-find with path compression and union by rank — nearly O(1) per operation",
                "A fresh BFS from A for every question",
                "Floyd-Warshall, re-run after every new friendship",
                "Each friend list kept in a sorted array",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Union-Find",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: a new friendship calls union(a, b); a question checks find(a) == find(b). With both optimisations each call is O(α(n)) — effectively constant. BFS per question is O(V + E) every time.",
            linkedTopicId = "union_find_pattern",
            linkedTopicLabel = "Union-Find Pattern",
        ),
        QuizQuestion(
            prompt = "Scenario: lay fibre so every office is connected, using the least total cable. Possible links and their lengths are known:",
            options = listOf(
                "Kruskal: sort links by length, keep each one that does not close a cycle",
                "Dijkstra from headquarters",
                "Connect each office to its nearest neighbour only",
                "Topologically sort the offices",
            ),
            correctIndex = 0,
            patternTag = "Scenario · MST",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: this is a minimum spanning tree. Take links shortest first; union-find tells you whether the two offices are already connected, in which case you skip the link. Stop at V − 1 links. Dijkstra minimises each office's distance to HQ, not the total cable; nearest-neighbour can leave separate islands.",
            linkedTopicId = "kruskals_mst",
            linkedTopicLabel = "Kruskal's MST",
            figure = Figure(
                caption = "Possible links, km of cable",
                shape = FigureShape.Graph(
                    nodes = listOf(
                        FigureGraphNode("HQ", 0.1f, 0.5f),
                        FigureGraphNode("B", 0.4f, 0.16f),
                        FigureGraphNode("C", 0.4f, 0.84f),
                        FigureGraphNode("D", 0.72f, 0.16f),
                        FigureGraphNode("E", 0.9f, 0.7f),
                    ),
                    edges = listOf(
                        FigureEdge(0, 1, "4"),
                        FigureEdge(0, 2, "3"),
                        FigureEdge(1, 2, "2"),
                        FigureEdge(1, 3, "5"),
                        FigureEdge(2, 4, "6"),
                        FigureEdge(3, 4, "1"),
                        FigureEdge(2, 3, "7"),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Can a graph's nodes be split into two groups with every edge crossing between them (bipartite)?",
            options = listOf(
                "BFS/DFS two-colouring — fail if an edge joins two same-coloured nodes",
                "Yes whenever the number of nodes is even",
                "Yes whenever every node has even degree",
                "Only if the graph has no cycles at all",
            ),
            correctIndex = 0,
            patternTag = "Graph Colouring",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Colour a start node 0 and each neighbour the opposite colour. A conflict means an odd cycle, and a graph is bipartite exactly when it has none. Even cycles are fine — a square is bipartite.",
            linkedTopicId = "graph_coloring_pattern",
            linkedTopicLabel = "Two-Colouring & Cycle Detection",
        ),
        QuizQuestion(
            prompt = "Find the strongly connected components of a directed graph:",
            options = listOf(
                "Tarjan's or Kosaraju's algorithm — O(V + E)",
                "Union-find over the directed edges",
                "Dijkstra from every node",
                "A single BFS from any node",
            ),
            correctIndex = 0,
            patternTag = "Graphs",
            difficulty = Difficulty.ADVANCED,
            explanation = "A strongly connected component needs paths both ways. Kosaraju runs DFS twice (the second time on the reversed graph); Tarjan does it in one DFS with low-link values. Union-find treats edges as two-way, so it would merge nodes that only reach one direction.",
            linkedTopicId = "tarjans_algorithm",
            linkedTopicLabel = "Tarjan's Algorithm",
        ),
        QuizQuestion(
            prompt = "Scenario: a wildfire map grid; several cells are burning, and fire spreads to neighbours each minute. When is the last cell reached?",
            options = listOf(
                "Multi-source BFS — enqueue every fire at minute 0 and expand level by level",
                "A separate BFS from each fire, keeping the minimum per cell",
                "DFS from the first fire only",
                "Dijkstra with random edge weights",
            ),
            correctIndex = 0,
            patternTag = "Scenario · BFS",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: put all burning cells in the queue together, then run BFS; each level is one minute. The last level reached is the answer (or −1 if some cell is never reached). One BFS per fire gives the same answer at k times the cost.",
            linkedTopicId = "multi_source_bfs_pattern",
            linkedTopicLabel = "Multi-source BFS",
            figure = Figure(
                caption = "F = burning now, · = forest, # = rock",
                shape = FigureShape.Grid(
                    rows = listOf(
                        listOf("F", "·", "·", "#", "·"),
                        listOf("·", "#", "·", "·", "·"),
                        listOf("·", "·", "·", "#", "F"),
                        listOf("#", "·", "·", "·", "·"),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: cheapest flight from A to B with at most k stops:",
            options = listOf(
                "Bellman-Ford limited to k + 1 rounds, relaxing from the previous round's costs",
                "Plain Dijkstra on price, ignoring the stop count",
                "Greedy: always take the cheapest outgoing flight",
                "Topological sort of the airports",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Shortest Path",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: round r allows r flights. Each round copies the cost array and relaxes every flight using only last round's costs, so a path never gains two flights in one round. After k + 1 rounds read cost[B]. Plain Dijkstra may lock in a cheap route that has too many stops.",
            linkedTopicId = "bellman_ford",
            linkedTopicLabel = "Bellman-Ford Algorithm",
            figure = Figure(
                caption = "Flights and fares",
                shape = FigureShape.Graph(
                    nodes = listOf(
                        FigureGraphNode("A", 0.08f, 0.5f),
                        FigureGraphNode("X", 0.38f, 0.16f),
                        FigureGraphNode("Y", 0.38f, 0.84f),
                        FigureGraphNode("Z", 0.68f, 0.5f),
                        FigureGraphNode("B", 0.94f, 0.5f),
                    ),
                    edges = listOf(
                        FigureEdge(0, 1, "100", directed = true),
                        FigureEdge(0, 2, "50", directed = true),
                        FigureEdge(2, 3, "50", directed = true),
                        FigureEdge(3, 4, "50", directed = true),
                        FigureEdge(1, 4, "300", directed = true),
                        FigureEdge(2, 1, "20", directed = true),
                    ),
                ),
            ),
        ),
    ),
)

internal val advancedDpSet = Quiz(
    id = "advanced_dp_set",
    title = "Advanced DP Round",
    description = "State design, recurrences and the counterexamples that break greedy.",
    questions = listOf(
        QuizQuestion(
            prompt = "Scenario: rob houses along a street for the most money, but never two neighbouring houses. Recurrence:",
            options = listOf(
                "best[i] = max(best[i − 1], best[i − 2] + value[i])",
                "best[i] = best[i − 1] + value[i]",
                "Take every house at an even index",
                "Take the richest house, skip its neighbours, repeat",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Dynamic Programming",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: at house i you either skip it (best[i − 1]) or rob it on top of best[i − 2]. Two variables are enough — O(n) time, O(1) space. Greedy fails on [2, 3, 2]: it takes 3, but 2 + 2 = 4.",
            linkedTopicId = "fibonacci_dp",
            linkedTopicLabel = "Fibonacci (Dynamic Programming)",
        ),
        QuizQuestion(
            prompt = "Longest increasing subsequence in O(n log n):",
            options = listOf(
                "Keep a tails array and binary-search where each value belongs",
                "Sort the array and take the longest run",
                "Compare all pairs — the O(n²) DP is already O(n log n)",
                "Greedy: extend whenever the next value is larger",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.ADVANCED,
            explanation = "tails[k] holds the smallest possible ending of an increasing run of length k + 1. Each value replaces the first tail ≥ it, or extends the array. The array's length is the answer. Greedy fails on [3, 4, 1, 2, 5, 6].",
            linkedTopicId = "lis_patience_pattern",
            linkedTopicLabel = "Longest Increasing Subsequence",
        ),
        QuizQuestion(
            prompt = "Edit distance (insert / delete / replace) between strings a and b — the recurrence:",
            options = listOf(
                "dp[i][j] = dp[i−1][j−1] if the characters match, else 1 + min(insert, delete, replace)",
                "dp[i][j] = dp[i−1][j] + dp[i][j−1]",
                "Count the positions where the characters differ",
                "The difference between the two lengths",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "dp[i][j] is the cost to turn a's first i characters into b's first j. The three neighbours are delete (dp[i−1][j]), insert (dp[i][j−1]) and replace (dp[i−1][j−1]). Counting position-wise differences fails on \"abc\" → \"xabc\": every position differs, but one insert fixes it.",
            linkedTopicId = "edit_distance",
            linkedTopicLabel = "Edit Distance",
        ),
        QuizQuestion(
            prompt = "0/1 knapsack with a single 1-D array dp[capacity]. The inner loop over capacity must go:",
            options = listOf(
                "From high to low, so each item is counted at most once",
                "From low to high — that is what enforces the 0/1 rule",
                "In any order — the result is the same",
                "After sorting the items by value",
            ),
            correctIndex = 0,
            patternTag = "Knapsack DP",
            difficulty = Difficulty.ADVANCED,
            explanation = "dp[c] = max(dp[c], dp[c − w] + v) must read dp[c − w] from before this item. Going downward keeps it untouched. Going upward may read a value that already includes the item, which is the unbounded knapsack.",
            linkedTopicId = "knapsack_01",
            linkedTopicLabel = "0/1 Knapsack",
        ),
        QuizQuestion(
            prompt = "Scenario: a courier must visit 15 stops once each and return, with the shortest route. Exact approach:",
            options = listOf(
                "Bitmask DP over (visited set, current stop) — about 2ⁿ · n² ≈ 7 × 10⁶ steps",
                "Try every order — 15! ≈ 1.3 × 10¹²",
                "Greedy nearest-neighbour — it is exact",
                "Dijkstra from the depot",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Bitmask DP",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: dp[mask][v] = shortest path that visits exactly the stops in mask and ends at v. Extend with dp[mask | 1 << u][u] = min(…, dp[mask][v] + dist[v][u]). Answer = min over v of dp[all][v] + dist[v][depot]. The bitmask turns n! orders into 2ⁿ sets.",
            linkedTopicId = "bitmask_dp",
            linkedTopicLabel = "Bitmask DP",
        ),
        QuizQuestion(
            prompt = "Scenario: stock trading with unlimited trades, but after selling you must wait one day before buying. Best approach:",
            options = listOf(
                "State machine DP — track hold / just-sold / resting profit day by day",
                "Buy at the global minimum, sell at the global maximum",
                "Add up every positive day-to-day price increase",
                "Binary search for the best buy day",
            ),
            correctIndex = 0,
            patternTag = "Scenario · State Machine DP",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: hold = max(hold, rest − price); sold = hold + price; rest = max(rest, sold) — each using the previous day's values. Answer = max(sold, rest). Adding every rise is right without a cooldown, but here it can buy the day after a sale.",
            linkedTopicId = "state_machine_dp_pattern",
            linkedTopicLabel = "State Machine DP",
        ),
        QuizQuestion(
            prompt = "Burst balloons for coins, where each burst scores the product of its current neighbours. The key DP idea:",
            options = listOf(
                "Interval DP — pick which balloon in (i, j) bursts last",
                "Greedy — always burst the smallest balloon first",
                "Sort the balloons and pair up neighbours",
                "Try every order with backtracking and no memo",
            ),
            correctIndex = 0,
            patternTag = "Interval DP",
            difficulty = Difficulty.ADVANCED,
            explanation = "If k is the last to burst inside (i, j), its neighbours at that moment are exactly i and j, so dp[i][j] = max over k of dp[i][k] + dp[k][j] + v[i]·v[k]·v[j]. Thinking \"first\" instead of \"last\" leaves the two sides dependent on each other. O(n³).",
            linkedTopicId = "interval_dp_pattern",
            linkedTopicLabel = "Interval DP",
        ),
        QuizQuestion(
            prompt = "Scenario: invite employees to a party for the most total fun, but never an employee together with their direct manager. The org chart is a tree:",
            options = listOf(
                "Tree DP — each person returns (best if invited, best if not)",
                "Invite every other level of the org chart",
                "Invite the most fun person, remove their neighbours, repeat",
                "BFS and invite only the leaves",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Tree DP",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: post-order. in(v) = fun(v) + Σ out(child); out(v) = Σ max(in(child), out(child)). Answer = max(in(root), out(root)). O(n). Alternating levels fails when two consecutive levels are both worth skipping.",
            linkedTopicId = "tree_dp",
            linkedTopicLabel = "Tree DP",
            figure = Figure(
                caption = "Org chart with fun scores (parent = manager)",
                shape = FigureShape.Tree(
                    nodes = listOf(
                        FigureNode("CEO 3", null),
                        FigureNode("VP 7", 0),
                        FigureNode("Dev 4", 1),
                        FigureNode("QA 5", 1),
                        FigureNode("VP 2", 0),
                        FigureNode("Ops 6", 4),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Can \"cars\" be split into words from the dictionary {\"car\", \"ca\", \"rs\"}?",
            options = listOf(
                "Yes — dp[i] is true if some word ends at i and dp[start of that word] is true",
                "No — greedily taking the longest word \"car\" leaves an unmatched \"s\"",
                "Yes — every dictionary word appears somewhere in the string",
                "No — the dictionary has no word starting with 's'",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: dp[0] = true; dp[2] (\"ca\") = true; dp[3] (\"car\") = true; dp[4] = dp[2] && \"rs\" is a word = true. Split: \"ca\" + \"rs\". Greedy commits to \"car\" and fails. O(n²) substring checks with a hash set of words.",
            linkedTopicId = "memo_recursion_pattern",
            linkedTopicLabel = "Top-down Memoization",
        ),
        QuizQuestion(
            prompt = "Letters map to numbers (A = 1 … Z = 26). How many ways can \"226\" be decoded?",
            options = listOf(
                "3 — dp[i] = dp[i − 1] if the last digit is 1–9, plus dp[i − 2] if the last two form 10–26",
                "2 — one per split point",
                "1 — digits decode one at a time",
                "4 — 2²",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: \"2 2 6\" (BBF), \"22 6\" (VF), \"2 26\" (BZ) = 3. A '0' can only be used as part of 10 or 20, which is what the digit checks handle — \"06\" is not a valid code. O(n) time with two variables.",
            linkedTopicId = "fibonacci_dp",
            linkedTopicLabel = "Fibonacci (Dynamic Programming)",
        ),
    ),
)

internal val advancedDataStructuresSet = Quiz(
    id = "advanced_data_structures_set",
    title = "Advanced Data Structures Round",
    description = "Range queries, time-indexed stores, schedulers and O(1) designs — the structures behind the fast answer.",
    questions = listOf(
        QuizQuestion(
            prompt = "Design a time-based key-value store: set(key, value, t) with increasing t, and get(key, t) returning the value set at the latest time ≤ t.",
            options = listOf(
                "Per key, append (t, value) to a list and binary search it by t — O(log n) get",
                "A hash map holding only the latest value per key",
                "Scan every stored entry on each get",
                "Sort the whole store on every get",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Design",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: map key → list of (t, value). Timestamps only increase, so each list is already sorted and set is an O(1) append. get binary-searches for the last t' ≤ t and returns \"\" if there is none. Keeping only the latest value cannot answer a question about the past.",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
        ),
        QuizQuestion(
            prompt = "Many interleaved \"add x to index i\" updates and \"sum of range [l, r]\" queries:",
            options = listOf(
                "A Fenwick tree or segment tree — O(log n) for both",
                "Prefix sums — O(1) queries and O(1) updates",
                "A running total — O(1) for both",
                "A sorted array with binary search",
            ),
            correctIndex = 0,
            patternTag = "Range Query",
            difficulty = Difficulty.ADVANCED,
            explanation = "Prefix sums give O(1) queries, but one update shifts every later prefix — O(n). A Fenwick tree stores partial sums over power-of-two blocks, so both operations touch O(log n) cells.",
            linkedTopicId = "fenwick_tree",
            linkedTopicLabel = "Fenwick Tree (BIT)",
        ),
        QuizQuestion(
            prompt = "Tasks [A, A, A, B, B, B] must run with at least n = 2 idle slots between identical tasks. What is the fewest time slots needed?",
            options = listOf(
                "8 — (maxCount − 1) × (n + 1) + number of tasks with maxCount = 2 × 3 + 2",
                "6 — one slot per task",
                "7 — tasks plus one idle",
                "9 — every slot after a task sits idle",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Scheduling",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: the most frequent task makes the frame: A _ _ A _ _ A. B fills a gap in each frame and ties at the end: A B _ A B _ A B = 8. The answer is the larger of that formula and the task count, since with enough variety there are no idles at all.",
            linkedTopicId = "heap_scheduling_pattern",
            linkedTopicLabel = "Heap Scheduling",
        ),
        QuizQuestion(
            prompt = "Design a set with insert, remove and getRandom, all in O(1) on average.",
            options = listOf(
                "An array of values plus a map of value → index; remove swaps the value with the last one, then pops",
                "A hash set only — picking a random element is O(1)",
                "A linked list, walking to a random index",
                "A sorted array",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Design",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: insert appends and records the index. remove(x) moves the last element into x's slot, updates its index, and pops the end. getRandom picks arr[random(size)]. Hash sets have no index access, so a uniform random pick means iterating.",
            linkedTopicId = "composite_design_pattern",
            linkedTopicLabel = "Design with Paired Structures",
        ),
        QuizQuestion(
            prompt = "Return the k-th smallest value in a BST.",
            options = listOf(
                "In-order traversal, stopping at the k-th node visited — O(h + k)",
                "Level-order traversal, taking the k-th node",
                "Walk left k times from the root",
                "Collect all the values, then sort them",
            ),
            correctIndex = 0,
            patternTag = "BST",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: an iterative in-order with a stack: push left children, pop, count, and stop when the count reaches k. The BST already gives sorted order, so sorting is wasted work. Level order is not sorted.",
            linkedTopicId = "bst_inorder_pattern",
            linkedTopicLabel = "BST In-order Traversal",
        ),
        QuizQuestion(
            prompt = "For every element, find the next element to its right that is larger:",
            options = listOf(
                "A monotonic stack — each index is pushed and popped once, O(n)",
                "Nested loops with an early break — O(n) overall",
                "Sort the array, then look each value up in a hash map",
                "Binary search on the right-hand side",
            ),
            correctIndex = 0,
            patternTag = "Monotonic Stack",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Keep indices whose answer is still unknown on a stack of decreasing values. A new value pops every smaller one — it is their answer — and then pushes itself. An early break still costs O(n²) on a decreasing array.",
            linkedTopicId = "monotonic_stack_pattern",
            linkedTopicLabel = "Monotonic Stack",
        ),
        QuizQuestion(
            prompt = "Scenario: block a billion known malicious URLs using little memory. An occasional false alarm is fine; missing a bad URL is not:",
            options = listOf(
                "A Bloom filter — no false negatives, tunable false-positive rate",
                "A hash set of every URL",
                "A sorted list on disk with binary search",
                "A count-min sketch for exact membership",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Probabilistic",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: set k bit positions per URL. A lookup with any bit clear is definitely safe; all bits set means \"probably bad\", so confirm against the slow exact store. About 10 bits per URL gives roughly 1% false positives — around 1.2 GB instead of tens of GB.",
            linkedTopicId = "bloom_filter",
            linkedTopicLabel = "Bloom Filter",
        ),
        QuizQuestion(
            prompt = "A static array with a million range-minimum queries. Fastest per query:",
            options = listOf(
                "A sparse table — O(n log n) to build, O(1) per query",
                "A Fenwick tree — O(1) per query",
                "Prefix minimums — any range in O(1)",
                "Rescan each range — O(1) amortised",
            ),
            correctIndex = 0,
            patternTag = "Range Query",
            difficulty = Difficulty.ADVANCED,
            explanation = "The minimum is fine with overlap, so any range is covered by two power-of-two blocks: min(st[k][l], st[k][r − 2ᵏ + 1]). Prefix minimums only answer ranges that start at index 0.",
            linkedTopicId = "sparse_table",
            linkedTopicLabel = "Sparse Table",
        ),
        QuizQuestion(
            prompt = "When is a balanced BST (TreeMap) the better choice over a hash map?",
            options = listOf(
                "When you need ordered queries — floor, ceiling, range scans — in O(log n)",
                "When you need the fastest average exact-key lookup",
                "When the keys cannot be compared",
                "When the structure must use O(1) memory",
            ),
            correctIndex = 0,
            patternTag = "Data Structures",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Hash maps win exact lookups at O(1) average but know nothing about order. A balanced BST answers \"the largest key ≤ x\" or \"every key between a and b\" directly — which is what schedules, price books and time series need.",
            linkedTopicId = "avl_red_black_tree",
            linkedTopicLabel = "AVL / Red-Black Tree",
        ),
        QuizQuestion(
            prompt = "Scenario: a game leaderboard with frequent score updates and \"what is my rank?\" queries. Scores are integers from 0 to 1,000,000:",
            options = listOf(
                "A Fenwick tree over score counts — rank = number of higher scores + 1, O(log S)",
                "Re-sort the whole board on every update",
                "A hash map of player → score, scanning it for each rank",
                "A queue of players in join order",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Range Query",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: count[s] = players with score s, stored in a Fenwick tree. An update is add(old, −1) then add(new, +1); rank = (total − prefix(score)) + 1. Keep player → score in a map for the old value. Both operations are O(log 10⁶) ≈ 20 steps.",
            linkedTopicId = "fenwick_tree",
            linkedTopicLabel = "Fenwick Tree (BIT)",
        ),
    ),
)

internal val advancedSystemsScenariosSet = Quiz(
    id = "advanced_systems_scenarios_set",
    title = "Scenario Round: Real Systems",
    description = "Product problems — rate limits, logs, trends, calendars — solved with the right algorithm.",
    questions = listOf(
        QuizQuestion(
            prompt = "Scenario: allow each user at most 100 API requests in any rolling 60-second window:",
            options = listOf(
                "Per user, a queue of timestamps — drop those older than 60 s, reject if 100 remain",
                "One global counter reset once a day",
                "Sort every request by user once a minute",
                "A stack of timestamps per user, popped from the top",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Sliding Window",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: on each request, pop from the front while front ≤ now − 60 s. If size < 100, push now and allow; otherwise reject. Each timestamp is pushed and popped once. The oldest entries leave first, so it is a queue, not a stack. A token bucket gives a similar limit in O(1) memory.",
            linkedTopicId = "sliding_window_pattern",
            linkedTopicLabel = "Sliding Window Pattern",
        ),
        QuizQuestion(
            prompt = "Scenario: merge k log files, each already sorted by timestamp, N lines in total:",
            options = listOf(
                "A k-way merge with a min-heap of each file's next line — O(N log k)",
                "Concatenate everything and sort — O(N log N)",
                "Merge file 1 with 2, then the result with 3, and so on — O(N·k)",
                "Take one line from each file in turn",
            ),
            correctIndex = 0,
            patternTag = "Scenario · K-way Merge",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: push the first line of every file onto a heap keyed by timestamp. Pop the smallest, write it, and push the next line from the same file. The heap never holds more than k lines, so it streams files too big for memory.",
            linkedTopicId = "k_way_merge_pattern",
            linkedTopicLabel = "K-way Merge",
        ),
        QuizQuestion(
            prompt = "Scenario: show the top 10 trending hashtags from millions of posts:",
            options = listOf(
                "Count in a hash map, then keep a size-10 min-heap — O(n log 10)",
                "Re-sort every hashtag by count after each post",
                "Push every tag onto a max-heap and pop 10",
                "Show the 10 most recent hashtags",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Top-K",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: count[tag]++ per post. Then for each (tag, count): push onto a min-heap and pop whenever its size passes 10. The heap's root is the weakest of the current top 10, so anything smaller is dropped at once. A max-heap of every tag works but costs O(n log n).",
            linkedTopicId = "top_k_pattern",
            linkedTopicLabel = "Top-K Pattern",
        ),
        QuizQuestion(
            prompt = "Scenario: given today's meetings as (start, end), how many rooms does the office need?",
            options = listOf(
                "Sort by start; a min-heap of end times — its peak size is the answer",
                "Divide the number of meetings by 8 working hours",
                "Sort by duration and pack meetings greedily",
                "Count the meetings that overlap the first one",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Heap Scheduling",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: for each meeting in start order, pop the heap's top if that meeting has ended (end ≤ start) — its room is free — then push this meeting's end. The largest heap size is the room count. A line sweep over +1/−1 events gives the same answer.",
            linkedTopicId = "heap_scheduling_pattern",
            linkedTopicLabel = "Heap Scheduling",
            figure = Figure(
                caption = "Meetings, hours after 9:00",
                shape = FigureShape.Timeline(
                    spans = listOf(
                        FigureSpan(0, 1, "Standup"),
                        FigureSpan(0, 3, "Design"),
                        FigureSpan(2, 4, "Review"),
                        FigureSpan(3, 5, "Lunch talk"),
                        FigureSpan(4, 6, "1:1"),
                    ),
                    axisMax = 7,
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: pick 1,000 records uniformly at random from a stream of unknown length, in one pass and O(1,000) memory:",
            options = listOf(
                "Reservoir sampling — keep record i with probability 1,000 / i",
                "Keep the first 1,000 records",
                "Keep every 1,000th record",
                "Store the whole stream, then shuffle it",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Randomised",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: fill the reservoir with the first 1,000. For record i > 1,000, pick j in [1, i]; if j ≤ 1,000, replace slot j. Every record ends up with an equal 1,000 / n chance. Storing everything breaks the memory limit; the other two are biased.",
            linkedTopicId = "reservoir_sampling",
            linkedTopicLabel = "Reservoir Sampling",
        ),
        QuizQuestion(
            prompt = "Scenario: find every 10-letter DNA sequence that occurs more than once in a genome of n letters:",
            options = listOf(
                "A rolling hash over each 10-letter window, with a set of seen hashes — O(n)",
                "Compare every pair of windows — O(n²)",
                "Sort the genome's letters",
                "Run KMP with an empty pattern",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Rolling Hash",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: with 4 letters, each window packs into 20 bits: h = ((h << 2) | code(c)) & 0xFFFFF. Add h to seen; if already present, add it to repeated. Each slide is O(1), and this packing is collision-free, so no string comparison is needed.",
            linkedTopicId = "rolling_hash_pattern",
            linkedTopicLabel = "Rolling Hash",
        ),
        QuizQuestion(
            prompt = "Scenario: ship packages in their given order within D days. What is the smallest daily truck capacity that works?",
            options = listOf(
                "Binary search on the capacity, greedily checking whether D days suffice",
                "Try every capacity from 1 upward",
                "Total weight ÷ D, rounded up",
                "Sort the packages and ship the heaviest first",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Binary Search on Answer",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: lo = heaviest package, hi = total weight. For mid, fill each day until the next package would overflow, then start a new day. If that takes ≤ D days, try smaller (hi = mid); otherwise lo = mid + 1. Feasibility only flips once, which is what makes binary search valid. Total ÷ D ignores that packages cannot be split.",
            linkedTopicId = "binary_search_answer",
            linkedTopicLabel = "Binary Search on Answer",
        ),
        QuizQuestion(
            prompt = "Scenario: a calendar app must reject a new event that overlaps an existing one, with thousands of events:",
            options = listOf(
                "A balanced BST keyed by start — check only the floor and ceiling neighbours, O(log n)",
                "Scan every event on each insert",
                "A hash map keyed by start time",
                "A stack of events in creation order",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Ordered Map",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: prev = floorEntry(start), next = ceilingEntry(start). The event fits if prev.end ≤ start and end ≤ next.start. Existing events never overlap each other, so only those two neighbours can clash. A hash map cannot find neighbouring times.",
            linkedTopicId = "avl_red_black_tree",
            linkedTopicLabel = "AVL / Red-Black Tree",
        ),
        QuizQuestion(
            prompt = "Scenario: from a pile of airline tickets (from, to), rebuild the one itinerary that uses every ticket exactly once:",
            options = listOf(
                "Hierholzer's algorithm — DFS that uses up edges and adds airports on the way back",
                "Sort tickets by departure airport and chain them greedily",
                "BFS from the starting airport",
                "Topologically sort the airports",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Eulerian Path",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: every ticket is an edge, used once — an Eulerian path. Walk DFS, removing each ticket as you use it; when an airport has none left, prepend it to the answer. Greedy chaining can walk into a dead end early; topological sort fails because routes revisit airports.",
            linkedTopicId = "eulerian_path",
            linkedTopicLabel = "Eulerian Path & Circuit",
        ),
        QuizQuestion(
            prompt = "Scenario: a warehouse robot needs the shortest path across a grid with shelves, and should explore as few cells as possible:",
            options = listOf(
                "A* with Manhattan distance as the heuristic",
                "DFS until it happens to reach the goal",
                "Dijkstra with a negative heuristic added",
                "Greedy best-first search — it is always optimal",
            ),
            correctIndex = 0,
            patternTag = "Scenario · A* Search",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: expand by f = g (steps so far) + h (Manhattan distance to the goal). With 4-way moves, Manhattan never overestimates, so A* stays optimal while skipping cells that head away from the goal. Greedy best-first uses h alone and can return a longer path.",
            linkedTopicId = "a_star_search",
            linkedTopicLabel = "A* Search",
            figure = Figure(
                caption = "S = robot, E = goal, # = shelf",
                shape = FigureShape.Grid(
                    rows = listOf(
                        listOf("S", "·", "·", "#", "·", "·"),
                        listOf("·", "#", "·", "#", "·", "·"),
                        listOf("·", "#", "·", "·", "·", "#"),
                        listOf("·", "·", "·", "#", "·", "E"),
                    ),
                ),
            ),
        ),
    ),
)

internal val advancedConstraintsScenariosSet = Quiz(
    id = "advanced_constraints_scenarios_set",
    title = "Scenario Round: Constraints & Trade-offs",
    description = "Read the limits first — n, memory, accuracy — and let them pick the algorithm.",
    questions = listOf(
        QuizQuestion(
            prompt = "The problem says n ≤ 20 and asks for the best subset of items. What do the limits allow?",
            options = listOf(
                "Enumerating every subset — 2²⁰ ≈ 10⁶ with a bitmask is fine",
                "Only an O(n log n) solution will pass",
                "Only O(n) will pass",
                "Backtracking over 20 items is always too slow",
            ),
            correctIndex = 0,
            patternTag = "Constraints",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A tiny n is a hint: the intended solution is exponential. Loop mask from 0 to 2ⁿ − 1; bit i set means item i is taken. At about 20 · 10⁶ operations it runs well under a second.",
            linkedTopicId = "subsets_bitmask",
            linkedTopicLabel = "Subsets using Bitmask",
        ),
        QuizQuestion(
            prompt = "Subset sum with n = 40 items whose values reach 10⁹:",
            options = listOf(
                "Meet in the middle — enumerate both halves (2 × 2²⁰), sort one, binary-search it",
                "Enumerate all 2⁴⁰ ≈ 10¹² subsets",
                "Greedy: take the largest items first",
                "DP over every possible sum up to 4 × 10¹⁰",
            ),
            correctIndex = 0,
            patternTag = "Meet in the Middle",
            difficulty = Difficulty.ADVANCED,
            explanation = "Split into two halves of 20 and list each half's subset sums — about 10⁶ each. Sort one list; for each sum s in the other, binary-search for target − s. Huge values rule out sum-indexed DP, and 2⁴⁰ is too slow.",
            linkedTopicId = "meet_in_middle_pattern",
            linkedTopicLabel = "Meet in the Middle",
        ),
        QuizQuestion(
            prompt = "n = 10⁵ and the problem involves pairs of elements. What complexity do you aim for?",
            options = listOf(
                "O(n log n) or better — O(n²) is 10¹⁰ operations",
                "O(n²) is fine for 10⁵",
                "O(n³) with pruning",
                "O(2ⁿ) with memoisation",
            ),
            correctIndex = 0,
            patternTag = "Constraints",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Rough limits for about a second: n ≤ 20 → exponential, ≤ 500 → n³, ≤ 5,000 → n², ≤ 10⁶ → n log n. At 10⁵, all-pairs is out, so reach for sorting, hashing, two pointers or a heap.",
            linkedTopicId = "complexity_class_comparison",
            linkedTopicLabel = "Complexity Class Comparison",
        ),
        QuizQuestion(
            prompt = "Scenario: 10⁵ hotel bookings each add +1 guest to every day in [l, r], across 10⁵ days. You need the final count per day:",
            options = listOf(
                "A difference array: +1 at l, −1 at r + 1, then one prefix-sum pass — O(n + q)",
                "Loop over each booking's days and add — O(n·q) is fine",
                "A segment tree is required",
                "Sort the bookings by length",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Difference Array",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: diff[l] += 1 and diff[r + 1] −= 1 per booking, then count[d] = count[d − 1] + diff[d]. 2 × 10⁵ operations instead of up to 10¹⁰. A lazy segment tree also works, but it is only needed when queries arrive between updates.",
            linkedTopicId = "difference_array",
            linkedTopicLabel = "Difference Array",
            figure = Figure(
                caption = "A few bookings (day ranges)",
                shape = FigureShape.Timeline(
                    spans = listOf(
                        FigureSpan(1, 4, "Kim 1–4"),
                        FigureSpan(2, 6, "Lee 2–6"),
                        FigureSpan(5, 8, "Ng 5–8"),
                        FigureSpan(3, 9, "Oz 3–9"),
                    ),
                    axisMax = 10,
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: count the subarrays that sum to exactly k, where values can be negative:",
            options = listOf(
                "Prefix sums with a hash map of prefix counts — O(n)",
                "A sliding window that shrinks whenever the sum exceeds k",
                "Sort the array, then use two pointers",
                "Binary search over the prefix sums",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Prefix Sum",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: seen = {0: 1}. For each running sum s, add seen[s − k] to the answer, then seen[s]++. A sliding window needs sums that only grow as it widens; negatives break that. Sorting destroys contiguity.",
            linkedTopicId = "prefix_sum",
            linkedTopicLabel = "Prefix Sum",
        ),
        QuizQuestion(
            prompt = "Scenario: sort a 1 GB file of integers on a machine with 100 MB of RAM:",
            options = listOf(
                "External merge sort — sort 100 MB chunks to disk, then k-way merge them",
                "Load the whole file and quicksort it",
                "Counting sort over the full 32-bit range in memory",
                "Bubble sort directly on disk",
            ),
            correctIndex = 0,
            patternTag = "Scenario · External Sort",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: read about 10 chunks that fit in RAM, sort each and write it out. Then merge all 10 with a min-heap, reading and writing buffered blocks — the disk is read sequentially twice. A 32-bit count array needs 16 GB.",
            linkedTopicId = "merge_sort",
            linkedTopicLabel = "Merge Sort",
        ),
        QuizQuestion(
            prompt = "Scenario: a map has 10⁵ points. Find the two closest ones.",
            options = listOf(
                "Divide and conquer by x, then check a narrow strip around the split — O(n log n)",
                "Compare every pair — about 5 × 10⁹ comparisons",
                "Sort by x and compare neighbours only",
                "Take the two points closest to the origin",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Divide & Conquer",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: split by median x, recurse on both halves to get δ, then check only points within δ of the split line, sorted by y — each needs at most about 7 comparisons. Neighbours in x order can be far apart in y, so comparing only neighbours misses pairs.",
            linkedTopicId = "closest_pair_of_points",
            linkedTopicLabel = "Closest Pair of Points",
        ),
        QuizQuestion(
            prompt = "Scenario: count the distinct users across billions of events. ±2% is acceptable, and memory must stay in kilobytes:",
            options = listOf(
                "A HyperLogLog-style cardinality sketch",
                "An exact hash set of every user id",
                "Sort every event by user id",
                "A Bloom filter, which counts distinct items exactly",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Probabilistic",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: hash each id and track, per bucket, the longest run of leading zeros seen; rare long runs mean many distinct values. About 1.5 KB gives roughly 2% error at any scale. An exact set of a billion ids needs gigabytes. A Bloom filter answers membership, not counts.",
        ),
        QuizQuestion(
            prompt = "Scenario: your recursive DFS crashes with a stack overflow on a path-shaped graph of 10⁶ nodes. The fix:",
            options = listOf(
                "Rewrite it as an iterative DFS with an explicit stack",
                "Add memoisation — that removes the depth",
                "Rely on tail-call optimisation, which every language performs",
                "Sort the nodes before the DFS",
            ),
            correctIndex = 0,
            patternTag = "Scenario · DFS",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: push the start node onto a heap-allocated stack; loop pop → visit → push unvisited neighbours. The depth now lives in heap memory, not the call stack of about 1 MB. Memoisation cuts repeated work, not depth, and the JVM does not eliminate tail calls.",
            linkedTopicId = "dfs",
            linkedTopicLabel = "Depth-First Search (DFS)",
        ),
        QuizQuestion(
            prompt = "Scenario: your O(n²) brute force works and the interviewer asks, \"Can you do better?\" The strongest next move:",
            options = listOf(
                "Name what the inner loop recomputes, then precompute it — a hash map, prefix sums or sorted order",
                "Offer to rewrite it in a faster language",
                "Add early returns inside the inner loop",
                "Split the work across several threads",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Interview Technique",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: say it out loud — \"for each i, the inner loop searches for x\". Then ask which structure answers that search in O(1) or O(log n): a set for existence, a map for counts or indices, prefix sums for ranges, sorting for order. Languages, threads and early exits only change constants.",
            linkedTopicId = "hash_counting_pattern",
            linkedTopicLabel = "Hashing & Counting",
        ),
    ),
)
