package com.algora.app.feature.interviewprep.quiz

import com.algora.app.core.data.model.Difficulty
import com.algora.app.core.data.model.Figure
import com.algora.app.core.data.model.FigureShape

// Beginner interview sets: the first screen a new learner can pass. Each set mixes concept checks
// with "Scenario:" questions — a small product problem to solve — and the explanation walks through
// the solve, so a wrong answer still teaches the approach rather than just naming it.

internal val beginnerArraysStringsSet = Quiz(
    id = "beginner_arrays_strings_set",
    title = "Arrays & Strings Warm-up",
    description = "Indexing, two pointers, windows and counting — the first questions most screens open with.",
    questions = listOf(
        QuizQuestion(
            prompt = "Reading arr[i] from an array of n elements costs:",
            options = listOf(
                "O(1) — the address is computed straight from the index",
                "O(i) — it walks from the start to position i",
                "O(log n) — it binary-searches for the index",
                "O(n) — the array is copied before reading",
            ),
            correctIndex = 0,
            patternTag = "Arrays",
            difficulty = Difficulty.BEGINNER,
            explanation = "Array elements sit side by side in memory, so element i lives at base + i × size. One multiplication and one read — no walking.",
            linkedTopicId = "array",
            linkedTopicLabel = "Array",
        ),
        QuizQuestion(
            prompt = "Rotate nums right by k steps, in place with O(1) extra space. [1, 2, 3, 4, 5], k = 2 → [4, 5, 1, 2, 3].",
            options = listOf(
                "Reverse the whole array, then reverse the first k and the last n − k (after k %= n)",
                "Move the last element to the front, k times",
                "Copy into a new array at index (i + k) % n",
                "Sort the array, then shift it",
            ),
            correctIndex = 0,
            patternTag = "Arrays",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: reverse all → [5, 4, 3, 2, 1]; reverse the first 2 → [4, 5, 3, 2, 1]; reverse the rest → [4, 5, 1, 2, 3]. O(n), O(1). Moving one element k times is O(n·k); the copy is right but uses O(n) space.",
            linkedTopicId = "array",
            linkedTopicLabel = "Array",
        ),
        QuizQuestion(
            prompt = "Given a sorted array, remove the duplicates in place and return how many unique values remain.",
            options = listOf(
                "A slow write pointer copies nums[i] only when it differs from the last value written",
                "Insert every value into a hash set and return its size",
                "Delete each duplicate by shifting the rest of the array left",
                "Binary search for each value's last copy",
            ),
            correctIndex = 0,
            patternTag = "Two Pointer",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: w = 1; for i in 1 until n: if nums[i] != nums[w − 1], nums[w++] = nums[i]. Return w. Sorted input puts duplicates next to each other, so one comparison is enough. The hash set gives the count but leaves the array unchanged; shifting is O(n²).",
            linkedTopicId = "two_pointer",
            linkedTopicLabel = "Two Pointer Technique",
        ),
        QuizQuestion(
            prompt = "Is \"A man, a plan, a canal: Panama\" a palindrome if you ignore case and punctuation? Best check:",
            options = listOf(
                "Two pointers that skip non-letters and compare lowercase characters",
                "Reverse the whole string, punctuation included, and compare",
                "Count every letter and check all counts are even",
                "Remove the vowels, then compare with the reverse",
            ),
            correctIndex = 0,
            patternTag = "Two Pointer",
            difficulty = Difficulty.BEGINNER,
            explanation = "Move left and right inward, skipping anything that is not a letter or digit, and compare lowercased characters. Reversing with punctuation fails on the comma placement; letter counts only tell you whether some rearrangement could be a palindrome.",
            linkedTopicId = "two_pointer",
            linkedTopicLabel = "Two Pointer Technique",
        ),
        QuizQuestion(
            prompt = "Scenario: a fitness app stores a week of daily step counts. The user taps \"best day\". How do you find it?",
            options = listOf(
                "One pass keeping the largest value seen so far — O(n)",
                "Sort the week, then take the last element — O(n log n)",
                "Compare every day against every other day — O(n²)",
                "Binary search for the maximum — O(log n)",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Arrays",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: best = steps[0]; for each day, if steps[d] > best, best = steps[d]. One pass, O(1) memory. Sorting works but does more work than needed and loses which day it was; binary search needs sorted data, which step counts are not.",
            linkedTopicId = "linear_search",
            linkedTopicLabel = "Linear Search",
            figure = Figure(
                caption = "Steps per day",
                shape = FigureShape.Strip(
                    cells = listOf("6.2k", "8.1k", "4.5k", "9.8k", "7.3k", "5.0k", "8.7k"),
                    aux = listOf("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"),
                    auxLabel = "day",
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: a scores list uses 0 for \"absent\". Move every 0 to the end while keeping the other scores in their original order, in place:",
            options = listOf(
                "A write pointer copies each non-zero forward, then fills the tail with zeros",
                "Sort the array in descending order",
                "Remove each zero and append it, shifting the array every time",
                "Swap each zero with the current last element",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Two Pointer",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: w = 0; for each value v, if v ≠ 0 then a[w++] = v. Afterwards set a[w..n−1] = 0. O(n), O(1) space, order kept. Sorting reorders the scores; remove-and-append is O(n²); swapping with the last element scrambles the order.",
            linkedTopicId = "two_pointer_pattern",
            linkedTopicLabel = "Two Pointer Pattern",
            figure = Figure(
                caption = "Scores, 0 = absent",
                shape = FigureShape.Strip(
                    cells = listOf("7", "0", "5", "0", "0", "9", "3"),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: a sales dashboard is asked \"total sales from day l to day r\" thousands of times. Best approach:",
            options = listOf(
                "Precompute prefix sums once; each query is prefix[r + 1] − prefix[l]",
                "Loop from l to r and add, for every query",
                "Sort the sales, then add the middle section",
                "Precompute and store every possible (l, r) range sum",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Prefix Sum",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: prefix[0] = 0 and prefix[i + 1] = prefix[i] + sales[i]. Any range is then two lookups and a subtraction — O(n) setup, O(1) per query. Looping is O(n) per query; storing every range costs O(n²) memory; sorting destroys the day order.",
            linkedTopicId = "prefix_sum",
            linkedTopicLabel = "Prefix Sum",
        ),
        QuizQuestion(
            prompt = "Are \"listen\" and \"silent\" anagrams? The cleanest O(n) check:",
            options = listOf(
                "Count the letters of both words and compare the counts",
                "Check that the first and last letters match",
                "Compare the lengths only",
                "Check that each word is a palindrome",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.BEGINNER,
            explanation = "Anagrams use exactly the same letters the same number of times. A 26-slot count array (or a map) does it in one pass per word. Sorting both words and comparing also works, at O(n log n). Equal lengths is necessary but nowhere near sufficient.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Scenario: find the highest total over any k consecutive days of revenue. Best approach:",
            options = listOf(
                "Slide a size-k window: add the entering day, subtract the leaving one — O(n)",
                "Re-add all k days at every starting position — O(n·k)",
                "Sort the days and add the k largest",
                "Find the single best day and add its neighbours",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Sliding Window",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: sum the first k days, then for each next day do sum += a[i] − a[i − k] and track the best. Every step is O(1). Sorting picks the k best days even when they are not consecutive, which answers a different question.",
            linkedTopicId = "sliding_window",
            linkedTopicLabel = "Sliding Window",
        ),
        QuizQuestion(
            prompt = "Return the first character that appears exactly once in a string:",
            options = listOf(
                "Two passes: count every character, then return the first with count 1 — O(n)",
                "Sort the string and return the first character with no equal neighbour",
                "Return the first character that differs from the one after it",
                "Binary search the character positions",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Pass one fills a count map; pass two walks the original string in order and stops at the first count of 1. Sorting finds a unique character, but not the first one — it throws the original order away.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
    ),
)

internal val beginnerHashingSet = Quiz(
    id = "beginner_hashing_set",
    title = "Hash Maps & Sets Warm-up",
    description = "Lookups, counting and membership — the tool that turns most O(n²) answers into O(n).",
    questions = listOf(
        QuizQuestion(
            prompt = "Average cost of looking up a key in a hash map:",
            options = listOf(
                "O(1) on average — the key hashes straight to its bucket",
                "O(log n) — keys are kept in sorted order",
                "O(n) — every stored key is compared in turn",
                "O(n log n) — the table is sorted on each lookup",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.BEGINNER,
            explanation = "The hash function turns the key into a bucket index, so a lookup checks one bucket. Collisions can make one bucket long, which is why the worst case is O(n) — but a good hash and resizing keep the average at O(1).",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Two Sum on an unsorted array: find two indices whose values add up to a target, in O(n):",
            options = listOf(
                "One pass: for each number, check whether target − number is already in a map",
                "Sort the array, then binary search for every pair",
                "Two nested loops over all pairs",
                "Two pointers from both ends, without sorting",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.BEGINNER,
            explanation = "Keep a map value → index of what you have seen. For each x, if target − x is in the map you have your pair; otherwise store x. O(n) time, O(n) space. Two pointers only work on sorted input, and nested loops are O(n²).",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Scenario: a signup form must instantly reject an email that is already registered, among 1,000,000 users. Store the emails in:",
            options = listOf(
                "A hash set — each check is O(1) on average",
                "An unsorted list scanned on every signup",
                "A stack, popped until the email is found",
                "A list that is re-sorted before each check",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Hashing",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: normalise the email (trim, lowercase), then if set.contains(email) reject, else set.add(email). A scan is a million comparisons per signup; re-sorting is O(n log n) per signup; popping a stack destroys the data you are checking.",
            linkedTopicId = "set_adt",
            linkedTopicLabel = "Set",
        ),
        QuizQuestion(
            prompt = "Given [100, 4, 200, 1, 3, 2], return the length of the longest run of consecutive integers, in O(n).",
            options = listOf(
                "4 — put everything in a set, and count upwards only from numbers whose n − 1 is missing",
                "6 — the number of distinct values",
                "4 — sort and count the runs, which is O(n)",
                "2 — the longest run of neighbours in the array",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: for each x with x − 1 not in the set, count x, x + 1, … while they are present. Each number is counted once in total, so the whole thing is O(n). Sorting finds the same 4 (1, 2, 3, 4) but costs O(n log n).",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Given nums = [1, 1, 1, 2, 2, 3] and k = 2, return the k most frequent values.",
            options = listOf(
                "[1, 2] — count with a map, then bucket values by frequency (O(n)) or keep a size-k heap",
                "[1, 1] — sort and take the first k",
                "[3, 2] — the k largest values",
                "[1, 2, 3] — every distinct value",
            ),
            correctIndex = 0,
            patternTag = "Top-K",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: counts {1: 3, 2: 2, 3: 1}. Bucket sort: bucket[frequency] = values, then walk from the highest frequency down until you have k. A size-k min-heap gives O(n log k) and handles streaming input.",
            linkedTopicId = "top_k_elements",
            linkedTopicLabel = "Top-K Elements",
        ),
        QuizQuestion(
            prompt = "Scenario: show how often each word appears in a 10,000-word article. Best approach:",
            options = listOf(
                "Map each word to a counter and increment it as you read — O(n)",
                "For each distinct word, rescan the whole article",
                "Sort the words, then binary search for each one",
                "Push every word onto a stack and count while popping",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Counting",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: for each word w (lowercased, punctuation stripped), counts[w] = counts.getOrDefault(w, 0) + 1. One pass. Sorting and counting adjacent runs also works at O(n log n); rescanning per word is O(n²).",
            linkedTopicId = "hash_counting_pattern",
            linkedTopicLabel = "Hashing & Counting",
        ),
        QuizQuestion(
            prompt = "Does an unsorted array contain any duplicate? The O(n) check:",
            options = listOf(
                "Insert each element into a hash set; stop when one is already present",
                "Check whether the array's sum is odd",
                "Compare each element only with its neighbour",
                "Check whether the array is already sorted",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.BEGINNER,
            explanation = "A set remembers everything seen so far, so the first repeat is caught the moment it arrives. Comparing neighbours only works after sorting (O(n log n)), because duplicates in unsorted data need not be adjacent.",
            linkedTopicId = "set_adt",
            linkedTopicLabel = "Set",
        ),
        QuizQuestion(
            prompt = "Group [\"eat\", \"tea\", \"tan\", \"ate\", \"nat\"] into anagram groups. Key the map by:",
            options = listOf(
                "Each word's letters in sorted order",
                "Each word's length",
                "Each word's first letter",
                "Each word's number of vowels",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Anagrams sort to the same string: \"eat\", \"tea\" and \"ate\" all become \"aet\". Length, first letter and vowel count would all put \"tan\" and \"eat\" together, or split real anagrams apart.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Scenario: show the mutual friends of two users, with m and n friends. Best approach:",
            options = listOf(
                "Put one list in a hash set, then check each of the other user's friends — O(m + n)",
                "Compare every friend with every other friend — O(m·n)",
                "Merge both lists and remove duplicates",
                "Sort both lists and return the longer one",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Hashing",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: seen = set(friendsA); mutual = friendsB.filter { it in seen }. Build the set from the smaller list to save memory. Merging and removing duplicates gives the union — everyone either user knows — not the people they share.",
            linkedTopicId = "set_adt",
            linkedTopicLabel = "Set",
        ),
        QuizQuestion(
            prompt = "Why shouldn't you change an object after using it as a hash map key?",
            options = listOf(
                "Its hash changes, so later lookups search the wrong bucket and miss it",
                "Maps copy their keys, so the change is silently ignored",
                "Every language throws an exception when a key is mutated",
                "It forces the map to sort itself again",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The entry was filed under the old hash. After the change, get() hashes to a different bucket and returns nothing, even though the entry is still in the map. Use immutable keys — strings, numbers, data classes with val fields.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
    ),
)

internal val beginnerBigOSet = Quiz(
    id = "beginner_big_o_set",
    title = "Big-O Warm-up",
    description = "Read a loop, name its cost, and check whether an approach fits the input size.",
    questions = listOf(
        QuizQuestion(
            prompt = "A single loop from 0 to n doing constant work each time runs in:",
            options = listOf(
                "O(n) — the body runs once per element",
                "O(1) — a loop is a single statement",
                "O(log n) — the counter grows every time",
                "O(n²) — the loop compares every element",
            ),
            correctIndex = 0,
            patternTag = "Complexity",
            difficulty = Difficulty.BEGINNER,
            explanation = "n iterations × O(1) work = O(n). Double the input and the loop does twice the work — the definition of linear growth.",
            linkedTopicId = "complexity_class_comparison",
            linkedTopicLabel = "Complexity Class Comparison",
        ),
        QuizQuestion(
            prompt = "for (i in 1..n) { var j = 1; while (j < n) j *= 2 } — the total cost:",
            options = listOf(
                "O(n log n) — n outer iterations, each with about log₂ n doublings",
                "O(n²) — two loops always multiply to n²",
                "O(n) — the inner loop is constant",
                "O(log n) — only the doubling matters",
            ),
            correctIndex = 0,
            patternTag = "Complexity",
            difficulty = Difficulty.BEGINNER,
            explanation = "Multiply the cost of each loop: the outer runs n times and the inner doubles j until it reaches n, about log₂ n times. Nested loops are only n² when both loops count up one at a time to n.",
            linkedTopicId = "complexity_class_comparison",
            linkedTopicLabel = "Complexity Class Comparison",
        ),
        QuizQuestion(
            prompt = "for (i = 1; i < n; i *= 2) { … } — how many iterations?",
            options = listOf(
                "O(log n) — i doubles, so it passes n after about log₂ n steps",
                "O(n) — it still reaches n in the end",
                "O(n/2) — it skips every other number",
                "O(√n) — it grows faster than linear",
            ),
            correctIndex = 0,
            patternTag = "Complexity",
            difficulty = Difficulty.BEGINNER,
            explanation = "i takes the values 1, 2, 4, 8 … 2ᵏ, stopping when 2ᵏ ≥ n, so k ≈ log₂ n. For n = 1,000,000 that is only 20 iterations.",
            linkedTopicId = "growth_class_comparison",
            linkedTopicLabel = "Log vs Linear vs Exponential",
        ),
        QuizQuestion(
            prompt = "for (x in items) { if (x in seenList) … } — both have n elements and seenList is a plain list. The cost:",
            options = listOf(
                "O(n²) — `in` on a list is a hidden linear scan; a set makes it O(n)",
                "O(n) — `in` is one operation",
                "O(n log n) — the list is searched by halving",
                "O(1) — both are fixed-size collections",
            ),
            correctIndex = 0,
            patternTag = "Complexity",
            difficulty = Difficulty.BEGINNER,
            explanation = "Library calls have costs too. contains() on a list checks each element; on a hash set it hashes once. Spotting a hidden O(n) call inside a loop is one of the most common interview fixes.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "A loop over array A (size n), followed by a separate loop over array B (size m):",
            options = listOf(
                "O(n + m) — the loops run one after the other",
                "O(n·m) — every pair of loops multiplies",
                "O(max(n, m)²) — the longer loop dominates twice",
                "O(n) — m can always be ignored",
            ),
            correctIndex = 0,
            patternTag = "Complexity",
            difficulty = Difficulty.BEGINNER,
            explanation = "Sequential work adds; nested work multiplies. You cannot drop m because B may be far bigger than A — keep both inputs in the answer.",
            linkedTopicId = "complexity_class_comparison",
            linkedTopicLabel = "Complexity Class Comparison",
        ),
        QuizQuestion(
            prompt = "Scenario: an O(n²) report takes 1 second for 1,000 rows. Roughly how long for 2,000 rows?",
            options = listOf(
                "About 4 seconds — doubling n quadruples n²",
                "About 2 seconds — twice the rows, twice the time",
                "About 1 second — the runtime is fixed",
                "About 8 seconds — each row doubles the time",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Complexity",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: (2,000 / 1,000)² = 2² = 4, so about 4 seconds. At 10,000 rows it would be 10² = 100 seconds — this is how you spot, before shipping, that a quadratic report will not scale.",
            linkedTopicId = "input_size_scaling",
            linkedTopicLabel = "Input Size Scaling",
        ),
        QuizQuestion(
            prompt = "Scenario: n = 1,000,000 with a 1-second limit (about 10⁸ simple operations). Which complexity fits?",
            options = listOf(
                "O(n log n) — about 2 × 10⁷ operations",
                "O(n²) — about 10¹² operations",
                "O(n³) — about 10¹⁸ operations",
                "O(2ⁿ) — the fastest for large n",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Complexity",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: plug n in. n log₂ n ≈ 10⁶ × 20 = 2 × 10⁷, well under 10⁸. n² = 10¹² is roughly 10,000 times over budget. Reading the constraints first tells you which algorithms are even worth trying.",
            linkedTopicId = "complexity_class_comparison",
            linkedTopicLabel = "Complexity Class Comparison",
        ),
        QuizQuestion(
            prompt = "A function that copies its input array before processing it uses how much extra space?",
            options = listOf(
                "O(n) — the copy holds all n elements",
                "O(1) — a copy reuses the original's memory",
                "O(log n) — only half the array is stored",
                "O(n²) — each element is copied n times",
            ),
            correctIndex = 0,
            patternTag = "Complexity",
            difficulty = Difficulty.BEGINNER,
            explanation = "Extra (auxiliary) space counts memory beyond the input. A full copy is n more elements. Interviewers often ask whether you can drop it and work in place for O(1).",
            linkedTopicId = "space_time_tradeoffs",
            linkedTopicLabel = "Space-Time Tradeoffs",
        ),
        QuizQuestion(
            prompt = "T(n) = T(n / 2) + O(n) — for example, a function that does linear work and then recurses on half. It solves to:",
            options = listOf(
                "O(n) — n + n/2 + n/4 + … < 2n",
                "O(n log n) — log n levels of O(n) work",
                "O(log n) — the input halves every call",
                "O(n²) — each call repeats the linear work",
            ),
            correctIndex = 0,
            patternTag = "Complexity",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: the work shrinks geometrically, so the first call dominates and the total stays under 2n. O(n log n) needs two half-sized calls per level, as in merge sort's T(n) = 2T(n / 2) + O(n).",
            linkedTopicId = "master_theorem",
            linkedTopicLabel = "Master Theorem",
        ),
        QuizQuestion(
            prompt = "var s = \"\"; for (c in chars) s += c — building a string of n characters this way costs:",
            options = listOf(
                "O(n²) — each += copies the whole string so far; a StringBuilder makes it O(n)",
                "O(n) — each append is constant",
                "O(n log n) — the string doubles like an array",
                "O(1) — strings are cached",
            ),
            correctIndex = 0,
            patternTag = "Complexity",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Strings are immutable in Java, Kotlin and Python, so s += c builds a new string: 1 + 2 + … + n = O(n²) characters copied. StringBuilder (or \"\".join) appends into a growing buffer in amortised O(1).",
            linkedTopicId = "string",
            linkedTopicLabel = "String",
        ),
    ),
)

internal val beginnerLinearStructuresSet = Quiz(
    id = "beginner_linear_structures_set",
    title = "Stacks, Queues & Lists Warm-up",
    description = "Pick the right container for everyday features — back buttons, print queues, undo.",
    questions = listOf(
        QuizQuestion(
            prompt = "Scenario: a browser's Back button returns to the page you visited most recently. Store the history in:",
            options = listOf(
                "A stack — the most recent page comes off first",
                "A queue — the oldest page comes back first",
                "A hash set — pages have no order",
                "A sorted array — pages ordered by URL",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Stack",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: push each page when you navigate away; Back pops the top. Last in, first out is exactly \"most recent first\". A queue would take you back to the first page you opened.",
            linkedTopicId = "stack",
            linkedTopicLabel = "Stack",
        ),
        QuizQuestion(
            prompt = "Scenario: an office printer must print jobs in the order they were sent. Use:",
            options = listOf(
                "A queue — first in, first out",
                "A stack — the newest job prints first",
                "A heap keyed by page count",
                "A hash map keyed by file name",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Queue",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: enqueue at the back when a job arrives; the printer dequeues from the front. Both are O(1). A stack would starve the earliest jobs; a heap by page count reorders them.",
            linkedTopicId = "queue",
            linkedTopicLabel = "Queue",
        ),
        QuizQuestion(
            prompt = "Evaluate the Reverse Polish Notation tokens [\"2\", \"1\", \"+\", \"3\", \"*\"].",
            options = listOf(
                "9 — push numbers; on an operator pop two, apply it, push the result",
                "6 — add up every number",
                "7 — apply the operators right to left",
                "5 — ignore the operators after the first",
            ),
            correctIndex = 0,
            patternTag = "Stack",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: push 2, push 1; '+' pops 1 and 2 and pushes 3; push 3; '*' pops 3 and 3 and pushes 9. The first value popped is the right-hand operand — that matters for '−' and '/'.",
            linkedTopicId = "stack",
            linkedTopicLabel = "Stack",
        ),
        QuizQuestion(
            prompt = "Inserting a new node at the head of a singly linked list costs:",
            options = listOf(
                "O(1) — point the new node at the old head, then move head",
                "O(n) — every node shifts one position right",
                "O(log n) — the list is searched for the right spot",
                "O(n) — the tail must be found first",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.BEGINNER,
            explanation = "node.next = head; head = node. Two pointer writes, nothing moves. That constant-time front insert is the main thing a linked list offers over an array.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Reverse a singly linked list in place:",
            options = listOf(
                "Walk it with prev, curr and next pointers, flipping each next pointer",
                "Copy the values into an array, sort them descending, write them back",
                "Swap the head and tail nodes only",
                "Delete each node and re-insert it at the tail",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.BEGINNER,
            explanation = "Loop: next = curr.next; curr.next = prev; prev = curr; curr = next. When curr is null, prev is the new head. O(n) time, O(1) space. Sorting descending reverses values only if they happened to be sorted.",
            linkedTopicId = "in_place_reversal_pattern",
            linkedTopicLabel = "In-place Linked List Reversal",
        ),
        QuizQuestion(
            prompt = "Find the middle node of a linked list in a single pass:",
            options = listOf(
                "Slow pointer moves 1, fast moves 2; when fast reaches the end, slow is the middle",
                "Jump straight to index n / 2",
                "Reverse the list and take the new head",
                "Count backwards from the tail",
            ),
            correctIndex = 0,
            patternTag = "Fast & Slow Pointers",
            difficulty = Difficulty.BEGINNER,
            explanation = "Fast covers twice the distance, so it hits the end exactly when slow is halfway. Lists have no index access and singly linked lists cannot walk backwards, which rules out the other options.",
            linkedTopicId = "fast_slow_pointers",
            linkedTopicLabel = "Fast & Slow Pointers",
        ),
        QuizQuestion(
            prompt = "Remove the n-th node from the end of a linked list, in one pass.",
            options = listOf(
                "Move a lead pointer n steps ahead, then advance both until the lead reaches the end",
                "Reverse the list, delete the n-th node, then reverse it back",
                "Jump straight to index length − n",
                "Delete the head n times",
            ),
            correctIndex = 0,
            patternTag = "Two Pointer",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: start both at a dummy head; move lead n + 1 steps; advance both until lead is null. The trailing pointer is now just before the target, so trail.next = trail.next.next. The dummy handles removing the head. Reversing twice works but takes three passes.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Scenario: a text editor needs both Undo and Redo. Store the edits in:",
            options = listOf(
                "Two stacks — undo pops from one and pushes onto the other",
                "One queue shared by undo and redo",
                "A single array scanned from the start",
                "A hash map keyed by edit timestamp",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Stack",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: each edit pushes onto undoStack and clears redoStack. Undo: pop from undoStack, revert it, push onto redoStack. Redo: the reverse. Clearing redo on a new edit matters — otherwise redo would replay onto text that has changed since.",
            linkedTopicId = "stack",
            linkedTopicLabel = "Stack",
        ),
        QuizQuestion(
            prompt = "Merge two sorted linked lists into one sorted list.",
            options = listOf(
                "Dummy head; repeatedly attach the smaller front node and advance that list — O(m + n)",
                "Concatenate the lists, then sort the result",
                "Alternate one node from each list",
                "Insert each node of list two into list one using binary search",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: tail = dummy; while both remain, attach the smaller head to tail and advance it; finally attach whatever is left. No new nodes are created. Alternating ignores the values, and binary search does not work on a linked list.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Scenario: a support chat serves customers in arrival order, but VIP customers jump ahead. Use:",
            options = listOf(
                "A priority queue (heap) ordered by priority, then arrival time",
                "A plain stack",
                "A plain FIFO queue",
                "An unsorted array, picking a random customer",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Heap",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: key each customer as (isVip ? 0 : 1, arrivalTime) in a min-heap. Poll returns the earliest VIP, or the earliest regular customer if no VIP is waiting. O(log n) insert and poll. A plain queue ignores VIPs.",
            linkedTopicId = "heap",
            linkedTopicLabel = "Heap (Min / Max)",
            figure = Figure(
                caption = "Waiting customers, in arrival order",
                shape = FigureShape.Strip(
                    cells = listOf("Ann", "Raj", "Li", "Mo", "Sara"),
                    aux = listOf("", "VIP", "", "VIP", ""),
                    auxLabel = "tier",
                ),
            ),
        ),
    ),
)

internal val beginnerRecursionSearchSet = Quiz(
    id = "beginner_recursion_search_set",
    title = "Recursion, Sorting & Search Warm-up",
    description = "Recursion, binary search variants and one-pass sorting.",
    questions = listOf(
        QuizQuestion(
            prompt = "You can climb 1 or 2 steps at a time. How many different ways are there to climb 5 steps?",
            options = listOf(
                "8 — ways(n) = ways(n − 1) + ways(n − 2), with ways(1) = 1 and ways(2) = 2",
                "5 — one way per step",
                "10 — 5 × 2",
                "32 — 2⁵",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: the last move was either a 1-step from stair n − 1 or a 2-step from n − 2, so the counts add: 1, 2, 3, 5, 8. That is Fibonacci. Two variables give O(n) time and O(1) space; 2⁵ counts sequences that overshoot the top.",
            linkedTopicId = "fibonacci_dp",
            linkedTopicLabel = "Fibonacci (Dynamic Programming)",
        ),
        QuizQuestion(
            prompt = "sum(n) = n + sum(n − 1), with sum(0) = 0. What does sum(4) return?",
            options = listOf("10", "4", "24", "0"),
            correctIndex = 0,
            patternTag = "Recursion",
            difficulty = Difficulty.BEGINNER,
            explanation = "Unroll it: 4 + sum(3) = 4 + 3 + sum(2) = 4 + 3 + 2 + 1 + sum(0) = 10. Tracing a small input by hand is how you check recursive code before running it. (24 would be 4!, which multiplies.)",
            linkedTopicId = "factorial",
            linkedTopicLabel = "Factorial",
        ),
        QuizQuestion(
            prompt = "Binary search only works when:",
            options = listOf(
                "The data is sorted",
                "The data has no duplicates",
                "The array length is a power of two",
                "The data fits in a hash map",
            ),
            correctIndex = 0,
            patternTag = "Binary Search",
            difficulty = Difficulty.BEGINNER,
            explanation = "Each step compares with the middle and throws away the half that cannot contain the target. That is only safe when order tells you which side the target is on.",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
        ),
        QuizQuestion(
            prompt = "Scenario: guess a number from 1 to 100; after each guess you hear \"higher\" or \"lower\". Worst-case guesses with the best strategy:",
            options = listOf(
                "7 — halve the range every guess (2⁷ = 128 ≥ 100)",
                "10 — one guess per ten numbers",
                "50 — half of the range",
                "100 — one guess per number",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Binary Search",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: guess 50; \"higher\" leaves 51–100, so guess 75, and so on. The range goes 100 → 50 → 25 → 13 → 7 → 4 → 2 → 1: at most 7 guesses, which is ⌈log₂ 100⌉.",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
        ),
        QuizQuestion(
            prompt = "Scenario: builds 1 to 1,000 are released in order; from some build onward they are all broken. Find the first broken build with the fewest tests:",
            options = listOf(
                "Binary search on build number — about 10 tests",
                "Test every build from the first — up to 1,000 tests",
                "Test every other build — about 500 tests",
                "Test only the newest build",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Binary Search",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: lo = 1, hi = 1000. While lo < hi: mid = (lo + hi) / 2; if broken(mid) then hi = mid, else lo = mid + 1. lo is the answer. Broken-ness is sorted (good…good, bad…bad), so you binary-search for the boundary, not for a value.",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
            figure = Figure(
                caption = "Builds in release order — only a few tested so far",
                shape = FigureShape.Strip(
                    cells = listOf("1", "2", "…", "?", "?", "…", "999", "1000"),
                    aux = listOf("ok", "ok", "", "", "", "", "bad", "bad"),
                    auxLabel = "tested",
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Sort [2, 0, 2, 1, 1, 0] (values 0, 1, 2 only) in one pass with O(1) extra space.",
            options = listOf(
                "Three pointers low / mid / high: swap 0s to low and 2s to high",
                "Counting sort — two passes",
                "The built-in sort",
                "Bubble sort",
            ),
            correctIndex = 0,
            patternTag = "Partitioning",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: while mid ≤ high: 0 → swap(low++, mid++); 1 → mid++; 2 → swap(mid, high--) and do not advance mid, because the swapped-in value is still unchecked. Counting sort is correct but takes two passes, which the question rules out.",
            linkedTopicId = "dutch_flag_pattern",
            linkedTopicLabel = "In-place Partitioning",
        ),
        QuizQuestion(
            prompt = "Return the minimum of a rotated sorted array such as [4, 5, 6, 7, 0, 1, 2], in O(log n).",
            options = listOf(
                "Binary search: if nums[mid] > nums[hi], the minimum is right of mid; otherwise it is at mid or to its left",
                "Return the first element",
                "A linear scan — the only correct way",
                "Binary search for the value 0",
            ),
            correctIndex = 0,
            patternTag = "Modified Binary Search",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: lo = 0, hi = n − 1; while lo < hi: mid = (lo + hi) / 2; if nums[mid] > nums[hi] then lo = mid + 1 else hi = mid. Return nums[lo]. Comparing with nums[hi] tells you which half holds the drop. (Assumes distinct values.)",
            linkedTopicId = "modified_binary_search_pattern",
            linkedTopicLabel = "Modified Binary Search",
        ),
        QuizQuestion(
            prompt = "Search an m × n matrix whose rows are sorted and each row starts above the previous row's end.",
            options = listOf(
                "Treat it as one sorted array of m·n values and binary search — O(log(m·n))",
                "Binary search each row separately — O(m log n)",
                "Scan every cell — O(m·n)",
                "Search only the diagonal",
            ),
            correctIndex = 0,
            patternTag = "Binary Search",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: lo = 0, hi = m·n − 1; index k maps to matrix[k / n][k % n]. Because each row continues where the last one ended, the flattened order is fully sorted. Searching row by row is correct but slower.",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
        ),
        QuizQuestion(
            prompt = "Scenario: a leaderboard of 20 sorted scores gets one new score added at the end. Re-sort it with:",
            options = listOf(
                "Insertion sort — nearly sorted input runs in close to O(n)",
                "Selection sort — it always makes O(n²) comparisons",
                "Bubble sort with no early exit",
                "Shuffle it first, then sort",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Sorting",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: insertion sort slides the new score left until it sits behind a larger one — at most 20 shifts. Everything else is already in place, so it barely does any work. Selection sort does the full O(n²) scan whatever the input.",
            linkedTopicId = "insertion_sort",
            linkedTopicLabel = "Insertion Sort",
        ),
        QuizQuestion(
            prompt = "Scenario: list every possible play order for 3 songs. Approach and count:",
            options = listOf(
                "Backtracking: pick an unused song, recurse, then un-pick — 3! = 6 orders",
                "One loop over the songs — 3 orders",
                "Sort the songs — 1 order",
                "Binary search the songs — log₂ 3 orders",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Backtracking",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: at each position try every song not yet used, recurse to fill the rest, then remove it and try the next. 3 choices, then 2, then 1: 3 × 2 × 1 = 6. The un-pick step is what lets one list be reused for every branch.",
            linkedTopicId = "permutation_generation",
            linkedTopicLabel = "Permutation Generation",
        ),
    ),
)
