package com.algora.app.feature.interviewprep.quiz

import com.algora.app.core.data.model.Difficulty

// AI-mode subject quizzes. Same six-question, four-minute shape as the DSA subject quizzes; every
// question links back into the ML / DL / NLP / RL taxonomy.

private const val AI_TIME_LIMIT = 240

internal val mlFoundationsQuiz = Quiz(
    id = "ml_foundations_quiz",
    title = "ML Foundations",
    description = "Bias/variance, loss functions and evaluation.",
    timeLimitSeconds = AI_TIME_LIMIT,
    questions = listOf(
        QuizQuestion(
            prompt = "A model with low training error and high test error is:",
            options = listOf("Overfitting — high variance", "Underfitting — high bias", "Perfectly regularised", "Undertrained"),
            correctIndex = 0,
            patternTag = "Bias & Variance",
            difficulty = Difficulty.BEGINNER,
            explanation = "It memorised noise specific to the training set. Regularisation, more data, or a simpler model close the gap.",
            linkedTopicId = "decision_trees",
            linkedTopicLabel = "Decision Trees",
        ),
        QuizQuestion(
            prompt = "Linear regression minimises which loss by default?",
            options = listOf("Mean squared error", "Cross-entropy", "Hinge loss", "KL divergence"),
            correctIndex = 0,
            patternTag = "Loss Functions",
            difficulty = Difficulty.BEGINNER,
            explanation = "Squared error has a closed-form solution and penalises large residuals quadratically — which also makes it outlier-sensitive.",
            linkedTopicId = "linear_regression",
            linkedTopicLabel = "Linear Regression",
        ),
        QuizQuestion(
            prompt = "Logistic regression is used for classification because it:",
            options = listOf(
                "Squashes a linear score into a probability with the sigmoid",
                "Fits a straight line to class labels",
                "Requires no training",
                "Always produces a hard 0 or 1",
            ),
            correctIndex = 0,
            patternTag = "Classification",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The linear score becomes a calibrated probability, trained with cross-entropy rather than squared error.",
            linkedTopicId = "logistic_regression",
            linkedTopicLabel = "Logistic Regression",
        ),
        QuizQuestion(
            prompt = "On a heavily imbalanced dataset, accuracy misleads because:",
            options = listOf(
                "Always predicting the majority class already scores high",
                "It cannot be computed",
                "It ignores the training set",
                "It requires probabilities",
            ),
            correctIndex = 0,
            patternTag = "Evaluation",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "At 99% negatives a trivial model scores 99%. Precision, recall, F1 or AUC expose what it actually missed.",
            linkedTopicId = "naive_bayes",
            linkedTopicLabel = "Naive Bayes",
        ),
        QuizQuestion(
            prompt = "k-NN is called a lazy learner because it:",
            options = listOf(
                "Does no work at training time and all of it at prediction time",
                "Converges slowly",
                "Uses a small k",
                "Ignores distant points",
            ),
            correctIndex = 0,
            patternTag = "Instance-Based Learning",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "It stores the training set and searches neighbours per query, so prediction cost grows with the dataset.",
            linkedTopicId = "knn",
            linkedTopicLabel = "k-Nearest Neighbors",
        ),
        QuizQuestion(
            prompt = "PCA reduces dimensionality by projecting onto:",
            options = listOf(
                "The directions of greatest variance",
                "The axes with the smallest values",
                "Randomly chosen axes",
                "The class boundaries",
            ),
            correctIndex = 0,
            patternTag = "Dimensionality Reduction",
            difficulty = Difficulty.ADVANCED,
            explanation = "Top eigenvectors of the covariance matrix retain the most information. It is unsupervised, so it can discard a low-variance but discriminative direction.",
            linkedTopicId = "pca",
            linkedTopicLabel = "PCA",
        ),
    ),
)

internal val deepLearningQuiz = Quiz(
    id = "deep_learning_quiz",
    title = "Deep Learning",
    description = "Backpropagation, activations and regularisation.",
    timeLimitSeconds = AI_TIME_LIMIT,
    questions = listOf(
        QuizQuestion(
            prompt = "Backpropagation computes gradients by:",
            options = listOf(
                "Applying the chain rule backwards through the network",
                "Perturbing each weight and re-running the forward pass",
                "Randomly sampling gradients",
                "Inverting the weight matrices",
            ),
            correctIndex = 0,
            patternTag = "Backpropagation",
            difficulty = Difficulty.BEGINNER,
            explanation = "One backward pass reuses cached forward activations to get every gradient — finite differences would cost one forward pass per weight.",
            linkedTopicId = "backpropagation",
            linkedTopicLabel = "Backpropagation",
        ),
        QuizQuestion(
            prompt = "A network with only linear activations is equivalent to:",
            options = listOf("A single linear layer, no matter the depth", "A decision tree", "A convolutional network", "A universal approximator"),
            correctIndex = 0,
            patternTag = "Activation Functions",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Composing linear maps yields a linear map. Non-linearity is what depth actually buys.",
            linkedTopicId = "activation_functions",
            linkedTopicLabel = "Activation Functions",
        ),
        QuizQuestion(
            prompt = "ReLU is preferred over sigmoid in hidden layers mainly because it:",
            options = listOf(
                "Does not saturate for positive inputs, easing vanishing gradients",
                "Is bounded between 0 and 1",
                "Is smooth everywhere",
                "Guarantees convergence",
            ),
            correctIndex = 0,
            patternTag = "Activation Functions",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Sigmoid gradients shrink toward zero at both tails, stalling deep networks. ReLU's own failure mode is dead units on the negative side.",
            linkedTopicId = "activation_functions",
            linkedTopicLabel = "Activation Functions",
        ),
        QuizQuestion(
            prompt = "Dropout regularises by:",
            options = listOf(
                "Randomly zeroing activations during training so no unit is relied on alone",
                "Removing layers permanently",
                "Shrinking the learning rate",
                "Discarding training examples",
            ),
            correctIndex = 0,
            patternTag = "Regularisation",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "It approximates averaging many thinned networks. Dropout is disabled at inference, with activations scaled to compensate.",
            linkedTopicId = "neural_network_basics",
            linkedTopicLabel = "Neural Network Basics",
        ),
        QuizQuestion(
            prompt = "A CNN suits images because convolution provides:",
            options = listOf(
                "Local receptive fields and shared weights, giving translation equivariance",
                "Full connectivity between all pixels",
                "Guaranteed rotation invariance",
                "Sequence modelling",
            ),
            correctIndex = 0,
            patternTag = "CNN",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "One kernel is reused across the image, cutting parameters massively and detecting a feature wherever it appears.",
            linkedTopicId = "cnn",
            linkedTopicLabel = "CNNs",
        ),
        QuizQuestion(
            prompt = "LSTMs handle long sequences better than vanilla RNNs because they:",
            options = listOf(
                "Carry a gated cell state that lets gradients flow further",
                "Process the sequence in parallel",
                "Use convolutions internally",
                "Have fewer parameters",
            ),
            correctIndex = 0,
            patternTag = "RNN",
            difficulty = Difficulty.ADVANCED,
            explanation = "Gates control what is written, kept and read, easing vanishing gradients. Transformers later removed recurrence altogether for parallelism.",
            linkedTopicId = "lstm_gru",
            linkedTopicLabel = "LSTMs / GRUs",
        ),
    ),
)

internal val nlpRlQuiz = Quiz(
    id = "nlp_rl_quiz",
    title = "NLP & RL",
    description = "Embeddings, attention, rewards and policies.",
    timeLimitSeconds = AI_TIME_LIMIT,
    questions = listOf(
        QuizQuestion(
            prompt = "Word embeddings improve on one-hot encoding because they:",
            options = listOf(
                "Place similar words near each other in a dense low-dimensional space",
                "Use less training data",
                "Are always sparse",
                "Require no vocabulary",
            ),
            correctIndex = 0,
            patternTag = "Embeddings",
            difficulty = Difficulty.BEGINNER,
            explanation = "One-hot vectors are equidistant, encoding no similarity. Embeddings put semantic structure into the geometry.",
            linkedTopicId = "word_embeddings",
            linkedTopicLabel = "Word Embeddings",
        ),
        QuizQuestion(
            prompt = "TF-IDF down-weights a term that:",
            options = listOf("Appears in nearly every document", "Appears rarely overall", "Is long", "Appears at the start of a document"),
            correctIndex = 0,
            patternTag = "Text Representation",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The inverse document frequency factor suppresses ubiquitous terms, which carry little discriminative signal.",
            linkedTopicId = "bow_tfidf",
            linkedTopicLabel = "Bag-of-Words / TF-IDF",
        ),
        QuizQuestion(
            prompt = "Self-attention lets a transformer:",
            options = listOf(
                "Relate every token to every other in one layer, in parallel",
                "Process tokens strictly left to right",
                "Avoid needing positional information",
                "Work only on fixed-length input",
            ),
            correctIndex = 0,
            patternTag = "Attention",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Direct token-to-token paths remove recurrence, at O(n²) cost in sequence length. Positional encodings are added back because attention is order-agnostic.",
            linkedTopicId = "attention",
            linkedTopicLabel = "Attention",
        ),
        QuizQuestion(
            prompt = "In an MDP, the discount factor γ controls:",
            options = listOf(
                "How much future rewards count relative to immediate ones",
                "The learning rate",
                "The exploration probability",
                "The size of the state space",
            ),
            correctIndex = 0,
            patternTag = "MDP",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "γ near 0 is myopic; near 1 is far-sighted and also keeps returns finite in continuing tasks.",
            linkedTopicId = "mdp",
            linkedTopicLabel = "MDP",
        ),
        QuizQuestion(
            prompt = "Q-learning is called off-policy because it:",
            options = listOf(
                "Learns the greedy policy's values while behaving with a different, exploratory policy",
                "Never updates its policy",
                "Requires a model of the environment",
                "Only works offline",
            ),
            correctIndex = 0,
            patternTag = "Q-Learning",
            difficulty = Difficulty.ADVANCED,
            explanation = "The update uses max over next actions regardless of what was actually taken. SARSA, which uses the action taken, is the on-policy counterpart.",
            linkedTopicId = "q_learning",
            linkedTopicLabel = "Q-Learning (off-policy)",
        ),
        QuizQuestion(
            prompt = "Experience replay in DQN mainly exists to:",
            options = listOf(
                "Break the correlation between consecutive samples and reuse past data",
                "Increase the discount factor",
                "Remove the need for a target network",
                "Make the policy deterministic",
            ),
            correctIndex = 0,
            patternTag = "DQN",
            difficulty = Difficulty.ADVANCED,
            explanation = "Sequential transitions are highly correlated, which destabilises gradient updates. Sampling a buffer restores something closer to i.i.d. data.",
            linkedTopicId = "experience_replay",
            linkedTopicLabel = "Experience Replay",
        ),
    ),
)

internal val transformersLlmQuiz = Quiz(
    id = "transformers_llm_quiz",
    title = "Transformers & LLMs",
    description = "Attention cost, positional information, pretraining and decoding.",
    timeLimitSeconds = AI_TIME_LIMIT,
    questions = listOf(
        QuizQuestion(
            prompt = "Self-attention over a sequence of length n costs:",
            options = listOf("O(n²) — every token attends to every other", "O(n)", "O(n log n)", "O(1)"),
            correctIndex = 0,
            patternTag = "Transformers",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The score matrix is n × n, which is why long-context models need sparse, linear or flash-attention variants.",
            linkedTopicId = "transformers",
            linkedTopicLabel = "Transformers",
        ),
        QuizQuestion(
            prompt = "Transformers need positional encodings because attention is:",
            options = listOf("Permutation-invariant — it sees a set, not a sequence", "Too slow otherwise", "Unable to use embeddings", "Restricted to short input"),
            correctIndex = 0,
            patternTag = "Transformers",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Shuffling the input permutes the output identically. Position must be injected, by sinusoids, learned vectors or rotary embeddings.",
            linkedTopicId = "transformers",
            linkedTopicLabel = "Transformers",
        ),
        QuizQuestion(
            prompt = "Dividing attention scores by √d prevents:",
            options = listOf(
                "Large dot products pushing softmax into a saturated, low-gradient regime",
                "Numerical underflow in the values",
                "The keys and queries from differing in size",
                "Overfitting",
            ),
            correctIndex = 0,
            patternTag = "Attention",
            difficulty = Difficulty.ADVANCED,
            explanation = "Dot products grow with dimension. Unscaled, softmax approaches one-hot and gradients vanish.",
            linkedTopicId = "attention",
            linkedTopicLabel = "Attention",
        ),
        QuizQuestion(
            prompt = "Multi-head attention helps because different heads can:",
            options = listOf(
                "Attend to different relationships in parallel subspaces",
                "Process longer sequences",
                "Remove the need for feed-forward layers",
                "Guarantee interpretability",
            ),
            correctIndex = 0,
            patternTag = "Transformers",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Each head projects into its own subspace, so one may track syntax while another tracks coreference. A single head must average all of it.",
            linkedTopicId = "transformers",
            linkedTopicLabel = "Transformers",
        ),
        QuizQuestion(
            prompt = "Greedy decoding differs from sampling in that it:",
            options = listOf(
                "Always takes the highest-probability token, producing repetitive but stable text",
                "Is slower",
                "Requires a larger model",
                "Ignores the softmax",
            ),
            correctIndex = 0,
            patternTag = "LLMs",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Determinism costs diversity — hence temperature, top-k and nucleus sampling as middle grounds.",
            linkedTopicId = "llms",
            linkedTopicLabel = "LLMs",
        ),
        QuizQuestion(
            prompt = "Subword tokenisation such as BPE mainly solves:",
            options = listOf(
                "Out-of-vocabulary words, by splitting rare words into known pieces",
                "The quadratic cost of attention",
                "Positional encoding",
                "Gradient vanishing",
            ),
            correctIndex = 0,
            patternTag = "Tokenization",
            difficulty = Difficulty.ADVANCED,
            explanation = "Word-level vocabularies map anything unseen to a single unknown token. Subwords keep rare words representable at a bounded vocabulary size.",
            linkedTopicId = "tokenization",
            linkedTopicLabel = "Tokenization",
        ),
    ),
)

internal val rlAlgorithmsQuiz = Quiz(
    id = "rl_algorithms_quiz",
    title = "RL Algorithms",
    description = "Value versus policy methods, stability tricks and exploration.",
    timeLimitSeconds = AI_TIME_LIMIT,
    questions = listOf(
        QuizQuestion(
            prompt = "The difference between Q-learning and SARSA is that SARSA's target uses:",
            options = listOf(
                "The action actually taken next, making it on-policy",
                "A discount factor of 1",
                "No reward term",
                "A neural network",
            ),
            correctIndex = 0,
            patternTag = "Q-Learning",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Q-learning bootstraps from max over next actions regardless of behaviour; SARSA follows its own policy, making it more conservative near cliffs.",
            linkedTopicId = "q_learning",
            linkedTopicLabel = "Q-Learning (off-policy)",
        ),
        QuizQuestion(
            prompt = "A target network in DQN exists to:",
            options = listOf(
                "Hold the bootstrap target fixed for a while so training does not chase a moving goal",
                "Double the batch size",
                "Replace the replay buffer",
                "Add exploration noise",
            ),
            correctIndex = 0,
            patternTag = "DQN",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Without it the target shifts every gradient step, since the same network produces both prediction and target.",
            linkedTopicId = "target_networks",
            linkedTopicLabel = "Target Networks",
        ),
        QuizQuestion(
            prompt = "Double DQN reduces which specific failure of DQN?",
            options = listOf(
                "Overestimation bias from taking a max over noisy value estimates",
                "Slow convergence on small state spaces",
                "Excessive exploration",
                "Memory usage",
            ),
            correctIndex = 0,
            patternTag = "DQN",
            difficulty = Difficulty.ADVANCED,
            explanation = "It decouples action selection from evaluation — one network picks the argmax, the other scores it.",
            linkedTopicId = "double_dqn",
            linkedTopicLabel = "Double DQN",
        ),
        QuizQuestion(
            prompt = "Policy-gradient methods are preferred over value-based ones when:",
            options = listOf(
                "The action space is continuous or a stochastic policy is required",
                "The state space is small",
                "Rewards are always positive",
                "The environment is deterministic",
            ),
            correctIndex = 0,
            patternTag = "Policy Gradient",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A max over a continuous action space is intractable; policy methods parameterise the action distribution directly.",
            linkedTopicId = "reinforce",
            linkedTopicLabel = "REINFORCE",
        ),
        QuizQuestion(
            prompt = "A baseline subtracted from the return in REINFORCE:",
            options = listOf(
                "Reduces gradient variance without biasing the estimate",
                "Increases the learning rate",
                "Guarantees convergence",
                "Removes the need for a discount factor",
            ),
            correctIndex = 0,
            patternTag = "Policy Gradient",
            difficulty = Difficulty.ADVANCED,
            explanation = "Any action-independent baseline has zero expected contribution. Using the value function as the baseline gives the advantage, which is actor-critic.",
            linkedTopicId = "actor_critic",
            linkedTopicLabel = "Actor-Critic",
        ),
        QuizQuestion(
            prompt = "PPO's clipped objective exists to:",
            options = listOf(
                "Stop a single update from moving the policy too far from the one that collected the data",
                "Speed up the forward pass",
                "Eliminate the value network",
                "Force deterministic actions",
            ),
            correctIndex = 0,
            patternTag = "PPO",
            difficulty = Difficulty.ADVANCED,
            explanation = "Large policy jumps invalidate the sampled data and can collapse performance. Clipping is a cheap stand-in for TRPO's trust region.",
            linkedTopicId = "ppo",
            linkedTopicLabel = "PPO",
        ),
    ),
)

// Mixed AI round for the AI Interview category — the counterpart of timedMockInterview.
internal val aiMockInterview = Quiz(
    id = "ai_ml_mock_interview",
    title = "AI/ML Mock Interview",
    description = "Six mixed ML, DL, NLP and RL questions under a five-minute clock.",
    timeLimitSeconds = 300,
    questions = listOf(
        QuizQuestion(
            prompt = "A model scores 0.99 training accuracy and 0.62 on validation. The first thing to try is:",
            options = listOf(
                "Regularisation or more data — it is overfitting",
                "A larger model",
                "A higher learning rate",
                "More training epochs",
            ),
            correctIndex = 0,
            patternTag = "Bias & Variance",
            difficulty = Difficulty.BEGINNER,
            explanation = "The gap is variance, not bias. Dropout, weight decay, augmentation or more data close it; a bigger model widens it.",
            linkedTopicId = "decision_trees",
            linkedTopicLabel = "Decision Trees",
        ),
        QuizQuestion(
            prompt = "Features on wildly different scales hurt k-NN and gradient descent because:",
            options = listOf(
                "Distance and gradient steps become dominated by the largest-scale feature",
                "The model cannot store them",
                "Labels become unbalanced",
                "It only affects tree models",
            ),
            correctIndex = 0,
            patternTag = "Preprocessing",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Standardising fixes both. Tree-based models are the ones genuinely scale-invariant.",
            linkedTopicId = "knn",
            linkedTopicLabel = "k-Nearest Neighbors",
        ),
        QuizQuestion(
            prompt = "Validation data leaking into training typically shows up as:",
            options = listOf(
                "Excellent validation scores that collapse in production",
                "Training loss that never decreases",
                "Exploding gradients",
                "Slower epochs",
            ),
            correctIndex = 0,
            patternTag = "Evaluation",
            difficulty = Difficulty.ADVANCED,
            explanation = "Fitting the scaler or selecting features on the full dataset before splitting is the usual cause — the split must come first.",
            linkedTopicId = "pca",
            linkedTopicLabel = "PCA",
        ),
        QuizQuestion(
            prompt = "Training loss decreasing while gradients in early layers approach zero indicates:",
            options = listOf(
                "Vanishing gradients — the early layers have effectively stopped learning",
                "A learning rate that is too high",
                "Label noise",
                "Too small a batch size",
            ),
            correctIndex = 0,
            patternTag = "Deep Learning",
            difficulty = Difficulty.ADVANCED,
            explanation = "Saturating activations and depth compound the shrinkage. ReLU, residual connections and normalisation are the standard remedies.",
            linkedTopicId = "activation_functions",
            linkedTopicLabel = "Activation Functions",
        ),
        QuizQuestion(
            prompt = "For a text classifier with a small labelled dataset, the strongest first move is usually:",
            options = listOf(
                "Fine-tune a pretrained language model",
                "Train a transformer from scratch",
                "Use one-hot word vectors",
                "Increase the vocabulary size",
            ),
            correctIndex = 0,
            patternTag = "NLP",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Pretraining supplies the language knowledge the small dataset cannot. Training from scratch needs orders of magnitude more data.",
            linkedTopicId = "llms",
            linkedTopicLabel = "LLMs",
        ),
        QuizQuestion(
            prompt = "An RL agent that gets stuck repeating one mediocre action most likely needs:",
            options = listOf(
                "More exploration — a higher ε, entropy bonus or optimistic initialisation",
                "A smaller discount factor",
                "A larger replay buffer only",
                "A deterministic policy",
            ),
            correctIndex = 0,
            patternTag = "Exploration",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Premature convergence on a locally good action is an exploration failure — the agent never sampled the better one often enough to value it.",
            linkedTopicId = "q_learning",
            linkedTopicLabel = "Q-Learning (off-policy)",
        ),
    ),
)
