package com.algora.app.feature.interviewprep.quiz

import com.algora.app.core.data.model.Difficulty

// Coding rounds: every question is stated the way an interviewer poses it — "given …, return …" —
// and the options are the candidate approaches. The explanation carries the solve (steps, a worked
// example where it helps, complexity) and why the tempting wrong answer fails.

internal val beginnerCodingArraysSet = Quiz(
    id = "beginner_coding_arrays_set",
    title = "Coding Round: Arrays & Hashing",
    description = "Ten classic array and hashing problems, posed the way an interviewer asks them.",
    questions = listOf(
        QuizQuestion(
            prompt = "Given nums, return an array where output[i] is the product of every element except nums[i] — in O(n), without division.",
            options = listOf(
                "Prefix products left to right, then multiply in suffix products right to left",
                "Multiply everything once, then divide by nums[i]",
                "Nested loops multiplying every j ≠ i",
                "Sort the array and multiply neighbours",
            ),
            correctIndex = 0,
            patternTag = "Prefix Products",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: out[i] = product of everything left of i (one forward pass), then walk backwards with a running suffix product and multiply it in. [1, 2, 3, 4] → [24, 12, 8, 6]. O(n) time, O(1) extra besides the output. Division is banned, and it breaks on a zero anyway.",
            linkedTopicId = "prefix_sum",
            linkedTopicLabel = "Prefix Sum",
        ),
        QuizQuestion(
            prompt = "Given nums, return every unique triplet [a, b, c] with a + b + c = 0.",
            options = listOf(
                "Sort, fix each i, then two pointers over the rest, skipping repeated values — O(n²)",
                "Three nested loops plus a set of sorted triplets — O(n³)",
                "Hash every pair sum without sorting — O(n)",
                "Binary search for the third value without sorting",
            ),
            correctIndex = 0,
            patternTag = "Two Pointer",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: sort. For each i (skip if nums[i] == nums[i − 1]), set l = i + 1, r = n − 1; move l up if the sum is too small, r down if too big, and on a hit record it and skip duplicates on both sides. Sorting is what makes both the pointers and the de-duplication work.",
            linkedTopicId = "two_pointer_pattern",
            linkedTopicLabel = "Two Pointer Pattern",
        ),
        QuizQuestion(
            prompt = "Given nums where one value appears more than n / 2 times, return it in O(n) time and O(1) space.",
            options = listOf(
                "Boyer-Moore voting: keep a candidate and a counter",
                "Return the middle element without sorting",
                "Return the most frequent value in the first half",
                "Return the maximum value",
            ),
            correctIndex = 0,
            patternTag = "Arrays",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: count = 0; for each x, if count == 0 then candidate = x; count += (x == candidate) ? 1 : −1. The majority survives because it outnumbers everything else combined. Sorting and taking the middle also works, at O(n log n).",
            linkedTopicId = "array",
            linkedTopicLabel = "Array",
        ),
        QuizQuestion(
            prompt = "nums1 has m values followed by n empty slots; nums2 has n values. Both are sorted. Merge nums2 into nums1 in place.",
            options = listOf(
                "Fill from the back: write the larger of the two remaining tails at index m + n − 1",
                "Fill from the front, shifting nums1 right on each insert",
                "Append nums2, then bubble sort",
                "Copy both arrays into a hash set",
            ),
            correctIndex = 0,
            patternTag = "Two Pointer",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: i = m − 1, j = n − 1, k = m + n − 1. While j ≥ 0: if i ≥ 0 and nums1[i] > nums2[j], nums1[k--] = nums1[i--], else nums1[k--] = nums2[j--]. The back of nums1 is empty, so nothing is overwritten before it is read. O(m + n).",
            linkedTopicId = "two_pointer",
            linkedTopicLabel = "Two Pointer Technique",
        ),
        QuizQuestion(
            prompt = "Given a partly filled 9 × 9 Sudoku board, return whether it is valid so far (no repeat in any row, column or 3 × 3 box).",
            options = listOf(
                "One pass with a set per row, column and box — box index = (r / 3) · 3 + c / 3",
                "Solve the whole puzzle with backtracking first",
                "Check that every row adds up to 45",
                "Check only the two diagonals",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: for each filled cell, try adding its digit to rows[r], cols[c] and boxes[(r / 3) · 3 + c / 3]; any failed add means invalid. 81 cells, constant work. Sums fail because duplicates can add to 45, and empty cells make the sum meaningless.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Given nums (negatives allowed), return the largest product of any contiguous subarray.",
            options = listOf(
                "Track both the max and min product ending here — a negative swaps them",
                "Kadane's algorithm on sums",
                "Multiply all the positive numbers",
                "Sort and multiply the three largest",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: for each x, if x < 0 swap hi and lo; then hi = max(x, hi · x), lo = min(x, lo · x), best = max(best, hi). The smallest (most negative) product can become the largest after one more negative. [2, 3, −2, 4] → 6.",
            linkedTopicId = "kadanes_algorithm",
            linkedTopicLabel = "Kadane's Algorithm",
        ),
        QuizQuestion(
            prompt = "nums holds n distinct values from 0..n, so exactly one is missing. Return it in O(n) time and O(1) space.",
            options = listOf(
                "Expected sum n(n + 1) / 2 minus the actual sum (or XOR every index with every value)",
                "Sort, then binary search for 0",
                "Always return n + 1",
                "Return the smallest value",
            ),
            correctIndex = 0,
            patternTag = "Math",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: 0 + 1 + … + n = n(n + 1) / 2; subtract what is there and the gap is the answer. The XOR version (i ^ nums[i] across all i, then ^ n) cancels every pair and cannot overflow.",
            linkedTopicId = "xor_tricks",
            linkedTopicLabel = "XOR Tricks",
        ),
        QuizQuestion(
            prompt = "Given ransomNote and magazine, return whether the note can be built using each magazine letter at most once.",
            options = listOf(
                "Count the magazine's letters, then decrement per note letter — fail if any count goes negative",
                "Check that the note is a substring of the magazine",
                "Check that both strings have the same length",
                "Check that every note letter appears somewhere in the magazine",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: counts = IntArray(26); for c in magazine counts[c]++; for c in note if (--counts[c] < 0) return false. O(n + m). \"Appears somewhere\" ignores counts: note \"aa\" with magazine \"ab\" would wrongly pass.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Given an m × n matrix, return all its elements in spiral order.",
            options = listOf(
                "Walk four boundaries (top, right, bottom, left), shrinking each one after its pass",
                "Read row by row, reversing every other row",
                "Read it diagonal by diagonal",
                "Transpose it, then flatten",
            ),
            correctIndex = 0,
            patternTag = "Matrix",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: top = 0, bottom = m − 1, left = 0, right = n − 1. Read the top row then top++, right column then right--, bottom row (if top ≤ bottom) then bottom--, left column (if left ≤ right) then left++. The two checks stop a single leftover row or column being read twice.",
            linkedTopicId = "matrix_transform_pattern",
            linkedTopicLabel = "Matrix Manipulation",
        ),
        QuizQuestion(
            prompt = "Rotate an n × n image 90° clockwise, in place.",
            options = listOf(
                "Transpose it, then reverse each row",
                "Reverse each row, then transpose",
                "Swap each pair of opposite corners only",
                "Copy it into a new matrix — that counts as in place",
            ),
            correctIndex = 0,
            patternTag = "Matrix",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: swap m[i][j] with m[j][i] for j > i (transpose), then reverse every row. Doing it the other way round — reverse rows, then transpose — rotates counter-clockwise. O(n²) time, O(1) space.",
            linkedTopicId = "matrix_transform_pattern",
            linkedTopicLabel = "Matrix Manipulation",
        ),
    ),
)

internal val beginnerCodingListsSet = Quiz(
    id = "beginner_coding_lists_set",
    title = "Coding Round: Linked Lists & Stacks",
    description = "Pointer rewiring and stack problems — palindromes, intersections, decoding.",
    questions = listOf(
        QuizQuestion(
            prompt = "Given the head of a singly linked list, return whether it is a palindrome, using O(1) extra space.",
            options = listOf(
                "Find the middle with fast/slow pointers, reverse the second half, compare the halves",
                "Copy the values into an array and use two pointers",
                "Compare head and tail, walking to the tail each time",
                "Reverse the whole list and compare it with itself",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: slow and fast find the middle; reverse from slow onward; walk one pointer from the head and one from the reversed half, comparing values. Restore the list afterwards if the caller needs it. The array version is correct but uses O(n) space.",
            linkedTopicId = "fast_slow_pointers",
            linkedTopicLabel = "Fast & Slow Pointers",
        ),
        QuizQuestion(
            prompt = "Given the heads of two singly linked lists that may merge, return the node where they intersect (or null).",
            options = listOf(
                "Two pointers; when one reaches the end, restart it at the other list's head — they meet at the intersection",
                "Compare the node values position by position",
                "Reverse both lists and compare their heads",
                "Return the middle node of the longer list",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: a = headA, b = headB; while a !== b, a = if (a == null) headB else a.next, and the same for b with headA. Each walks lenA + lenB, so they line up at the shared node, or both hit null. Compare nodes by reference — equal values do not mean a shared node.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Two numbers are stored as linked lists of digits in reverse order: 2→4→3 is 342. Return their sum as a list.",
            options = listOf(
                "Walk both lists digit by digit, carrying into the next node",
                "Convert both lists to integers, add, convert back",
                "Reverse both lists first, then add",
                "Add only the first digits",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: dummy head, carry = 0; while either list or carry remains: s = a + b + carry, append s % 10, carry = s / 10. 2→4→3 + 5→6→4 = 7→0→8 (342 + 465 = 807). Converting to integers overflows once the lists are longer than about 19 digits.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Given a sorted linked list, delete the duplicates so each value appears once.",
            options = listOf(
                "If curr.next has the same value, unlink it (curr.next = curr.next.next); otherwise advance",
                "Put every value in a hash set and rebuild the list",
                "Sort the list first",
                "Delete the head until the values differ",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: sorted means duplicates are neighbours, so one pointer is enough. Only advance curr when the next value differs — advancing after an unlink would skip a third copy. O(n), O(1) space.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Simplify the Unix path \"/a/./b/../../c/\" to its canonical form.",
            options = listOf(
                "Split on '/', push names, pop on '..', skip '.' and empty parts — result \"/c\"",
                "Remove every '.' character — result \"/a/b/c\"",
                "Keep only the last name — result \"/c/\"",
                "Reverse the parts and join them",
            ),
            correctIndex = 0,
            patternTag = "Stack",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: parts a, ., b, .., .., c → push a, skip ., push b, pop b, pop a, push c. Join with '/' and prefix '/': \"/c\". A '..' on an empty stack stays at the root.",
            linkedTopicId = "stack",
            linkedTopicLabel = "Stack",
        ),
        QuizQuestion(
            prompt = "Decode \"3[a2[c]]\", where k[s] means s repeated k times.",
            options = listOf(
                "Two stacks (counts and partial strings); on ']' pop and repeat — \"accaccacc\"",
                "Repeat each letter by the digit before it — \"aaacc\"",
                "Delete the digits and brackets — \"ac\"",
                "Expand only the outermost bracket — \"a2[c]a2[c]a2[c]\"",
            ),
            correctIndex = 0,
            patternTag = "Stack",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: digits build k; '[' pushes (k, current) and resets them; letters append to current; ']' pops (k, prev) and sets current = prev + current × k. Inner c → \"cc\", then \"acc\" × 3 = \"accaccacc\".",
            linkedTopicId = "expression_stack_pattern",
            linkedTopicLabel = "Parsing with a Stack",
        ),
        QuizQuestion(
            prompt = "Reorder a list L0→L1→…→Ln into L0→Ln→L1→Ln−1→…, in place.",
            options = listOf(
                "Find the middle, reverse the second half, then weave the two halves together",
                "Sort the list",
                "Repeatedly walk to the tail and move it forward",
                "Swap every adjacent pair",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: three O(n) passes — fast/slow to split, iterative reverse of the second half, then alternate one node from each half. Walking to the tail every time is O(n²).",
            linkedTopicId = "in_place_reversal_pattern",
            linkedTopicLabel = "In-place Linked List Reversal",
        ),
        QuizQuestion(
            prompt = "Swap every two adjacent nodes: 1→2→3→4 becomes 2→1→4→3. Rewire pointers, do not swap values.",
            options = listOf(
                "Dummy head, then rewire three pointers per pair and move prev on by two",
                "Reverse the whole list",
                "Sort the pairs in descending order",
                "Move every even-position node to the front",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: prev = dummy. While a pair exists: first = prev.next, second = first.next; first.next = second.next; second.next = first; prev.next = second; prev = first. The dummy removes the special case for the new head.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Rotate a linked list right by k places (k may be larger than the length).",
            options = listOf(
                "Get the length, link the tail to the head, then break the ring at length − k % length",
                "Move the tail to the front k times",
                "Reverse the list k times",
                "Sort the list, then shift it",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: one pass for length L and the tail; tail.next = head; walk L − k % L − 1 steps to the new tail, set newHead = newTail.next and newTail.next = null. Moving the tail k times is O(n·k), and k can be huge.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Deep-copy a linked list where every node also has a random pointer to any node or null.",
            options = listOf(
                "Map each old node to its copy (or interleave copies), then set next and random",
                "Copy the next pointers only and leave random null",
                "Copy the values into an array",
                "Reuse the original nodes in the new list",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: pass 1 creates copy[node] for every node; pass 2 sets copy[n].next = copy[n.next] and copy[n].random = copy[n.random]. The map solves the problem of a random pointer to a node not copied yet. Interleaving A→A'→B→B' does it in O(1) extra space.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
    ),
)

internal val beginnerCodingTreesSet = Quiz(
    id = "beginner_coding_trees_set",
    title = "Coding Round: Trees",
    description = "Depth, symmetry, paths and BST building — the tree problems every screen opens with.",
    questions = listOf(
        QuizQuestion(
            prompt = "Given the root of a binary tree, return its maximum depth.",
            options = listOf(
                "Recursion: 1 + max(depth(left), depth(right)), with an empty tree = 0",
                "Count all the nodes",
                "Follow the left children only",
                "Take log₂ of the node count",
            ),
            correctIndex = 0,
            patternTag = "Tree DFS",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: fun depth(n) = if (n == null) 0 else 1 + max(depth(n.left), depth(n.right)). O(n) time, O(h) stack. log₂ of the node count is only right for a perfectly balanced tree.",
            linkedTopicId = "tree",
            linkedTopicLabel = "Tree",
        ),
        QuizQuestion(
            prompt = "Invert a binary tree (mirror it left to right).",
            options = listOf(
                "Swap left and right at every node, recursing into both",
                "Reverse the in-order list of values",
                "Swap only the root's two children",
                "Sort the values in descending order",
            ),
            correctIndex = 0,
            patternTag = "Tree DFS",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: if (n == null) return; swap(n.left, n.right); invert(n.left); invert(n.right). Every node needs its own swap — swapping only at the root leaves each subtree un-mirrored inside.",
            linkedTopicId = "tree",
            linkedTopicLabel = "Tree",
        ),
        QuizQuestion(
            prompt = "Given two binary trees, return whether they are identical in shape and values.",
            options = listOf(
                "Recursively compare the values, then left with left and right with right",
                "Compare their in-order traversals only",
                "Compare their node counts",
                "Compare their root values",
            ),
            correctIndex = 0,
            patternTag = "Tree DFS",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: same(a, b) = both null → true; one null → false; else a.val == b.val && same(a.left, b.left) && same(a.right, b.right). In-order alone cannot tell a left-leaning chain from a right-leaning one with the same values.",
            linkedTopicId = "tree",
            linkedTopicLabel = "Tree",
        ),
        QuizQuestion(
            prompt = "Return the right-side view of a binary tree — the last node you would see on each level.",
            options = listOf(
                "BFS level by level, recording the last node of each level",
                "Follow right children only from the root",
                "Take every second value of the in-order traversal",
                "Return the leaves from left to right",
            ),
            correctIndex = 0,
            patternTag = "Tree BFS",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: queue the root; for each level, pop its size nodes and record the last one. Following right children fails when the left subtree is deeper — its lower nodes are visible from the right too.",
            linkedTopicId = "tree_bfs_pattern",
            linkedTopicLabel = "Tree BFS (Level Order)",
        ),
        QuizQuestion(
            prompt = "Given a binary tree and a target, return whether some root-to-leaf path adds up to the target.",
            options = listOf(
                "DFS subtracting each value, succeeding at a leaf with remainder 0",
                "Check whether any single node equals the target",
                "Add up every node and compare",
                "BFS adding up each level",
            ),
            correctIndex = 0,
            patternTag = "Tree DFS",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: has(n, t) = n != null && (if leaf: t == n.val else has(n.left, t − n.val) || has(n.right, t − n.val)). Check at a leaf, not at null, or a node with one child would count its missing side as a path.",
            linkedTopicId = "tree_dfs_pattern",
            linkedTopicLabel = "Tree DFS (Path Sum)",
        ),
        QuizQuestion(
            prompt = "Return whether a binary tree is symmetric around its centre.",
            options = listOf(
                "Mirror check: compare left.left with right.right and left.right with right.left",
                "Check that the in-order traversal is a palindrome",
                "Check that both subtrees have the same size",
                "Check that the left and right subtrees are identical",
            ),
            correctIndex = 0,
            patternTag = "Tree DFS",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: mirror(a, b) = both null → true; one null → false; else a.val == b.val && mirror(a.left, b.right) && mirror(a.right, b.left). Identical subtrees are the wrong test — symmetric means mirrored.",
            linkedTopicId = "tree",
            linkedTopicLabel = "Tree",
        ),
        QuizQuestion(
            prompt = "Given a BST and two nodes p and q, return their lowest common ancestor.",
            options = listOf(
                "From the root, go left if both are smaller, right if both are larger, otherwise stop here",
                "Average the two nodes' depths",
                "Always return the root",
                "Return whichever of p and q is smaller",
            ),
            correctIndex = 0,
            patternTag = "BST",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: the first node whose value lies between p and q (inclusive) splits them, so it is the LCA. O(h) time, O(1) space iteratively. BST order is what lets you skip the general-tree search.",
            linkedTopicId = "binary_search_tree",
            linkedTopicLabel = "Binary Search Tree",
        ),
        QuizQuestion(
            prompt = "Return whether a binary tree is height-balanced (subtree heights differ by at most 1 everywhere), in O(n).",
            options = listOf(
                "Post-order returning the height, or −1 as soon as any subtree is unbalanced",
                "Recompute the height from scratch at every node",
                "Compare the root's two subtree heights only",
                "Compare the leftmost and rightmost depths",
            ),
            correctIndex = 0,
            patternTag = "Tree DFS",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: h(n) = null → 0; l = h(left), r = h(right); if l == −1 || r == −1 || |l − r| > 1 return −1; else 1 + max(l, r). One pass. Recomputing heights at every node is O(n²) on a skewed tree; checking only the root misses deeper imbalance.",
            linkedTopicId = "tree",
            linkedTopicLabel = "Tree",
        ),
        QuizQuestion(
            prompt = "Return the diameter of a binary tree — the number of edges on its longest path between any two nodes.",
            options = listOf(
                "At each node try left height + right height; keep the max while returning 1 + max(heights)",
                "Twice the height of the root",
                "The longest path starting at the root",
                "The number of leaves",
            ),
            correctIndex = 0,
            patternTag = "Tree DFS",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: one post-order pass. The longest path bends at some node, and that node may not be the root — a tall left subtree can hold the whole path. Track best = max(best, l + r) and return 1 + max(l, r).",
            linkedTopicId = "tree_dp_pattern",
            linkedTopicLabel = "Tree DP (Subtree Aggregation)",
        ),
        QuizQuestion(
            prompt = "Convert a sorted array into a height-balanced BST.",
            options = listOf(
                "Make the middle element the root; recurse on the left and right halves",
                "Insert the elements into a BST in order",
                "Make the first element the root, and the rest its right chain",
                "Build a min-heap from the array",
            ),
            correctIndex = 0,
            patternTag = "BST",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: build(lo, hi) = if lo > hi null else mid = (lo + hi) / 2, node(nums[mid]) with left = build(lo, mid − 1) and right = build(mid + 1, hi). Inserting sorted values one by one makes a linked list of height n.",
            linkedTopicId = "binary_search_tree",
            linkedTopicLabel = "Binary Search Tree",
        ),
    ),
)

internal val advancedCodingTreesGraphsSet = Quiz(
    id = "advanced_coding_trees_graphs_set",
    title = "Coding Round: Trees & Graphs",
    description = "LCA, serialisation, word ladders, alien alphabets and spanning trees.",
    questions = listOf(
        QuizQuestion(
            prompt = "Given a binary tree (not a BST) and nodes p and q, return their lowest common ancestor.",
            options = listOf(
                "Recurse: return the node if it is p or q; if both sides return non-null, this node is the LCA",
                "Use BST ordering to decide which way to go",
                "Return the parent of the deeper node",
                "BFS and return the first level containing both",
            ),
            correctIndex = 0,
            patternTag = "Tree DFS",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: lca(n) = if n == null || n == p || n == q return n; l = lca(n.left); r = lca(n.right); return if (l != null && r != null) n else l ?: r. O(n). There is no ordering to exploit, so both sides must be searched.",
            linkedTopicId = "lca",
            linkedTopicLabel = "Lowest Common Ancestor",
        ),
        QuizQuestion(
            prompt = "Design serialize and deserialize for a binary tree, so that the string rebuilds the exact tree.",
            options = listOf(
                "Pre-order with a marker for every null child",
                "In-order values only",
                "Level-order values with the nulls left out",
                "The node count followed by the sorted values",
            ),
            correctIndex = 0,
            patternTag = "Tree Design",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: serialize: visit node, write val or \"#\", recurse left then right. Deserialize: read tokens in the same order; \"#\" returns null, otherwise build a node and recurse left, then right. Null markers are what pin the shape — without them many trees share one string.",
            linkedTopicId = "tree",
            linkedTopicLabel = "Tree",
        ),
        QuizQuestion(
            prompt = "Rebuild a binary tree from its pre-order and in-order traversals (values are unique).",
            options = listOf(
                "Pre-order's next value is the root; its index in in-order splits the left and right subtrees",
                "Insert the pre-order values into a BST",
                "In-order's first value is the root",
                "It cannot be done without the post-order too",
            ),
            correctIndex = 0,
            patternTag = "Tree DFS",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: keep a value → index map for in-order and a moving pointer into pre-order. build(lo, hi): root = pre[p++]; m = idx[root]; left = build(lo, m − 1); right = build(m + 1, hi). Build left first, because pre-order lists it first. O(n).",
            linkedTopicId = "tree",
            linkedTopicLabel = "Tree",
        ),
        QuizQuestion(
            prompt = "Return the maximum path sum in a binary tree, where a path can start and end at any nodes.",
            options = listOf(
                "Post-order: each node returns val + max(0, best child gain); update the answer with val + both gains",
                "Add up every positive node",
                "The largest root-to-leaf sum",
                "The largest single value times the height",
            ),
            correctIndex = 0,
            patternTag = "Tree DP",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: gain(n) = null → 0; l = max(0, gain(left)), r = max(0, gain(right)); best = max(best, n.val + l + r); return n.val + max(l, r). Returning only one side keeps the path unbranched for the parent; max(0, …) drops negative branches. Start best at the minimum value, since all values may be negative.",
            linkedTopicId = "tree_dp_pattern",
            linkedTopicLabel = "Tree DP (Subtree Aggregation)",
        ),
        QuizQuestion(
            prompt = "A height grid borders the Pacific (top/left) and the Atlantic (bottom/right). Water flows to equal or lower neighbours. Return the cells that can reach both oceans.",
            options = listOf(
                "BFS/DFS inward from each ocean's border going uphill; return the cells both searches reach",
                "DFS downhill from every cell separately",
                "Return the cells taller than all their neighbours",
                "Return the border cells",
            ),
            correctIndex = 0,
            patternTag = "Graph BFS",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: reverse the flow — from the Pacific border, move to neighbours with height ≥ the current one, marking pac[][]; do the same for atl[][]. The answer is where both are true. Two searches, O(m·n), instead of one search per cell, O((m·n)²).",
            linkedTopicId = "multi_source_bfs_pattern",
            linkedTopicLabel = "Multi-source BFS",
        ),
        QuizQuestion(
            prompt = "Word ladder: turn \"hit\" into \"cog\" one letter at a time, where every step must be a dictionary word. Return the fewest steps.",
            options = listOf(
                "BFS over words, making neighbours by changing one letter at a time",
                "DFS, returning the first path found",
                "Dijkstra with letter-distance weights",
                "Sort the dictionary and walk it alphabetically",
            ),
            correctIndex = 0,
            patternTag = "Graph BFS",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: queue \"hit\" at step 1. For each word, try all 26 letters in every position; any unvisited dictionary word goes into the queue at step + 1. The first time \"cog\" appears is the answer: hit→hot→dot→dog→cog = 5 words. Every step costs the same, so BFS finds the shortest; DFS finds some path.",
            linkedTopicId = "bfs",
            linkedTopicLabel = "Breadth-First Search (BFS)",
        ),
        QuizQuestion(
            prompt = "Given words sorted in an unknown alien alphabet, return an order of its letters.",
            options = listOf(
                "Compare adjacent words; the first differing letters give an edge — then topological sort",
                "Sort the letters by frequency",
                "Use the first word's letters in order",
                "Union-find the letters that appear together",
            ),
            correctIndex = 0,
            patternTag = "Topological Sort",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: for each adjacent pair, the first position where they differ gives an edge a → b; then run Kahn's algorithm over every letter. A cycle means no valid order. So does a longer word listed before its own prefix (\"abc\" before \"ab\") — check that explicitly.",
            linkedTopicId = "topological_sort",
            linkedTopicLabel = "Topological Sort",
        ),
        QuizQuestion(
            prompt = "Given n nodes and a list of undirected edges, return whether they form a valid tree.",
            options = listOf(
                "Exactly n − 1 edges and no cycle (union-find never joins two already-connected nodes)",
                "No node has degree greater than 2",
                "The number of edges equals n",
                "Every node has at least one edge",
            ),
            correctIndex = 0,
            patternTag = "Union-Find",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: if edges.size != n − 1 return false; then union each edge, failing if find(a) == find(b). n − 1 edges with no cycle forces the graph to be connected. The degree test describes a path, not a tree.",
            linkedTopicId = "disjoint_set",
            linkedTopicLabel = "Disjoint Set (Union-Find)",
        ),
        QuizQuestion(
            prompt = "Given n points, return the minimum total Manhattan distance needed to connect all of them.",
            options = listOf(
                "Prim's algorithm (an O(n²) array version suits the complete graph)",
                "Connect the points in order of x",
                "Dijkstra from point 0",
                "Add up each point's distance to its nearest neighbour",
            ),
            correctIndex = 0,
            patternTag = "MST",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: every pair is an edge, so E = n². Array Prim keeps dist[] to the growing tree: pick the closest unused point, add its distance, then relax every other point. O(n²) with no heap and no edge list. Nearest-neighbour sums can leave the points in separate clusters.",
            linkedTopicId = "prims_mst",
            linkedTopicLabel = "Prim's MST",
        ),
        QuizQuestion(
            prompt = "Network delay: a signal leaves node k along weighted directed edges. Return the time until every node has received it, or −1.",
            options = listOf(
                "Dijkstra from k; the answer is the largest distance, or −1 if any node is unreachable",
                "BFS counting edges",
                "The sum of all the edge weights",
                "The smallest distance to any node",
            ),
            correctIndex = 0,
            patternTag = "Shortest Path",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: every node receives the signal at its shortest-path time, so the network is done when the farthest node gets it: max(dist). Weights differ, so edge counts from BFS are the wrong measure.",
            linkedTopicId = "dijkstras_algorithm",
            linkedTopicLabel = "Dijkstra's Algorithm",
        ),
    ),
)

internal val advancedCodingDpSet = Quiz(
    id = "advanced_coding_dp_set",
    title = "Coding Round: DP & Backtracking",
    description = "Grid paths, partitions, combinations, regex matching and palindrome cuts.",
    questions = listOf(
        QuizQuestion(
            prompt = "A robot moves only right or down on an m × n grid. How many paths go from the top-left to the bottom-right of a 3 × 7 grid?",
            options = listOf(
                "28 — paths[r][c] = paths[r − 1][c] + paths[r][c − 1]",
                "21 — m × n",
                "10 — m + n",
                "1,024 — 2^(m + n)",
            ),
            correctIndex = 0,
            patternTag = "Grid DP",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: the first row and column have one path each; every other cell adds the cell above and the cell to its left. Equivalently C(m + n − 2, m − 1) = C(8, 2) = 28. One row of DP is enough: O(n) space.",
            linkedTopicId = "grid_dp_pattern",
            linkedTopicLabel = "Grid & Sequence DP",
        ),
        QuizQuestion(
            prompt = "nums[i] is the maximum jump from index i. Return whether you can reach the last index.",
            options = listOf(
                "Greedy: track the farthest reachable index; fail if i ever passes it",
                "BFS over every possible jump is required",
                "Always take the largest jump available",
                "Succeed exactly when no value is zero",
            ),
            correctIndex = 0,
            patternTag = "Greedy",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: far = 0; for i in indices: if i > far return false; far = max(far, i + nums[i]). O(n), O(1). Taking the largest jump can land on a 0 that a shorter jump would have skipped. Zeros are fine as long as you can jump over them.",
            linkedTopicId = "greedy_exchange_pattern",
            linkedTopicLabel = "Greedy & the Exchange Argument",
        ),
        QuizQuestion(
            prompt = "Given positive integers, return whether they can be split into two subsets with equal sums.",
            options = listOf(
                "Subset-sum DP towards total / 2 (an odd total is an immediate no)",
                "Sort and split at the middle index",
                "Greedily add each number to the smaller side",
                "Yes whenever the total is even",
            ),
            correctIndex = 0,
            patternTag = "Knapsack DP",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: target = total / 2; can = BooleanArray(target + 1), can[0] = true; for each x, for s from target down to x: can[s] = can[s] || can[s − x]. Answer can[target]. Greedy fails on [3, 3, 2, 2, 2]: the sides go 3 | 3, 5 | 3, 5 | 5, 7 | 5 — no split — yet 3 + 3 = 2 + 2 + 2.",
            linkedTopicId = "partition_problem",
            linkedTopicLabel = "Partition Problem",
        ),
        QuizQuestion(
            prompt = "Return the length of the longest palindromic subsequence (not substring) of \"bbbab\".",
            options = listOf(
                "4 — dp[i][j] = dp[i + 1][j − 1] + 2 when s[i] = s[j], else max(dp[i + 1][j], dp[i][j − 1])",
                "3 — expanding around each centre",
                "5 — the length of the string",
                "2 — the number of distinct letters",
            ),
            correctIndex = 0,
            patternTag = "Interval DP",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: \"bbbb\" (skipping the 'a') has length 4. A subsequence may skip characters, so expanding around centres — which finds the substring \"bbb\" — answers a different question. Fill the table by increasing length: O(n²).",
            linkedTopicId = "interval_dp_pattern",
            linkedTopicLabel = "Interval DP",
        ),
        QuizQuestion(
            prompt = "candidates = [2, 3, 6, 7], target = 7, each candidate reusable. Return every combination that sums to the target, with no duplicates.",
            options = listOf(
                "Backtrack from a start index that never moves backwards — [[2, 2, 3], [7]]",
                "List every ordering too — [[2, 2, 3], [2, 3, 2], [3, 2, 2], [7]]",
                "Greedily take the largest first — [[7]]",
                "Pairs only — []",
            ),
            correctIndex = 0,
            patternTag = "Backtracking",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: dfs(start, remaining, path): remaining == 0 → record; for i from start: if c[i] ≤ remaining, add it, dfs(i, remaining − c[i]) — i, not i + 1, allows reuse — then remove it. Never going back to an earlier index is what stops [2, 3, 2] appearing as a second copy of [2, 2, 3].",
            linkedTopicId = "backtracking_pattern",
            linkedTopicLabel = "Backtracking Pattern",
        ),
        QuizQuestion(
            prompt = "Return every well-formed string of n = 3 pairs of parentheses.",
            options = listOf(
                "Backtrack: add '(' while open < n, and ')' while close < open — 5 strings",
                "Generate all 2^(2n) strings with no filtering — 64 strings",
                "Place the pairs side by side — \"()()()\" only",
                "Nest all the pairs — \"((()))\" only",
            ),
            correctIndex = 0,
            patternTag = "Backtracking",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: the two rules only allow valid prefixes, so every leaf is a valid answer: ((())), (()()), (())(), ()(()), ()()(). The count is the Catalan number C₃ = 5. Generating all 64 and filtering works but wastes most of the work.",
            linkedTopicId = "backtracking_pattern",
            linkedTopicLabel = "Backtracking Pattern",
        ),
        QuizQuestion(
            prompt = "Given a grid of letters and a word, return whether the word can be traced through adjacent cells, using each cell at most once.",
            options = listOf(
                "DFS from every cell matching the first letter, marking the path and un-marking on return",
                "BFS that allows revisiting cells",
                "Check that the grid has enough of each letter",
                "Search each row as a plain string",
            ),
            correctIndex = 0,
            patternTag = "Backtracking",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: dfs(r, c, k): out of bounds or grid[r][c] != word[k] → false; k == last → true; mark grid[r][c] = '#', try the 4 neighbours with k + 1, then restore the letter. Un-marking is what lets another path use the cell later. Letter counts are necessary, not sufficient.",
            linkedTopicId = "backtracking_pattern",
            linkedTopicLabel = "Backtracking Pattern",
        ),
        QuizQuestion(
            prompt = "Regular expression matching with '.' (any one character) and '*' (zero or more of the preceding one). Does \"aab\" match \"c*a*b\"?",
            options = listOf(
                "Yes — 2-D DP where 'x*' either matches nothing (dp[i][j − 2]) or eats one matching character (dp[i − 1][j])",
                "No — greedy matching lets 'c*' fail on 'a'",
                "No — the pattern and the string have different lengths",
                "Yes — delete every '*' and compare",
            ),
            correctIndex = 0,
            patternTag = "String DP",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: dp[i][j] = does s[0..i) match p[0..j). 'c*' matches zero c's, 'a*' matches \"aa\", 'b' matches 'b' → true. Deleting the stars gives \"cab\", which does not equal \"aab\"; greedy matching goes wrong on inputs like \"aaa\" against \"a*a\".",
            linkedTopicId = "memo_recursion_pattern",
            linkedTopicLabel = "Top-down Memoization",
        ),
        QuizQuestion(
            prompt = "Given a grid of non-negative costs, return the cheapest path from the top-left to the bottom-right moving only right or down.",
            options = listOf(
                "cost[r][c] = grid[r][c] + min(cost from above, cost from the left)",
                "Greedy: always step to the cheaper neighbour",
                "Dijkstra is required",
                "Add up the main diagonal",
            ),
            correctIndex = 0,
            patternTag = "Grid DP",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: with only right and down moves the grid is a DAG, so one row-by-row pass settles every cell — O(m·n). Greedy can walk into an expensive corner. Dijkstra works too, but it is only needed when moves can go in every direction.",
            linkedTopicId = "grid_dp_pattern",
            linkedTopicLabel = "Grid & Sequence DP",
        ),
        QuizQuestion(
            prompt = "Return the fewest cuts needed to split \"abaab\" into palindromes.",
            options = listOf(
                "1 — cuts[i] = min over palindromic s[j..i] of cuts[j − 1] + 1, with a precomputed isPalindrome table",
                "2 — greedily take the longest palindromic prefix each time",
                "3 — the number of distinct letters",
                "4 — n − 1 cuts",
            ),
            correctIndex = 0,
            patternTag = "Interval DP",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: \"a | baab\" needs one cut. Greedy grabs the prefix \"aba\" first, leaving \"ab\", which needs two more pieces — 2 cuts. Precomputing isPalindrome[j][i] in O(n²) keeps the whole DP at O(n²).",
            linkedTopicId = "palindrome_expansion_pattern",
            linkedTopicLabel = "Expand Around Centre",
        ),
    ),
)

internal val advancedCodingHardSet = Quiz(
    id = "advanced_coding_hard_set",
    title = "Coding Round: Hard Classics",
    description = "Rain water, histograms, two-array medians and the rest of the hard list.",
    questions = listOf(
        QuizQuestion(
            prompt = "Given bar heights [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1], return how much rain water they trap.",
            options = listOf(
                "6 — two pointers: move the lower side inward, adding its side's running max minus its height",
                "22 — every bar filled up to the tallest bar",
                "4 — the number of zero-height bars",
                "3 — the height of the tallest bar",
            ),
            correctIndex = 0,
            patternTag = "Two Pointer",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: water at i = min(maxLeft, maxRight) − height[i]. With l and r pointers, the side with the smaller max is limited by its own max, so add that and move it inward. O(n), O(1). Filling everything to the global maximum ignores the lower wall on each side.",
            linkedTopicId = "two_pointer_pattern",
            linkedTopicLabel = "Two Pointer Pattern",
        ),
        QuizQuestion(
            prompt = "Return the area of the largest rectangle in the histogram [2, 1, 5, 6, 2, 3].",
            options = listOf(
                "10 — a monotonic increasing stack; each popped bar extends between its smaller neighbours",
                "36 — the tallest bar times the number of bars",
                "6 — the shortest bar times the number of bars",
                "11 — the two tallest bars added together",
            ),
            correctIndex = 0,
            patternTag = "Monotonic Stack",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: push indices while heights rise. When a lower bar arrives, pop: the popped bar's rectangle spans from the new stack top + 1 to i − 1. The bars 5 and 6 give 5 × 2 = 10. Add a height-0 sentinel at the end to flush the stack. O(n).",
            linkedTopicId = "monotonic_stack_pattern",
            linkedTopicLabel = "Monotonic Stack",
        ),
        QuizQuestion(
            prompt = "Return the median of two sorted arrays of sizes m and n in O(log(min(m, n))).",
            options = listOf(
                "Binary search a cut in the smaller array so the two left sides together hold half of all elements",
                "Merge the arrays and take the middle",
                "Average the two arrays' own medians",
                "Binary search the larger array's values only",
            ),
            correctIndex = 0,
            patternTag = "Modified Binary Search",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: cut A at i and B at j = (m + n + 1) / 2 − i. The cut is right when A[i − 1] ≤ B[j] and B[j − 1] ≤ A[i]; otherwise move i. The median then comes from the max of the left sides and the min of the right sides. Merging is correct but O(m + n); averaging medians is simply wrong.",
            linkedTopicId = "modified_binary_search_pattern",
            linkedTopicLabel = "Modified Binary Search",
        ),
        QuizQuestion(
            prompt = "Return the length of the longest valid (well-formed) parentheses substring in \"()(()\".",
            options = listOf(
                "2 — a stack of indices seeded with −1; on ')' pop, then length = i − the new top",
                "4 — twice the number of matched pairs",
                "5 — the length of the string",
                "3 — the longest run of '('",
            ),
            correctIndex = 0,
            patternTag = "Stack",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: '(' pushes its index. ')' pops; if the stack is now empty, push i as the new base, else best = max(best, i − top). For \"()(()\" the unmatched '(' at index 2 splits the valid parts into \"()\" and \"()\", so the answer is 2. Counting pairs gives 4 because it ignores that split.",
            linkedTopicId = "expression_stack_pattern",
            linkedTopicLabel = "Parsing with a Stack",
        ),
        QuizQuestion(
            prompt = "nums has n + 1 values in 1..n, with one value repeated (possibly many times). Find it without modifying nums, in O(1) space.",
            options = listOf(
                "Floyd's cycle detection over the links i → nums[i]",
                "Sort the array and scan for neighbours",
                "Put every value in a hash set",
                "Actual sum minus n(n + 1) / 2",
            ),
            correctIndex = 0,
            patternTag = "Fast & Slow Pointers",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: treat each value as a next pointer. The repeated value has two incoming links, so it is where a cycle starts. Run slow/fast until they meet, then reset one to index 0 and step both once at a time — they meet at the duplicate. Sorting modifies the input, the set is O(n) space, and the sum trick fails once the value repeats more than twice.",
            linkedTopicId = "fast_slow_pointers",
            linkedTopicLabel = "Fast & Slow Pointers",
        ),
        QuizQuestion(
            prompt = "Return the smallest positive integer missing from an unsorted array, in O(n) time and O(1) space.",
            options = listOf(
                "Cyclic sort: move each value v in 1..n to index v − 1, then return the first index whose value is wrong",
                "Sort, then scan",
                "Put the values in a hash set, then count up from 1",
                "Return the maximum plus one",
            ),
            correctIndex = 0,
            patternTag = "Cyclic Sort",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: while nums[i] in 1..n and nums[nums[i] − 1] != nums[i], swap it into place. Then the first i with nums[i] != i + 1 gives i + 1; if none, n + 1. Each swap places one value for good, so the total is O(n). Sorting is O(n log n) and the set is O(n) space.",
            linkedTopicId = "cyclic_sort_pattern",
            linkedTopicLabel = "Cyclic Sort",
        ),
        QuizQuestion(
            prompt = "For each element, return how many smaller elements appear to its right. n = 10⁵.",
            options = listOf(
                "Merge sort that counts how many right-half elements move ahead of each left-half element — O(n log n)",
                "Nested loops",
                "Sort the array and use each value's sorted index",
                "A monotonic stack",
            ),
            correctIndex = 0,
            patternTag = "Divide & Conquer",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: sort (value, originalIndex) pairs with merge sort. While merging, when a left element is placed, add the number of right elements already placed before it to count[originalIndex]. A Fenwick tree over value ranks, scanned right to left, also works. Nested loops are 10¹⁰ operations.",
            linkedTopicId = "divide_conquer_pattern",
            linkedTopicLabel = "Divide & Conquer",
        ),
        QuizQuestion(
            prompt = "Given a binary matrix, return the area of the largest square containing only 1s.",
            options = listOf(
                "side[r][c] = 1 + min(above, left, above-left) when the cell is 1; the answer is the max side²",
                "Count all the 1s and take the square root",
                "The longest row of 1s, squared",
                "BFS from every 1",
            ),
            correctIndex = 0,
            patternTag = "Grid DP",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: a square ending at (r, c) can only be as large as the smallest of the three squares it builds on, plus one. One pass, O(m·n), and a single row of memory is enough. Counting 1s ignores whether they are next to each other.",
            linkedTopicId = "grid_dp_pattern",
            linkedTopicLabel = "Grid & Sequence DP",
        ),
        QuizQuestion(
            prompt = "Return the length of the longest strictly increasing path in a matrix, moving up, down, left or right.",
            options = listOf(
                "DFS with a memo per cell — increasing moves form a DAG, so each cell is solved once: O(m·n)",
                "BFS from every cell with no memo",
                "Sort the cells and take the longest sorted row",
                "Dijkstra with negated values",
            ),
            correctIndex = 0,
            patternTag = "DAG DP",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: len(r, c) = 1 + max(len(neighbour)) over neighbours with a larger value, cached. Strictly increasing moves can never loop, so memoised DFS is safe — no visited set needed. Without the memo the same paths are re-explored exponentially.",
            linkedTopicId = "dag_dp_pattern",
            linkedTopicLabel = "DAG DP (Longest Path)",
        ),
        QuizQuestion(
            prompt = "Given intervals, return the fewest you must remove so the rest do not overlap.",
            options = listOf(
                "Sort by end; keep an interval if it starts at or after the last kept end — answer = n − kept",
                "Sort by length and drop the longest first",
                "Remove every interval that overlaps anything",
                "Sort by start and keep the first interval of each overlap",
            ),
            correctIndex = 0,
            patternTag = "Greedy Intervals",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: the earliest-ending interval leaves the most room for the rest (exchange argument), so keeping greedily by end time maximises how many stay. Dropping the longest first fails when one short interval overlaps two others that do not overlap each other.",
            linkedTopicId = "greedy_intervals_pattern",
            linkedTopicLabel = "Greedy Intervals",
        ),
    ),
)
