package com.algora.app.feature.topics.content

import com.algora.app.core.data.model.ApplicationCard
import com.algora.app.core.data.model.CodeBlock
import com.algora.app.core.data.model.CrossLink
import com.algora.app.core.data.model.FormulaEntry
import com.algora.app.core.data.model.NotationEntry
import com.algora.app.core.data.model.SimulationType
import com.algora.app.core.data.model.StepCard
import com.algora.app.core.data.model.TopicContent

internal val hmmContent = TopicContent(
    topicId = "hmm",
    whatIsIt = listOf(
        "A hidden Markov model describes a sequence you can see (words) generated by a sequence you cannot (part-of-speech tags, phonemes, gene regions). It has two tables: transitions A(t → t′), how likely one hidden state is to follow another, and emissions B(t → w), how likely a state is to produce a given observation. Both are estimated by counting a tagged corpus, so training is division, not gradient descent — the same shape as an n-gram model with a hidden layer of states behind it.",
        "The reason it is not just an n-gram model is the decoding problem. \"book that flight\" has two grammatical readings: VB DT NN (an instruction) and NN IN NN (\"book\" the object, \"that\" a complementiser). Tagging greedily left to right picks the locally best tag at each step — and here it opens with NN, because P(NN)·P(book|NN) = 0.0105 beats VB's 0.0100, then never revisits that choice. Viterbi keeps the best path *into every state* instead of one path overall, so the VB opening is still alive when the second word is scored, and the strong DT → NN transition pulls the whole sequence back to the imperative reading. It is 1.43× more probable than the answer greedy committed to.",
        "The trick is dynamic programming, and it is what makes the model practical: Viterbi fills T·N² trellis cells — 48 for three words over four tags — where enumerating tag sequences costs N^T, which is 64 here and about 1.1 × 10¹² for a 20-word sentence. The companion forward algorithm sums instead of maximising and gives P(the observations) with the states integrated out. HMMs are generative: they model P(words, tags) jointly, which lets them generate but forces independence assumptions that discriminative models (CRFs, and now neural taggers) drop by modelling P(tags | words) directly. That is why a CRF beat an HMM at NER, and why the HMM is still the clearest place to learn what the Viterbi recursion actually does.",
    ),
    steps = listOf(
        StepCard(1, "Define the States", "The hidden alphabet: POS tags, BIO labels, phonemes, or \"exon / intron\".", 0xFF8B5CF6),
        StepCard(2, "Count Two Tables", "A(t→t′) from tag bigrams, B(t→w) from tag-word pairs. That is training.", 0xFF6366F1),
        StepCard(3, "Score With Forward", "α_t(j) = Σᵢ α_{t−1}(i)·A(i→j)·B(j→wₜ) — every path into a cell, summed.", 0xFF3B82F6),
        StepCard(4, "Decode With Viterbi", "Same recursion with max instead of sum, plus a backpointer per cell.", 0xFF06B6D4),
        StepCard(5, "Backtrace", "Follow the pointers from the best final state to read off the tag sequence.", 0xFF14B8A6),
        StepCard(6, "Check Against Greedy", "If the two agree on every sentence, the transitions are carrying no information.", 0xFFEC4899),
    ),
    formulas = listOf(
        FormulaEntry("Joint model", "P(w, t) = Π A(t_{i−1} → tᵢ) · B(tᵢ → wᵢ)", "Generative: the words and the tags are modelled together."),
        FormulaEntry("Forward", "α_t(j) = [Σᵢ α_{t−1}(i)·A(i→j)]·B(j→wₜ)", "P(\"book that flight\") = 5.47 × 10⁻⁶ with the tags summed out."),
        FormulaEntry("Viterbi", "v_t(j) = maxᵢ v_{t−1}(i)·A(i→j)·B(j→wₜ)", "Best path VB DT NN at 2.70 × 10⁻⁶."),
        FormulaEntry("Greedy", "tᵢ = argmax_t A(t_{i−1}→t)·B(t→wᵢ)", "NN IN NN at 1.89 × 10⁻⁶ — 1.43× less probable, and unrecoverable."),
        FormulaEntry("Cost", "O(T·N²) vs O(N^T)", "48 cells vs 64 paths here; 320 cells vs ≈1.1×10¹² paths at 20 words."),
        FormulaEntry("Log space", "log v_t(j) = maxᵢ [log v_{t−1}(i) + log A + log B]", "Mandatory in practice — products of probabilities underflow within a few dozen tokens."),
    ),
    notationKey = listOf(
        NotationEntry("hidden state", "the thing being inferred — a tag, phoneme or region — never observed directly"),
        NotationEntry("Markov assumption", "the next state depends only on the current one, not the whole history"),
        NotationEntry("output independence", "an observation depends only on its own state; the assumption CRFs drop"),
        NotationEntry("trellis", "the T × N table of states over time that both algorithms fill"),
        NotationEntry("Baum-Welch", "EM training when the states are unlabelled — the unsupervised case"),
        NotationEntry("generative vs discriminative", "models P(w, t) vs P(t | w); the second needs no model of the words"),
    ),
    codeBlocks = listOf(
        CodeBlock(
            title = "Viterbi, and the greedy tagger it beats",
            accentColor = 0xFF8B5CF6,
            code = """
                tags  = ["NN", "VB", "DT", "IN"]
                start = {"NN": .35, "VB": .25, "DT": .30, "IN": .10}
                A = {"NN": {"NN": .15, "VB": .30, "DT": .05, "IN": .30, "</s>": .20},
                     "VB": {"NN": .20, "VB": .05, "DT": .50, "IN": .10, "</s>": .15},
                     "DT": {"NN": .90, "VB": .02, "DT": .02, "IN": .02, "</s>": .04},
                     "IN": {"NN": .60, "VB": .05, "DT": .30, "IN": .03, "</s>": .02}}
                B = {"NN": {"book": .030, "flight": .020},
                     "VB": {"book": .040},
                     "DT": {"that": .150},
                     "IN": {"that": .250}}
                b = lambda t, w: B[t].get(w, 0.0)

                def viterbi(words):
                    v = {t: start[t] * b(t, words[0]) for t in tags}
                    back = []
                    for w in words[1:]:
                        step = {}
                        ptr = {}
                        for to in tags:
                            best = max(tags, key=lambda fr: v[fr] * A[fr][to])
                            ptr[to] = best
                            step[to] = v[best] * A[best][to] * b(to, w)
                        v, _ = step, back.append(ptr)
                    final = {t: p * A[t]["</s>"] for t, p in v.items()}
                    tag = max(final, key=final.get)
                    path = [tag]
                    for ptr in reversed(back):
                        tag = ptr[tag]
                        path.insert(0, tag)
                    return path, max(final.values())

                print(viterbi(["book", "that", "flight"]))   # (['VB', 'DT', 'NN'], 2.7e-06)

                # Greedy: commit to the best tag at each step, never revisit.
                # -> ['NN', 'IN', 'NN'] at 1.89e-06. Grammatical, and 1.43x less probable.
            """.trimIndent(),
        ),
        CodeBlock(
            title = "Forward, in log space, the way it ships",
            accentColor = 0xFF3B82F6,
            code = """
                from math import log, exp, inf

                def logsumexp(xs):
                    m = max(xs)
                    return m + log(sum(exp(x - m) for x in xs)) if m > -inf else -inf

                def forward_log(words):
                    a = {t: (log(start[t]) + log(b(t, words[0]))) if b(t, words[0]) else -inf
                         for t in tags}
                    for w in words[1:]:
                        a = {to: logsumexp([a[fr] + log(A[fr][to]) for fr in tags]) + log(b(to, w))
                             if b(to, w) else -inf for to in tags}
                    return logsumexp([a[t] + log(A[t]["</s>"]) for t in tags])

                print(exp(forward_log(["book", "that", "flight"])))   # 5.4735e-06

                # Products of probabilities underflow float64 after ~300 tokens, so every production
                # implementation works in logs -- max survives the transform unchanged, and sum
                # becomes logsumexp.
            """.trimIndent(),
        ),
    ),
    simulation = SimulationType.TokenStripPlayer,
    applications = listOf(
        ApplicationCard("browser", 0xFF8B5CF6, "POS Tagging & Chunking", "The classic application, and the baseline every neural tagger is measured against."),
        ApplicationCard("music", 0xFF6366F1, "Speech Recognition", "Phoneme HMMs were the acoustic model of every ASR system until deep learning arrived."),
        ApplicationCard("flask", 0xFF3B82F6, "Bioinformatics", "Gene finding and profile HMMs for protein families — same algorithm, different alphabet."),
        ApplicationCard("finance", 0xFF14B8A6, "Regime Detection", "Market states inferred from returns; the hidden state is the regime, not the price."),
    ),
    takeaways = listOf(
        "Two counted tables — transitions and emissions — are the whole model; training is division.",
        "Greedy tagging commits early: on \"book that flight\" it returns NN IN NN, 1.43× less probable than Viterbi's VB DT NN.",
        "Viterbi is the same recursion with max instead of sum, plus backpointers; forward gives P(observations).",
        "Dynamic programming makes it O(T·N²): 48 cells here against 64 whole paths, and 320 vs ≈10¹² at 20 words.",
        "It is generative and assumes output independence — CRFs and neural taggers drop that and win on accuracy.",
    ),
    crossLinks = listOf(
        CrossLink("pcfg", "Probabilistic CFGs"),
        CrossLink("ner", "Named Entity Recognition"),
        CrossLink("n_grams", "N-Grams"),
        CrossLink("mdp", "Markov Decision Process"),
    ),
)
