package com.algora.app.feature.topics

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins the properties B7's lab copy leans on — the same guard `DimReductionMathTest` provides for B6.
 *
 * The association half is checkable by hand, so these assertions are exact. The time-series half is
 * not, so they are ordering assertions: which method beats which on the held-out year, and which
 * diagnostic moves in which direction. Those orderings *are* the copy. If a re-tune of the series or
 * an estimator flips one of them, the frames and notes would still be internally consistent — every
 * number in them is computed — but they would be teaching the opposite of what they say, and that is
 * the failure this file exists to catch.
 */
class B7MathTest {

    // ── Association rules ────────────────────────────────────────────────────

    @Test
    fun `the basket database exercises every claim the labs make about it`() {
        // Exactly one item below minimum support, so the level-1 prune has something to do.
        val infrequent = basketItems.filter { support(setOf(it)) < MinSupport }
        assertEquals("expected exactly one infrequent item, got $infrequent", 1, infrequent.size)

        // Support 6, 9, 5, 2, 4 for A..E — checked by hand when the database was chosen.
        assertEquals(6, support(setOf("A")))
        assertEquals(9, support(setOf("B")))
        assertEquals(2, support(setOf("D")))
    }

    @Test
    fun `downward closure kills a candidate without a counting pass`() {
        val passes = aprioriPasses()
        val level3 = passes.first { it.k == 3 }

        // BCE is generated by the join and eliminated because CE is infrequent — the Apriori
        // property doing work, which is the whole point of the level-3 frame.
        val pruned = level3.candidates.filter { it.prunedBySubset != null }
        assertEquals("expected one candidate pruned by subset, got ${pruned.map { it.label }}", 1, pruned.size)
        assertEquals("BCE", pruned.single().label)
        assertEquals("CE", itemsetLabel(pruned.single().prunedBySubset!!))
        assertTrue("the pruned candidate must not have been counted", level3.counted < level3.candidates.size)

        assertEquals(listOf("ABC"), level3.frequent.map { it.label })
    }

    @Test
    fun `all three algorithms find the same frequent itemsets`() {
        val fromApriori = aprioriPasses()
            .flatMap { pass -> pass.frequent.map { it.label } }
            .filter { it.length >= 2 }
            .toSortedSet()
        val fromEclat = eclatSteps()
            .filter { it.frequent && it.itemset.size >= 2 }
            .map { it.label }
            .toSortedSet()

        assertEquals(fromApriori, fromEclat)
        assertTrue("expected some multi-item frequent sets to compare", fromApriori.isNotEmpty())

        // FP-Growth's route to the same answer: E's conditional pattern base must make BE frequent.
        val tree = buildFpTree()
        val base = conditionalPatternBase(tree, "E")
        val bCount = base.filter { "B" in it.path }.sumOf { it.count }
        assertTrue("BE should be frequent from E's conditional base, got B count $bCount", bCount >= MinSupport)
        assertTrue("BE" in fromApriori)
    }

    @Test
    fun `the FP-tree is smaller than the transactions it stores`() {
        val tree = buildFpTree()
        val slots = transactions.sumOf { fpSortedTransaction(it).size }
        assertTrue(
            "the compression claim needs the tree to be smaller: ${tree.nodes.size} nodes vs $slots item slots",
            tree.nodes.size < slots,
        )
        // Header chains must account for every occurrence, or the mining step is unsound.
        tree.header.forEach { (item, ids) ->
            assertEquals(item, support(setOf(item)), ids.sumOf { tree.nodes[it].count })
        }
    }

    @Test
    fun `a high-confidence rule with lift below one exists`() {
        // The frame that argues against shipping confidence alone needs a real example, not a
        // hypothetical one. Measured: E → B at confidence 0.75 and lift 0.83.
        val misleading = allRules().filter { it.lift < 1.0 }.maxByOrNull { it.confidence }
        assertTrue("no rule with lift < 1 — the confidence-is-not-enough frame has no example", misleading != null)
        assertTrue("its confidence should look convincing, got ${misleading!!.confidence}", misleading.confidence >= 0.7)
        assertTrue(
            "and its lift should say the opposite, got ${misleading.lift}",
            misleading.lift < 1.0,
        )
    }

    // ── Time series ──────────────────────────────────────────────────────────

    private val series = retailSeries()
    private val train = trainingPart(series)
    private val actual = holdOutPart(series)
    private val benchmark = forecastRmse(seasonalNaiveForecast(train, actual.size), actual)

    @Test
    fun `a wider moving average smooths more and lags more`() {
        // Measured: roughness 7.21 raw, 4.61 at w=3, 2.54 at w=6, 0.48 at w=12.
        val raw = roughness(train)
        val widths = listOf(3, 6, 12).map { roughness(movingAverage(train, it).filterNotNull()) }
        assertTrue(widths[0] < raw)
        assertTrue(widths[1] < widths[0])
        assertTrue(widths[2] < widths[1])

        // And the warm-up cost that the lab's third readout quotes.
        assertEquals(train.size - 11, movingAverage(train, 12).filterNotNull().size)
    }

    @Test
    fun `differencing pulls the lag-1 autocorrelation down`() {
        // Measured: 0.870 undifferenced, 0.168 after one difference. This is the ARIMA lab's
        // stationarity readout, and the note branches on it.
        val before = lag1Autocorrelation(train)
        val after = lag1Autocorrelation(difference(train))
        assertTrue("a trending series should look non-stationary, got $before", before > 0.7)
        assertTrue("one difference should fix it, got $after", after < 0.4)
    }

    @Test
    fun `the seasonal difference is what removes the annual cycle`() {
        // Measured: lag-12 autocorrelation 0.328 -> -0.104, and forecast error falls with it.
        val fit = fitSarima(train, 2, seasonalDifference = true, horizon = actual.size)
        assertTrue("lag-12 autocorrelation should fall, ${fit.acfBefore} -> ${fit.acfAfter}", fit.acfAfter < fit.acfBefore)

        val without = forecastRmse(fitSarima(train, 2, false, actual.size).forecast, actual)
        val with = forecastRmse(fit.forecast, actual)
        assertTrue("the seasonal difference should improve the forecast: $with vs $without", with < without)
        assertTrue("and it should clear the seasonal-naive benchmark: $with vs $benchmark", with < benchmark)
    }

    @Test
    fun `AR reaches this series' seasonality only by spending a lag on every month`() {
        val byOrder = (1..12).map { p -> p to forecastRmse(arForecast(fitAr(train, p), train, actual.size), actual) }
        println("AR forecast RMSE by p: " + byOrder.joinToString { "${it.first}=${"%.2f".format(it.second)}" })

        // Short models cannot see a year back at all, so they lose to seasonal-naive.
        byOrder.filter { it.first <= 6 }.forEach { (p, rmse) ->
            assertTrue("AR($p) should lose to seasonal-naive, got $rmse vs $benchmark", rmse > benchmark)
        }
        // A long one can — by spending twelve parameters to express one seasonal idea, which is
        // exactly the lab's point and the reason the seasonal models exist.
        assertTrue(
            "AR(12) should be able to reach the annual lag: ${byOrder.last().second} vs $benchmark",
            byOrder.last().second < benchmark,
        )
    }

    @Test
    fun `Holt-Winters and Prophet both beat the benchmark this AR model cannot`() {
        // Measured: Holt-Winters 4.72 at (0.3, 0.1, 0.3), Prophet 3.77 at four changepoints.
        val hw = forecastRmse(holtWinters(train, 0.3, 0.1, 0.3, actual.size).forecast, actual)
        assertTrue("Holt-Winters should beat seasonal-naive: $hw vs $benchmark", hw < benchmark)

        val prophet = forecastRmse(fitProphet(train, 4, 2, 1.0, actual.size).forecast, actual)
        assertTrue("Prophet should beat seasonal-naive: $prophet vs $benchmark", prophet < benchmark)
    }

    @Test
    fun `over-smoothing Holt-Winters fits the past and ruins the forecast`() {
        // The note that fires at high α, β, γ needs the gap to be real. Measured: in-sample 5.05,
        // forecast 21.08 at (0.8, 0.3, 0.8) — worse than the benchmark by a factor of three.
        val hot = holtWinters(train, 0.8, 0.3, 0.8, actual.size)
        val inSample = rmseOf(train.indices.map { train[it] - hot.fitted[it] })
        val outSample = forecastRmse(hot.forecast, actual)
        assertTrue(
            "high smoothing parameters should hurt the forecast, in $inSample out $outSample",
            outSample > inSample * 2.5,
        )
    }

    @Test
    fun `Prophet needs changepoints for a series whose slope changes`() {
        // The series changes slope at month 30 on purpose. With no changepoint the trend is one
        // straight line and cannot describe both halves. Measured: 12.33 with none, 3.77 with four.
        val none = forecastRmse(fitProphet(train, 0, 2, 1.0, actual.size).forecast, actual)
        val some = forecastRmse(fitProphet(train, 4, 2, 1.0, actual.size).forecast, actual)
        assertTrue("changepoints should earn their keep: $none -> $some", some < none)
    }

    @Test
    fun `the changepoint penalty shrinks the slope changes it is applied to`() {
        // Prophet's sparse prior on δ, which is the only thing stopping a kink at every candidate.
        // Measured at eight changepoints: total |δ| 10.86 unpenalised, 6.15 at 1e0, 1.17 at 5e1.
        fun totalDelta(penalty: Double) = fitProphet(train, 8, 2, penalty, actual.size).deltas.sumOf { kotlin.math.abs(it) }
        val free = totalDelta(0.0)
        val mild = totalDelta(1.0)
        val strong = totalDelta(50.0)
        assertTrue("penalty should shrink the deltas: $free -> $mild -> $strong", mild < free && strong < mild)
    }

    @Test
    fun `every forecast lands in the same neighbourhood as the data`() {
        // A diverging AR or a failed integration produces a forecast that is off the chart, and the
        // lab draws it without complaint. Nothing here should leave the series' own range by much.
        val range = train.min()..train.max()
        val span = range.endInclusive - range.start
        val forecasts = mapOf(
            "ar" to arForecast(fitAr(train, 2), train, actual.size),
            "arima" to fitArima(train, 2, 1, 1, actual.size).forecast,
            "sarima" to fitSarima(train, 2, true, actual.size).forecast,
            "holtWinters" to holtWinters(train, 0.3, 0.1, 0.3, actual.size).forecast,
            "prophet" to fitProphet(train, 4, 2, 1.0, actual.size).forecast,
        )
        forecasts.forEach { (name, values) ->
            values.forEach {
                assertTrue("$name produced a non-finite forecast", it.isFinite())
                assertTrue(
                    "$name forecast $it is far outside the observed range $range",
                    it > range.start - span && it < range.endInclusive + span,
                )
            }
        }
    }
}
