import SwiftUI

// Port of the walkConfigs map in ArrayWalkSection.kt.

let walkConfigs: [String: WalkConfig] = [
    "flash_attention": WalkConfig(intro: "The tiled softmax as a scan over key blocks, carrying a running maximum and denominator. It computes the same function as the textbook version — the last frames price what that buys and what it costs.",
        legend: [(walkActiveFill, "Current block"), (walkDoneFill, "Folded in"), (walkResultFill, "Result")], build: flashAttentionFrames),
    "ssm": WalkConfig(intro: "One diagonal linear recurrence, walked token by token and then rebuilt as a convolution kernel. The two forms are the same function, and the lab reports the gap rather than asserting it.",
        legend: [(walkActiveFill, "Current token"), (walkWindowFill, "Computed"), (walkResultFill, "Convolution")], build: ssmFrames),
    "mamba": WalkConfig(intro: "The selective-copying task on three one-channel systems. The aux row is the state, which is where the argument lives: a fixed decay forgets the signal, no decay cannot ignore the filler.",
        legend: [(walkActiveFill, "Failing arm"), (walkWindowFill, "State"), (walkResultFill, "Selective")], build: mambaFrames),
    "rwkv": WalkConfig(intro: "A weighted average with no query in it — a learned decay and a per-token key. The closing frames price both sides of that trade: a fixed-size state, and a needle it cannot reach for.",
        legend: [(walkActiveFill, "Current token"), (walkWindowFill, "Read-out"), (walkResultFill, "Cost")], build: rwkvFrames),
    "label_encoding": WalkConfig(intro: "A colour column encoded two ways, then scored: 40x the error in a linear model, and exactly nothing in a tree.",
        legend: [(walkActiveFill, "Cost"), (walkDoneFill, "Free"), (walkResultFill, "Filled")], build: labelEncodingFrames),
    "missing_value_imputation": WalkConfig(intro: "30% of a column missing. What a constant fill does to its variance and to every correlation it was in, measured against the complete data.",
        legend: [(walkActiveFill, "Missing / changed"), (walkDoneFill, "Original"), (walkResultFill, "Imputed")], build: imputationFrames),
    "outlier_detection": WalkConfig(intro: "The z-score rule against the IQR rule, including the sample where the z-score rule flags nothing at all and the sample sizes where it cannot fire.",
        legend: [(walkResultFill, "Flagged"), (walkActiveFill, "Missed"), (walkDoneFill, "Robust")], build: outlierFrames),
    "chi_square_selection": WalkConfig(intro: "Contingency tables and chi-square scores over five features — including XOR-labelled data, where it ranks the noise above the signal.",
        legend: [(walkDoneFill, "Selected"), (walkActiveFill, "Blind spot"), (walkWindowFill, "Counts")], build: chiSquareFrames),
    "rfe": WalkConfig(intro: "Fit, drop the weakest coefficient, refit. Four rounds on five features, then the same run on data its model cannot express.",
        legend: [(walkActiveFill, "Being dropped"), (walkWindowFill, "Coefficient"), (walkResultFill, "Survivor")], build: rfeFrames),
    "apriori": WalkConfig(intro: "Ten baskets, five items, minimum support 3. Level by level: generate candidates, prune what cannot possibly be frequent, then count only what is left.",
        legend: [(walkActiveFill, "Being counted"), (walkDoneFill, "Frequent"), (walkResultFill, "Answer")], build: aprioriFrames),
    "eclat": WalkConfig(intro: "The same database stored by column instead of by row, so support becomes the length of a set intersection rather than the result of a counting pass.",
        legend: [(walkWindowFill, "In tid-list"), (walkDoneFill, "In intersection"), (walkResultFill, "Answer")], build: eclatFrames),
    "kmp": WalkConfig(intro: "First the LPS table is built from the pattern alone, then the text is scanned. Watch the text pointer i on the second phase: it only ever moves forward, even on a mismatch.",
        legend: walkPointerLegend, build: kmpFrames),
    "rabin_karp": WalkConfig(intro: "Base-10 hashes mod 13 over a digit string. Most windows are rejected on a number comparison alone — and one collision shows why a hash hit still has to be verified.",
        legend: walkPointerLegend, build: rabinKarpFrames),
    "manacher": WalkConfig(intro: "Radii for every centre of \"#a#b#a#c#a#b#a#\". Centres inside a known palindrome inherit their mirror's radius instead of expanding from zero.",
        legend: walkPointerLegend, build: manacherFrames),
    "prefix_sum": WalkConfig(intro: "One pass builds P, then every range sum is a single subtraction. Watch the query at the end pay nothing for the width of the range.",
        legend: walkPointerLegend, build: prefixSumFrames),
    "difference_array": WalkConfig(intro: "The mirror image of prefix sum: two writes record a whole range update, and one prefix pass at the end turns all of them into the final array.",
        legend: walkPointerLegend, build: differenceArrayFrames),
    "sliding_window": WalkConfig(intro: "A fixed window of 3 over the array. Each slide subtracts what leaves and adds what enters, so the sum is maintained rather than recomputed.",
        legend: walkPointerLegend, build: slidingWindowFrames),
    "two_pointer": WalkConfig(intro: "Pair sums on a sorted array. Each comparison rules out an entire row or column of the pair table, which is why one pass replaces the nested loop.",
        legend: walkPointerLegend, build: twoPointerFrames),
    "kadanes_algorithm": WalkConfig(intro: "Kadane in one pass. The only state is \"best sum ending here\" — the moment extending is worse than starting over, the subarray restarts.",
        legend: walkPointerLegend, build: kadaneFrames),
    "top_k_elements": WalkConfig(intro: "Top-3 over a stream using a min-heap of size 3. The heap's smallest element is the admission price: anything below it can be discarded on sight.",
        legend: walkHeapLegend, build: topKStreamFrames),
    "sliding_window_pattern": WalkConfig(intro: "The pattern applied to a variable-length window: longest substring with no repeated character. The window grows on the right and only ever shrinks from the left.",
        legend: walkPointerLegend, build: longestUniqueWindowFrames),
    "two_pointer_pattern": WalkConfig(intro: "The same-direction variant of the pattern: a read pointer scans while a write pointer trails, compacting a sorted array in place.",
        legend: walkPointerLegend, build: dedupeInPlaceFrames),
    "fast_slow_pointers": WalkConfig(intro: "A linked list whose tail points back into itself. One pointer moves one step, the other two — where they meet, and what to do next, is the whole pattern.",
        legend: [(walkWindowFill, "slow"), (walkActiveFill, "fast"), (walkResultFill, "Meeting point")], build: fastSlowFrames),
    "merge_intervals_pattern": WalkConfig(intro: "Sort by start, then keep one open interval and either extend it or close it. The track underneath shows what the merged set looks like at each step.",
        legend: [(walkActiveFill, "Considering"), (walkDoneFill, "Merged"), (walkResultFill, "Final")], build: mergeIntervalsFrames),
    "top_k_pattern": WalkConfig(intro: "Top-2 most frequent. Counting comes first; the heap only decides the selection, and its size caps the log factor at log k rather than log m.",
        legend: walkHeapLegend, build: topKFrequentFrames),
    "prefix_sum_pattern": WalkConfig(intro: "The interview form of prefix sums: counting subarrays that hit a target, with a map of totals already seen. The negative value in the input is there to show why a window cannot do this.",
        legend: [(walkActiveFill, "Reading"), (walkWindowFill, "In prefix"), (walkResultFill, "Answer")], build: prefixSumPatternFrames),
    "binary_search_answer": WalkConfig(intro: "Binary search where the array is unsorted and the search runs over candidate answers instead. Each probe repacks the ships; the row underneath is which day every package sails on.",
        legend: [(walkActiveFill, "Even-numbered day"), (walkWindowFill, "Odd-numbered day"), (walkResultFill, "Final packing")], build: binarySearchAnswerFrames),
    "monotonic_stack_pattern": WalkConfig(intro: "Next greater element. Watch the aux row stay in decreasing order — every pop is one index learning its answer, which is why the whole scan is O(n).",
        legend: [(walkActiveFill, "Incoming"), (walkWindowFill, "On stack"), (walkDoneFill, "Answered")], build: monotonicStackFrames),
    "cyclic_sort_pattern": WalkConfig(intro: "Values 1..n placed by swapping each one to the index it names. The array ends sorted with a single mismatch, and that mismatch is both the duplicate and the missing value.",
        legend: [(walkActiveFill, "Being placed"), (walkDoneFill, "Home"), (walkResultFill, "Mismatch")], build: cyclicSortFrames),
    "in_place_reversal_pattern": WalkConfig(intro: "Reversing a linked list with prev / cur / next. The aux row is the reversed chain as it grows — no second list is ever allocated.",
        legend: [(walkActiveFill, "cur"), (walkDoneFill, "Reversed"), (walkResultFill, "Final order")], build: inPlaceReversalFrames),
    "k_way_merge_pattern": WalkConfig(intro: "Three sorted lists merged through a heap that never holds more than one head per list. The output row fills left to right; the heap row is what makes each choice O(log k).",
        legend: [(walkActiveFill, "Popped"), (walkDoneFill, "In heap"), (walkResultFill, "Merged")], build: kWayMergeFrames),
    "greedy_intervals_pattern": WalkConfig(intro: "Earliest-finish-first on one room. The track underneath shows the kept set growing, and the count of drops is the answer to the \"minimum removals\" phrasing of the same problem.",
        legend: [(walkActiveFill, "Considering"), (walkDoneFill, "Kept"), (walkResultFill, "Final set")], build: greedyIntervalsFrames),
    "expression_stack_pattern": WalkConfig(intro: "Decoding \"3[a2[bc]]\". The aux row is the stack of suspended contexts — each '[' pushes one, each ']' pops one and folds the finished piece into its parent.",
        legend: [(walkActiveFill, "Current token"), (walkWindowFill, "Suspended context"), (walkResultFill, "Decoded output")], build: expressionStackFrames),
    "heap_scheduling_pattern": WalkConfig(intro: "Meeting rooms: sorted by start, with a min-heap of end times underneath. The heap's size is the answer — watch it grow only when nothing has retired in time.",
        legend: [(walkActiveFill, "Starting now"), (walkDoneFill, "Room in use"), (walkResultFill, "Final schedule")], build: heapSchedulingFrames),
    "lis_patience_pattern": WalkConfig(intro: "The tails array doing its work. Most elements overwrite a tail rather than extend it — the row's length only grows when an element beats every chain so far.",
        legend: [(walkActiveFill, "Current element"), (walkWindowFill, "tails"), (walkResultFill, "Answer")], build: lisTailsFrames),
    "monotonic_deque_pattern": WalkConfig(intro: "Sliding-window maximum with k = 3. Two rules fire on every element: expire the front, pop the dominated from the back. What is left in front is the answer.",
        legend: [(walkActiveFill, "Incoming"), (walkWindowFill, "In window / deque"), (walkResultFill, "Window max")], build: windowMaxDequeFrames),
    "palindrome_expansion_pattern": WalkConfig(intro: "Both centre types tried at every index of \"abbanana\" — the even centres are the ones that find \"abba\", which is why forgetting them is the standard bug.",
        legend: [(walkActiveFill, "Centre"), (walkWindowFill, "Palindrome here"), (walkResultFill, "Longest so far")], build: palindromeExpansionFrames),
    "prefix_function_pattern": WalkConfig(intro: "The pi table built one character at a time. The interesting frames are the mismatches, where k falls back to pi[k−1] instead of restarting at zero.",
        legend: [(walkActiveFill, "Current index"), (walkWindowFill, "Border prefix"), (walkResultFill, "Final border")], build: prefixFunctionFrames),
    "randomized_pattern": WalkConfig(intro: "Fisher-Yates with the draw range drawn underneath. Every swap picks from [i, n) — the aux row is the legal range, and widening it to [0, n) is exactly the bias people ship.",
        legend: [(walkActiveFill, "Drawn index j"), (walkDoneFill, "Fixed"), (walkWindowFill, "Legal draws")], build: fisherYatesFrames),
    "range_query_pattern": WalkConfig(intro: "The same array under both structures: first a prefix-sum rebuild after one write, then the Fenwick update and query walks that replace it. i & −i is doing all the work.",
        legend: [(walkActiveFill, "On the walk"), (walkWindowFill, "Blocks / prefixes"), (walkResultFill, "Queried range")], build: fenwickRangeQueryFrames),
    "rolling_hash_pattern": WalkConfig(intro: "\"abra\" in \"abracadabra\" with a base-31 hash mod 1009. Each slide is three operations, and every hash hit still gets a character-by-character verification.",
        legend: [(walkActiveFill, "Candidate"), (walkWindowFill, "Current window"), (walkResultFill, "Verified match")], build: rollingHashPatternFrames),
    "running_best_pattern": WalkConfig(intro: "Kadane with the \"best ending here\" row exposed. The last frame switches to the product variant, where the running minimum is what produces the answer.",
        legend: [(walkActiveFill, "Current element"), (walkWindowFill, "Current run"), (walkResultFill, "Best subarray")], build: runningBestFrames),
    "sweep_line_pattern": WalkConfig(intro: "Five intervals reduced to ten endpoints. The track underneath still shows the intervals, but the sweep never consults them again — only the ±1 events.",
        legend: [(walkActiveFill, "Current event"), (walkWindowFill, "Active"), (walkResultFill, "Peak overlap")], build: sweepLineFrames),
    "two_heaps_pattern": WalkConfig(intro: "A running median over eight values. The aux row is both heaps side by side — lo largest-first, hi smallest-first — so the median is always the pair in the middle.",
        legend: [(walkActiveFill, "Arriving"), (walkWindowFill, "lo (smaller half)"), (walkDoneFill, "hi (larger half)")], build: twoHeapsFrames),
    "quickselect": WalkConfig(intro: "Partition, then recurse into one side only. The comparison count at the end is the argument for why selecting is cheaper than sorting.",
        legend: [(walkActiveFill, "Comparing"), (walkWindowFill, "Below pivot"), (walkResultFill, "Pivot · answer")], build: quickselectFrames),
    "median_of_medians": WalkConfig(intro: "A pivot chosen so its split is guaranteed rather than hoped for — and the measured split it produces on this input.",
        legend: [(walkActiveFill, "Group median"), (walkWindowFill, "Below pivot"), (walkResultFill, "Pivot")], build: medianOfMediansFrames),
    "mos_algorithm": WalkConfig(intro: "The same five range queries answered in two different orders, with the pointer travel counted both times. The ordering is the entire algorithm.",
        legend: [(walkWindowFill, "Current window"), (walkActiveFill, "Pointer"), (walkDoneFill, "Answered")], build: mosAlgorithmFrames),
    "reservoir_sampling": WalkConfig(intro: "One pass, constant memory, and a uniform sample from a stream of unknown length — with the uniformity measured over 20,000 runs rather than asserted.",
        legend: [(walkActiveFill, "Current item"), (walkResultFill, "In reservoir"), (walkDoneFill, "Within tolerance")], build: reservoirSamplingFrames),
    "string": WalkConfig(intro: "Characters in contiguous storage. Indexing and comparison are the easy half; the interesting half is what immutability does to a loop that builds a string with +.",
        legend: [(walkActiveFill, "Current character"), (walkDoneFill, "Settled"), (walkResultFill, "Result")], build: stringFrames),
    "list_adt": WalkConfig(intro: "One script of list operations run against two implementations at once. The contract is identical at every step; the counters underneath are not.",
        legend: [(walkActiveFill, "Touched"), (walkWindowFill, "Traversed"), (walkResultFill, "Written")], build: listAdtFrames),
    "job_sequencing": WalkConfig(intro: "Highest profit first, each job dropped into the latest slot that still meets its deadline. The final frames check the greedy answer against every other schedule.",
        legend: [(walkActiveFill, "Considering"), (walkDoneFill, "Scheduled"), (walkResultFill, "Slot filled")], build: jobSequencingFrames),
    "fractional_knapsack": WalkConfig(intro: "Sort by value per kilogram, fill greedily, split the last item. Then the same greedy is turned loose on the indivisible version to show exactly where the argument breaks.",
        legend: [(walkActiveFill, "Considering"), (walkDoneFill, "Taken whole"), (walkResultFill, "Taken in part")], build: fractionalKnapsackFrames),
    "activity_selection": WalkConfig(intro: "Sort by finish time, sweep once, take anything that starts after the last thing taken. The last two frames run earliest-start and shortest-duration on the same idea so the wrong sort keys are seen losing.",
        legend: [(walkActiveFill, "Considering"), (walkDoneFill, "Selected"), (walkResultFill, "Final schedule")], build: activitySelectionFrames),
    "coin_change_greedy": WalkConfig(intro: "Greedy change-making and the DP table, on the same {1, 3, 4} coins and the same target of 6. Greed commits to the 4 and pays three coins; the table finds 3 + 3.",
        legend: [(walkActiveFill, "Remaining amount"), (walkWindowFill, "Tabulated"), (walkResultFill, "Answer")], build: coinChangeGreedyFrames),
    "naive_string_search": WalkConfig(intro: "The pattern drawn where it currently sits, one frame per character comparison. The shift of one is a movement on screen, and the last frame counts the worst case rather than describing it.",
        legend: [(walkActiveFill, "Comparing"), (walkWindowFill, "Matched this alignment"), (walkResultFill, "Mismatch / match")], build: naiveSearchFrames),
    "z_algorithm": WalkConfig(intro: "The Z-array built left to right. The pointers are the window [l, r) whose right edge never moves left — the readout counts how many positions were copied from a mirror against how many characters were actually compared.",
        legend: [(walkActiveFill, "Current index"), (walkDoneFill, "Prefix it matches"), (walkResultFill, "The run found here")], build: zAlgorithmFrames),
    "longest_palindromic_substring": WalkConfig(intro: "Expand around every centre — the character centres and the gap centres both, since dropping the gaps is the bug that reports \"a\" as the longest palindrome in \"abba\".",
        legend: [(walkWindowFill, "Expanded here"), (walkDoneFill, "Best so far"), (walkResultFill, "New best")], build: longestPalindromeFrames),
    "euclid_gcd": WalkConfig(intro: "The remainder chain for gcd(252, 105) as a growing row, then the back-substitution that turns it into Bézout coefficients — which is the part modular inverses, CRT and RSA key generation actually consume.",
        legend: [(walkActiveFill, "Current remainder"), (walkWindowFill, "Previous pair"), (walkResultFill, "gcd / result")], build: euclidGcdFrames),
    "modular_arithmetic": WalkConfig(intro: "Residues mod 7, and the one operation that does not survive the collapse. The aux row is a·k mod m — whether 1 ever appears in it is exactly whether a has an inverse.",
        legend: [(walkActiveFill, "Current"), (walkWindowFill, "Residue reached"), (walkResultFill, "Answer / inverse")], build: modularArithmeticFrames),
    "sieve_of_eratosthenes": WalkConfig(intro: "2 through 30 across two rows. Each pass strikes one prime's multiples starting at p², and the outer loop stops at √30 — so only 2, 3 and 5 ever mark anything and nothing is ever divided.",
        legend: [(walkActiveFill, "Prime being processed"), (walkWindowFill, "Still standing"), (walkResultFill, "Struck this pass")], build: sieveFrames),
    "fermats_little_theorem": WalkConfig(intro: "Powers of 3 mod 7, one exponent at a time, arriving at 1 exactly at exponent 6. Then the inverse that follows from it, and the composite that passes the test anyway.",
        legend: [(walkActiveFill, "Current exponent"), (walkWindowFill, "Computed"), (walkResultFill, "≡ 1 / result")], build: fermatFrames),
    "chinese_remainder_theorem": WalkConfig(intro: "0 through 31 across two rows, with each congruence applied as a filter. One number survives all three, and the closing frames show the construction that finds it without scanning at all.",
        legend: [(walkWindowFill, "Still possible"), (walkResultFill, "The unique solution"), (walkActiveFill, "Eliminated")], build: crtFrames),
]
