package com.algora.app.feature.interviewprep.quiz

import com.algora.app.core.data.model.Difficulty

// Subject quizzes: one per area. Unlike the mixed mock
// and company sets, every question here drills the same area, and each links back to the topic that
// explains it so a wrong answer turns into a reading target.

internal val arraysStringsQuiz = Quiz(
    id = "arrays_strings_quiz",
    title = "Arrays & Strings",
    description = "Indexing, shifting, windows and in-place edits.",
    questions = listOf(
        QuizQuestion(
            prompt = "Inserting at the front of an array of n elements costs:",
            options = listOf("O(n) — every element shifts one slot right", "O(1) — arrays grow at the front", "O(log n)", "O(n log n)"),
            correctIndex = 0,
            patternTag = "Arrays",
            difficulty = Difficulty.BEGINNER,
            explanation = "Arrays are contiguous, so making room at index 0 shifts all n elements. Only appending at the tail is O(1) amortized.",
            linkedTopicId = "array",
            linkedTopicLabel = "Array",
        ),
        QuizQuestion(
            prompt = "A dynamic array doubles its capacity when full. The amortized cost of one append is:",
            options = listOf("O(1)", "O(n) — every append copies", "O(log n)", "O(n²) across n appends"),
            correctIndex = 0,
            patternTag = "Amortized Analysis",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Doubling makes copies rare: n appends cost n + n/2 + n/4 + … < 2n total work, so each append averages O(1).",
            linkedTopicId = "array",
            linkedTopicLabel = "Array",
        ),
        QuizQuestion(
            prompt = "Which problem is NOT a natural fit for a sliding window?",
            options = listOf(
                "Longest subsequence (non-contiguous) with a property",
                "Longest substring without repeating characters",
                "Maximum sum subarray of fixed size k",
                "Smallest subarray with sum ≥ target, all values positive",
            ),
            correctIndex = 0,
            patternTag = "Sliding Window",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A window is always contiguous. Subsequences allow gaps, so they need DP or another technique.",
            linkedTopicId = "sliding_window",
            linkedTopicLabel = "Sliding Window",
        ),
        QuizQuestion(
            prompt = "To answer many range-sum queries on a fixed array in O(1) each, precompute:",
            options = listOf("Prefix sums", "A sorted copy", "A hash map of every subarray", "A balanced BST"),
            correctIndex = 0,
            patternTag = "Prefix Sum",
            difficulty = Difficulty.BEGINNER,
            explanation = "With prefix[i] holding the sum of the first i elements, sum(l..r) = prefix[r+1] - prefix[l].",
            linkedTopicId = "prefix_sum",
            linkedTopicLabel = "Prefix Sum",
        ),
        QuizQuestion(
            prompt = "Reversing a string in place with two pointers uses how much extra space?",
            options = listOf("O(1)", "O(n)", "O(log n)", "O(n) only for odd lengths"),
            correctIndex = 0,
            patternTag = "Two Pointer",
            difficulty = Difficulty.BEGINNER,
            explanation = "Swapping from both ends inward needs only the two indices and one temporary — no second buffer.",
            linkedTopicId = "two_pointer",
            linkedTopicLabel = "Two Pointer Technique",
        ),
        QuizQuestion(
            prompt = "Why does a sliding window fail for \"count subarrays summing to k\" when negatives are allowed?",
            options = listOf(
                "The running sum is no longer monotone, so shrinking cannot be decided",
                "Windows cannot hold negative numbers",
                "The window would exceed the array bounds",
                "It works fine — negatives change nothing",
            ),
            correctIndex = 0,
            patternTag = "Prefix Sum",
            difficulty = Difficulty.ADVANCED,
            explanation = "Shrinking a window assumes removing an element lowers the sum. With negatives it can raise it, so prefix sums with a hash map are used instead.",
            linkedTopicId = "prefix_sum",
            linkedTopicLabel = "Prefix Sum",
        ),
        QuizQuestion(
            prompt = "An array holds each of 1..n once except that one value is missing and one is duplicated. Finding both in O(n) time and O(1) extra space uses:",
            options = listOf(
                "Cyclic sort — swap each value to index value − 1, then scan for the mismatch",
                "A hash set of everything seen so far",
                "Sorting the array, then scanning for the gap",
                "Binary search over the value range",
            ),
            correctIndex = 0,
            patternTag = "Cyclic Sort",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Because the values are exactly the index range, the array can be its own hash table: keep swapping until each slot holds its own value. The one index still holding the wrong value names both the duplicate and the missing number. The hash set is O(n) space and sorting is O(n log n).",
            linkedTopicId = "cyclic_sort_pattern",
            linkedTopicLabel = "Cyclic Sort",
        ),
    ),
)

internal val linkedListsQuiz = Quiz(
    id = "linked_lists_quiz",
    title = "Linked Lists",
    description = "Pointer rewiring, cycles and traversal costs.",
    questions = listOf(
        QuizQuestion(
            prompt = "Accessing the kth element of a singly linked list costs:",
            options = listOf("O(k) — you must walk from the head", "O(1) — same as an array", "O(log k)", "O(n log n)"),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.BEGINNER,
            explanation = "Nodes are scattered in memory with no index arithmetic, so position is only reachable by traversal.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Detecting a cycle in O(1) extra space uses:",
            options = listOf("Floyd's fast and slow pointers", "A visited hash set", "Sorting the nodes", "Binary search on node index"),
            correctIndex = 0,
            patternTag = "Fast & Slow Pointers",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Inside a cycle the gap between a 1-step and a 2-step pointer closes by one per iteration, so they must meet. A hash set works but costs O(n) space.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "When reversing a list iteratively, the classic bug is:",
            options = listOf(
                "Overwriting cur.next before saving it, losing the rest of the list",
                "Starting prev at the head instead of null",
                "Returning cur instead of prev",
                "Using a while loop rather than recursion",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "cur.next is the only reference to the remainder. Save it in a local before flipping the pointer.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "A dummy head node is used mainly to:",
            options = listOf(
                "Remove the special case of modifying the real head",
                "Speed up traversal",
                "Store the list length",
                "Allow random access",
            ),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.BEGINNER,
            explanation = "With a node in front of the head, insertion and deletion at position 0 use the same code as anywhere else.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Deleting a known node from a doubly linked list, given a reference to it, costs:",
            options = listOf("O(1)", "O(n) — you must find its predecessor", "O(log n)", "O(n) only for the tail"),
            correctIndex = 0,
            patternTag = "Linked List",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The back-pointer gives the predecessor directly. In a singly linked list the same operation is O(n) because the predecessor must be found.",
            linkedTopicId = "doubly_linked_list",
            linkedTopicLabel = "Doubly Linked List",
        ),
        QuizQuestion(
            prompt = "After fast and slow meet inside a cycle, moving one pointer back to the head and advancing both by one lands them at:",
            options = listOf("The node where the cycle begins", "The meeting point again", "The list's midpoint", "The last node before the cycle closes"),
            correctIndex = 0,
            patternTag = "Fast & Slow Pointers",
            difficulty = Difficulty.ADVANCED,
            explanation = "Slow travelled F + a and fast twice that, giving F = kL - a. So the distance head→entry equals meeting-point→entry.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
    ),
)

internal val stacksQueuesQuiz = Quiz(
    id = "stacks_queues_quiz",
    title = "Stacks & Queues",
    description = "LIFO, FIFO, monotonic stacks and deques.",
    questions = listOf(
        QuizQuestion(
            prompt = "Checking balanced brackets requires a stack because:",
            options = listOf(
                "The next bracket that must close is always the most recently opened one",
                "Counting brackets is impossible without one",
                "Stacks sort the brackets",
                "It gives O(1) random access",
            ),
            correctIndex = 0,
            patternTag = "Stack",
            difficulty = Difficulty.BEGINNER,
            explanation = "Counting alone accepts \"([)]\". LIFO order is exactly what nesting demands.",
            linkedTopicId = "stack",
            linkedTopicLabel = "Stack",
        ),
        QuizQuestion(
            prompt = "A monotonic decreasing stack is the standard tool for:",
            options = listOf("Next greater element", "Sorting in O(n)", "Cycle detection", "Shortest paths"),
            correctIndex = 0,
            patternTag = "Monotonic Stack",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Indices waiting for a larger value stay on the stack in decreasing order; one bigger arrival resolves all of them at once.",
            linkedTopicId = "stack",
            linkedTopicLabel = "Stack",
        ),
        QuizQuestion(
            prompt = "BFS uses a queue rather than a stack because:",
            options = listOf(
                "FIFO order visits all nodes at distance d before any at d + 1",
                "Queues are faster than stacks",
                "A stack cannot store graph nodes",
                "Queues remove duplicates automatically",
            ),
            correctIndex = 0,
            patternTag = "Queue",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Swapping in a stack turns the same code into DFS — the container choice *is* the traversal order.",
            linkedTopicId = "queue",
            linkedTopicLabel = "Queue",
        ),
        QuizQuestion(
            prompt = "Implementing a queue with two stacks gives amortized dequeue cost of:",
            options = listOf("O(1)", "O(n) every time", "O(log n)", "O(n) only when empty"),
            correctIndex = 0,
            patternTag = "Stack",
            difficulty = Difficulty.ADVANCED,
            explanation = "Elements move from the in-stack to the out-stack at most once each, so the occasional O(n) transfer averages to O(1).",
            linkedTopicId = "stack",
            linkedTopicLabel = "Stack",
        ),
        QuizQuestion(
            prompt = "A circular buffer queue avoids which cost of a naive array queue?",
            options = listOf(
                "Shifting every element left after each dequeue",
                "Allocating memory at all",
                "Comparisons during enqueue",
                "Recursion depth",
            ),
            correctIndex = 0,
            patternTag = "Queue",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Advancing a head index modulo capacity makes dequeue O(1) instead of O(n).",
            linkedTopicId = "queue",
            linkedTopicLabel = "Queue",
        ),
        QuizQuestion(
            prompt = "Supporting getMin() in O(1) alongside push and pop requires:",
            options = listOf(
                "A parallel stack of the minimum at each depth",
                "Sorting on every push",
                "A single min variable",
                "A binary search tree",
            ),
            correctIndex = 0,
            patternTag = "Stack",
            difficulty = Difficulty.ADVANCED,
            explanation = "A single variable cannot be restored after popping the current minimum. Storing the minimum per depth restores it for free.",
            linkedTopicId = "stack",
            linkedTopicLabel = "Stack",
        ),
    ),
)

internal val treesBstQuiz = Quiz(
    id = "trees_bst_quiz",
    title = "Trees & BST",
    description = "Traversal orders, balance and the BST invariant.",
    questions = listOf(
        QuizQuestion(
            prompt = "In-order traversal of a valid BST produces values in:",
            options = listOf("Ascending sorted order", "Level order", "Insertion order", "Descending order"),
            correctIndex = 0,
            patternTag = "BST",
            difficulty = Difficulty.BEGINNER,
            explanation = "Left subtree, node, right subtree — with the BST invariant this visits every value in ascending order.",
            linkedTopicId = "binary_search_tree",
            linkedTopicLabel = "Binary Search Tree",
        ),
        QuizQuestion(
            prompt = "Search in a BST degrades from O(log n) to O(n) when:",
            options = listOf("The tree is degenerate — essentially a linked list", "The tree is perfectly balanced", "Values are duplicated", "The tree stores strings"),
            correctIndex = 0,
            patternTag = "BST",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Inserting sorted data produces a single chain, so height becomes n. Self-balancing trees exist to prevent this.",
            linkedTopicId = "avl_red_black_tree",
            linkedTopicLabel = "AVL / Red-Black Tree",
        ),
        QuizQuestion(
            prompt = "Validating a BST by checking only node.left < node < node.right is wrong because:",
            options = listOf(
                "Every node is also bounded by all its ancestors",
                "Left and right must be compared to each other",
                "It ignores null children",
                "It is O(n²)",
            ),
            correctIndex = 0,
            patternTag = "BST",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A node deep in a right subtree must exceed the ancestor it turned right from. Thread a (low, high) range down the recursion.",
            linkedTopicId = "binary_search_tree",
            linkedTopicLabel = "Binary Search Tree",
        ),
        QuizQuestion(
            prompt = "Level-order traversal needs which structure?",
            options = listOf("A queue", "A stack", "A min-heap", "A hash map"),
            correctIndex = 0,
            patternTag = "Tree Traversal",
            difficulty = Difficulty.BEGINNER,
            explanation = "Children are enqueued behind the current level, so a level finishes before the next begins. Snapshot the queue size to separate levels.",
            linkedTopicId = "bfs",
            linkedTopicLabel = "Breadth-First Search (BFS)",
        ),
        QuizQuestion(
            prompt = "Recursive DFS on a tree of height h uses how much stack space?",
            options = listOf("O(h), which is O(n) for a degenerate tree", "O(1) always", "O(n) always", "O(log n) always"),
            correctIndex = 0,
            patternTag = "Tree Traversal",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Only the current root-to-node path is on the stack. Balanced means O(log n); a chain means O(n) and risks overflow.",
            linkedTopicId = "dfs",
            linkedTopicLabel = "Depth-First Search (DFS)",
        ),
        QuizQuestion(
            prompt = "A trie beats a hash set for which task?",
            options = listOf("Finding all stored words with a given prefix", "Testing exact membership fastest", "Sorting numbers", "Detecting cycles"),
            correctIndex = 0,
            patternTag = "Trie",
            difficulty = Difficulty.ADVANCED,
            explanation = "A hash destroys prefix structure. A trie walks the prefix path once and enumerates the subtree below it.",
            linkedTopicId = "trie",
            linkedTopicLabel = "Trie (Prefix Tree)",
        ),
    ),
)

internal val graphsQuiz = Quiz(
    id = "graphs_quiz",
    title = "Graphs",
    description = "Representations, BFS/DFS and shortest paths.",
    questions = listOf(
        QuizQuestion(
            prompt = "For a sparse graph, an adjacency list beats an adjacency matrix mainly in:",
            options = listOf("Space — O(V + E) instead of O(V²)", "Edge-existence lookup time", "Simplicity of code", "Cache locality"),
            correctIndex = 0,
            patternTag = "Graph",
            difficulty = Difficulty.BEGINNER,
            explanation = "A matrix stores a slot per node pair regardless of edges. The matrix does win on O(1) edge lookup.",
            linkedTopicId = "graph",
            linkedTopicLabel = "Graph",
        ),
        QuizQuestion(
            prompt = "Shortest path in an UNWEIGHTED graph is found by:",
            options = listOf("BFS", "DFS", "Dijkstra only", "Topological sort"),
            correctIndex = 0,
            patternTag = "BFS",
            difficulty = Difficulty.BEGINNER,
            explanation = "BFS expands by distance, so the first time it reaches a node is via a minimum-edge path. Dijkstra works but adds needless heap overhead.",
            linkedTopicId = "bfs",
            linkedTopicLabel = "Breadth-First Search (BFS)",
        ),
        QuizQuestion(
            prompt = "Dijkstra's algorithm fails when the graph has:",
            options = listOf("Negative edge weights", "Cycles", "More than 1000 nodes", "Disconnected components"),
            correctIndex = 0,
            patternTag = "Shortest Path",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "It finalises a node on first extraction, which a later negative edge could undercut. Bellman-Ford handles negatives.",
            linkedTopicId = "dijkstras_algorithm",
            linkedTopicLabel = "Dijkstra's Algorithm",
        ),
        QuizQuestion(
            prompt = "Kahn's algorithm reports a cycle when:",
            options = listOf(
                "Fewer nodes are output than the graph contains",
                "The queue starts empty",
                "Any node has in-degree above one",
                "The graph is disconnected",
            ),
            correctIndex = 0,
            patternTag = "Topological Sort",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Nodes inside a cycle never reach in-degree zero, so they never enter the queue and the count falls short.",
            linkedTopicId = "bfs",
            linkedTopicLabel = "Breadth-First Search (BFS)",
        ),
        QuizQuestion(
            prompt = "Counting connected components in a grid is usually done with:",
            options = listOf("Flood fill via DFS/BFS, or union-find", "Binary search", "A monotonic stack", "Topological sort"),
            correctIndex = 0,
            patternTag = "Graph",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Each unvisited land cell starts one traversal that consumes its whole component. Union-find is the alternative when edges stream in.",
            linkedTopicId = "disjoint_set",
            linkedTopicLabel = "Disjoint Set (Union-Find)",
        ),
        QuizQuestion(
            prompt = "Detecting a cycle in an UNDIRECTED graph with DFS requires:",
            options = listOf(
                "Ignoring the edge back to the parent",
                "Marking every node visited twice",
                "Sorting the adjacency list",
                "A priority queue",
            ),
            correctIndex = 0,
            patternTag = "DFS",
            difficulty = Difficulty.ADVANCED,
            explanation = "Every undirected edge appears in both directions, so without skipping the parent every edge looks like a 2-cycle.",
            linkedTopicId = "dfs",
            linkedTopicLabel = "Depth-First Search (DFS)",
        ),
    ),
)

internal val sortingSearchingQuiz = Quiz(
    id = "sorting_searching_quiz",
    title = "Sorting & Searching",
    description = "Stability, pivots and logarithmic search.",
    questions = listOf(
        QuizQuestion(
            prompt = "A stable sort guarantees that:",
            options = listOf(
                "Equal elements keep their original relative order",
                "It never exceeds O(n log n)",
                "It uses O(1) space",
                "It works on linked lists only",
            ),
            correctIndex = 0,
            patternTag = "Sorting",
            difficulty = Difficulty.BEGINNER,
            explanation = "Stability matters when sorting by a second key after a first. Merge sort is stable; quicksort and heapsort are not.",
            linkedTopicId = "merge_sort",
            linkedTopicLabel = "Merge Sort",
        ),
        QuizQuestion(
            prompt = "Quicksort degrades to O(n²) when:",
            options = listOf(
                "Pivots repeatedly split the array very unevenly",
                "The array is large",
                "The array contains negatives",
                "Recursion is replaced by iteration",
            ),
            correctIndex = 0,
            patternTag = "Sorting",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A worst-case pivot peels one element per level, giving n levels of O(n) work. Randomised or median-of-three pivots avoid it.",
            linkedTopicId = "quick_sort",
            linkedTopicLabel = "Quick Sort",
        ),
        QuizQuestion(
            prompt = "Counting sort can beat O(n log n) because it:",
            options = listOf(
                "Does not compare elements — it indexes by value",
                "Uses a better comparison order",
                "Runs in parallel",
                "Sorts in place",
            ),
            correctIndex = 0,
            patternTag = "Sorting",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The Ω(n log n) bound applies only to comparison sorts. Counting sort is O(n + k) but needs a bounded value range.",
            linkedTopicId = "counting_sort",
            linkedTopicLabel = "Counting Sort",
        ),
        QuizQuestion(
            prompt = "Computing mid as (lo + hi) / 2 rather than lo + (hi - lo) / 2 risks:",
            options = listOf("Integer overflow on large bounds", "An infinite loop", "Skipping the first element", "Nothing — they are identical"),
            correctIndex = 0,
            patternTag = "Binary Search",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "lo + hi can exceed Int.MAX_VALUE and wrap negative. The subtraction form never overflows.",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
        ),
        QuizQuestion(
            prompt = "\"Binary searching the answer\" is valid when the feasibility test is:",
            options = listOf(
                "Monotone — once true, true for every larger candidate",
                "Constant time",
                "Randomised",
                "Applied to a sorted array only",
            ),
            correctIndex = 0,
            patternTag = "Binary Search",
            difficulty = Difficulty.ADVANCED,
            explanation = "Monotonicity gives the sorted structure to halve. That is why minimum-eating-speed and capacity problems yield to it.",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
        ),
        QuizQuestion(
            prompt = "Finding the kth largest element in O(n) average time uses:",
            options = listOf("Quickselect", "Merge sort then index", "A full heapsort", "Binary search on the array"),
            correctIndex = 0,
            patternTag = "Selection",
            difficulty = Difficulty.ADVANCED,
            explanation = "Quickselect recurses into only the side holding k, giving n + n/2 + n/4 … = O(n) average. A size-k heap is O(n log k).",
            linkedTopicId = "quickselect",
            linkedTopicLabel = "Quickselect",
        ),
    ),
)

internal val hashingHeapsQuiz = Quiz(
    id = "hashing_heaps_quiz",
    title = "Hashing & Heaps",
    description = "Collisions, load factor and priority queues.",
    questions = listOf(
        QuizQuestion(
            prompt = "Hash map lookup is O(1) on average but O(n) in the worst case because:",
            options = listOf(
                "All keys can collide into one bucket",
                "Resizing happens on every insert",
                "Hashing itself is O(n)",
                "Keys must be sorted first",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A degenerate hash turns every lookup into a scan of one long chain. Tree-ified buckets soften this to O(log n).",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Raising a hash table's load factor threshold trades:",
            options = listOf("Less memory for more collisions", "More memory for more collisions", "Speed for correctness", "Nothing measurable"),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A fuller table resizes less often but packs more keys per bucket, lengthening probe and chain walks.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Building a heap from an unsorted array of n elements costs:",
            options = listOf("O(n) with bottom-up heapify", "O(n log n) always", "O(log n)", "O(n²)"),
            correctIndex = 0,
            patternTag = "Heap",
            difficulty = Difficulty.ADVANCED,
            explanation = "Most nodes sit near the leaves and sift down only a little; the series sums to O(n). Inserting one at a time is O(n log n).",
            linkedTopicId = "heap",
            linkedTopicLabel = "Heap (Min / Max)",
        ),
        QuizQuestion(
            prompt = "To keep the k largest elements of a stream, use:",
            options = listOf("A min-heap of size k", "A max-heap of size k", "A sorted list of everything", "A hash set"),
            correctIndex = 0,
            patternTag = "Top-K",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The root of a min-heap is the weakest survivor, so it is exactly what to evict when a better candidate arrives.",
            linkedTopicId = "top_k_elements",
            linkedTopicLabel = "Top-K Elements",
        ),
        QuizQuestion(
            prompt = "Peeking at the minimum of a min-heap costs:",
            options = listOf("O(1)", "O(log n)", "O(n)", "O(n log n)"),
            correctIndex = 0,
            patternTag = "Heap",
            difficulty = Difficulty.BEGINNER,
            explanation = "The heap property puts the minimum at the root. Removing it is O(log n) because of the sift-down that follows.",
            linkedTopicId = "heap",
            linkedTopicLabel = "Heap (Min / Max)",
        ),
        QuizQuestion(
            prompt = "A Bloom filter's defining trade-off is:",
            options = listOf(
                "False positives are possible, false negatives are not",
                "It stores the keys but slowly",
                "It never errs but uses more memory",
                "It only works on integers",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.ADVANCED,
            explanation = "It keeps bits, not keys, so \"maybe present\" can be wrong while \"definitely absent\" is always right — ideal as a cheap pre-filter.",
            linkedTopicId = "bloom_filter",
            linkedTopicLabel = "Bloom Filter",
        ),
    ),
)

internal val dpGreedyQuiz = Quiz(
    id = "dp_greedy_quiz",
    title = "DP & Greedy",
    description = "States, recurrences and when greedy is provably safe.",
    questions = listOf(
        QuizQuestion(
            prompt = "Dynamic programming applies when a problem has:",
            options = listOf(
                "Optimal substructure and overlapping subproblems",
                "Only optimal substructure",
                "Sorted input",
                "No recursion",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.BEGINNER,
            explanation = "Without overlap, plain divide and conquer is enough — memoisation would store entries never read twice.",
            linkedTopicId = "fibonacci_dp",
            linkedTopicLabel = "Fibonacci (Dynamic Programming)",
        ),
        QuizQuestion(
            prompt = "Greedy coin change fails on coins [1, 3, 4] with amount 6 because:",
            options = listOf(
                "Taking 4 first forces 4+1+1, while 3+3 uses fewer coins",
                "6 cannot be made at all",
                "The coins are unsorted",
                "It only fails with negative amounts",
            ),
            correctIndex = 0,
            patternTag = "Greedy",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The locally biggest coin is not globally safe here. Canonical systems like [1, 5, 10, 25] happen to be greedy-safe; arbitrary ones are not.",
            linkedTopicId = "coin_change",
            linkedTopicLabel = "Coin Change",
        ),
        QuizQuestion(
            prompt = "0/1 Knapsack differs from Fractional Knapsack in that:",
            options = listOf(
                "Items cannot be split, so greedy by value/weight is not optimal",
                "It has no capacity limit",
                "It allows negative weights",
                "It is solved in O(1)",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Splitting is what makes the greedy exchange argument valid. Whole items require a DP table over capacities.",
            linkedTopicId = "knapsack_01",
            linkedTopicLabel = "0/1 Knapsack",
        ),
        QuizQuestion(
            prompt = "In interval scheduling, the greedy choice that maximises how many intervals fit is:",
            options = listOf("Pick the interval that finishes earliest", "Pick the shortest interval", "Pick the one starting earliest", "Pick the one overlapping fewest others"),
            correctIndex = 0,
            patternTag = "Greedy",
            difficulty = Difficulty.ADVANCED,
            explanation = "Earliest finish leaves the most room for what follows, provable by an exchange argument. Earliest start is the classic wrong answer.",
            linkedTopicId = "job_sequencing",
            linkedTopicLabel = "Job Sequencing with Deadlines",
        ),
        QuizQuestion(
            prompt = "Memoised recursion (top-down) versus tabulation (bottom-up):",
            options = listOf(
                "Same complexity; top-down only computes reachable states, bottom-up avoids stack depth",
                "Top-down is always faster",
                "Bottom-up cannot handle 2D states",
                "They solve different problem classes",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Choose top-down for sparse state spaces, bottom-up when deep recursion risks overflow or rolling arrays can cut space.",
            linkedTopicId = "fibonacci_dp",
            linkedTopicLabel = "Fibonacci (Dynamic Programming)",
        ),
        QuizQuestion(
            prompt = "Space in a 2D DP can often drop to O(min(m, n)) when:",
            options = listOf(
                "Each cell depends only on the previous row (or column)",
                "The table holds only zeroes and ones",
                "The recurrence is linear",
                "The inputs are sorted",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.ADVANCED,
            explanation = "With a one-row dependency you can roll a single array forward — the trick used in LCS, edit distance and unique paths.",
            linkedTopicId = "longest_common_subsequence",
            linkedTopicLabel = "Longest Common Subsequence",
        ),
        QuizQuestion(
            prompt = "To merge every overlapping interval in a list of [start, end] pairs, sort by start and then:",
            options = listOf(
                "Extend the last kept interval's end whenever the next start is ≤ that end",
                "Drop any interval whose start is inside the previous one",
                "Sort by end instead and keep the earliest finisher",
                "Compare every interval against every other",
            ),
            correctIndex = 0,
            patternTag = "Merge Intervals",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Sorting by start means anything overlapping the current interval comes next, so one pass suffices: extend the end on overlap, otherwise start a new interval. O(n log n) for the sort, O(n) after. Sorting by end is the *scheduling* greedy — it maximises how many intervals fit, a different question.",
            linkedTopicId = "merge_intervals_pattern",
            linkedTopicLabel = "Merge Intervals",
        ),
    ),
)

internal val complexityQuiz = Quiz(
    id = "complexity_quiz",
    title = "Complexity Analysis",
    description = "Big-O, amortized cost and space trade-offs.",
    questions = listOf(
        QuizQuestion(
            prompt = "O(2n² + 100n + 5000) simplifies to:",
            options = listOf("O(n²)", "O(2n²)", "O(n² + n)", "O(5000)"),
            correctIndex = 0,
            patternTag = "Big-O",
            difficulty = Difficulty.BEGINNER,
            explanation = "Big-O drops constants and lower-order terms — they stop mattering as n grows.",
            linkedTopicId = "complexity_class_comparison",
            linkedTopicLabel = "Complexity Class Comparison",
        ),
        QuizQuestion(
            prompt = "Two nested loops both running to n, where the inner starts at the outer's index, cost:",
            options = listOf("O(n²) — roughly n²/2 iterations", "O(n)", "O(n log n)", "O(log n)"),
            correctIndex = 0,
            patternTag = "Big-O",
            difficulty = Difficulty.BEGINNER,
            explanation = "n + (n-1) + … + 1 = n(n+1)/2, and the constant ½ drops out.",
            linkedTopicId = "operation_counter",
            linkedTopicLabel = "Operation Counter",
        ),
        QuizQuestion(
            prompt = "Amortized O(1) means:",
            options = listOf(
                "Averaged over a sequence of operations, each costs constant time",
                "Every single operation is constant time",
                "The best case is constant",
                "It is constant only for small n",
            ),
            correctIndex = 0,
            patternTag = "Amortized Analysis",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Individual operations may be expensive — like a resize copy — as long as their cost is paid for by many cheap ones.",
            linkedTopicId = "amortized_analysis",
            linkedTopicLabel = "Amortized Analysis",
        ),
        QuizQuestion(
            prompt = "A recurrence T(n) = 2T(n/2) + O(n) solves to:",
            options = listOf("O(n log n)", "O(n)", "O(n²)", "O(log n)"),
            correctIndex = 0,
            patternTag = "Divide & Conquer",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "log n levels of O(n) merging — the merge sort recurrence, and the Master Theorem's balanced case.",
            linkedTopicId = "master_theorem",
            linkedTopicLabel = "Master Theorem",
        ),
        QuizQuestion(
            prompt = "Which is the space complexity of recursive DFS on a balanced binary tree?",
            options = listOf("O(log n) for the call stack", "O(1)", "O(n)", "O(n log n)"),
            correctIndex = 0,
            patternTag = "Space Complexity",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Only the current root-to-node path is live. A degenerate tree pushes this to O(n).",
            linkedTopicId = "space_time_tradeoffs",
            linkedTopicLabel = "Space-Time Tradeoffs",
        ),
        QuizQuestion(
            prompt = "Worst case is a stronger guarantee than average case because:",
            options = listOf(
                "It holds for every input, with no distributional assumption",
                "It is always tighter",
                "It ignores constants",
                "It applies only to sorted input",
            ),
            correctIndex = 0,
            patternTag = "Case Analysis",
            difficulty = Difficulty.ADVANCED,
            explanation = "Average case assumes an input distribution that adversarial or real-world data may violate — quicksort's O(n²) worst case is the classic example.",
            linkedTopicId = "worst_case",
            linkedTopicLabel = "Worst Case",
        ),
    ),
)
