package com.algora.app.feature.interviewprep.quiz

import com.algora.app.core.data.model.Difficulty

// Second batch of DSA subject quizzes, covering the areas the first batch left out: recursion and
// backtracking, bit manipulation, string matching, and number theory. Same six-question,
// shape as QuizContentTopics.kt, and every question links back to the topic that
// explains it.

internal val recursionBacktrackingQuiz = Quiz(
    id = "recursion_backtracking_quiz",
    title = "Recursion & Backtracking",
    description = "Base cases, call-stack cost, pruning and un-choosing.",
    questions = listOf(
        QuizQuestion(
            prompt = "A recursion that never reaches its base case fails with:",
            options = listOf(
                "A stack overflow — each call keeps a frame alive",
                "A heap overflow",
                "A wrong answer, but no crash",
                "An infinite loop with constant memory",
            ),
            correctIndex = 0,
            patternTag = "Recursion",
            difficulty = Difficulty.BEGINNER,
            explanation = "Every pending call holds a stack frame with its locals and return address. Without a base case the frames accumulate until the stack is exhausted.",
            linkedTopicId = "factorial",
            linkedTopicLabel = "Factorial",
        ),
        QuizQuestion(
            prompt = "Naive recursive Fibonacci runs in exponential time because:",
            options = listOf(
                "The same subproblems are recomputed across separate branches",
                "Each call allocates a new array",
                "Addition on large integers is slow",
                "The recursion depth is exponential",
            ),
            correctIndex = 0,
            patternTag = "Overlapping Subproblems",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "fib(n-2) is recomputed inside both fib(n-1) and the direct call, so the tree has ~2ⁿ nodes while the depth is only n. Memoising collapses it to O(n).",
            linkedTopicId = "fibonacci_recursive",
            linkedTopicLabel = "Recursive Fibonacci",
        ),
        QuizQuestion(
            prompt = "The step that makes backtracking different from plain recursion is:",
            options = listOf(
                "Undoing the choice after exploring it, so the state is clean for the next branch",
                "Caching every partial solution",
                "Sorting the candidates first",
                "Using a queue instead of the call stack",
            ),
            correctIndex = 0,
            patternTag = "Backtracking",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Choose, explore, un-choose. Mutating shared state without the un-choose step leaks a branch's decisions into its siblings.",
            linkedTopicId = "backtracking_pattern",
            linkedTopicLabel = "Backtracking Pattern",
        ),
        QuizQuestion(
            prompt = "In N-Queens, checking a candidate square against columns and both diagonals before recursing is:",
            options = listOf(
                "Pruning — it cuts an entire subtree that cannot contain a solution",
                "Memoisation",
                "A greedy choice",
                "Only a constant-factor speedup",
            ),
            correctIndex = 0,
            patternTag = "Pruning",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Rejecting a placement early removes every arrangement built on top of it. Pruning is what makes backtracking usable on search spaces that are exponential on paper.",
            linkedTopicId = "n_queens",
            linkedTopicLabel = "N-Queens",
        ),
        QuizQuestion(
            prompt = "Generating all subsets of n distinct elements costs at least:",
            options = listOf("O(2ⁿ) — one per subset", "O(n²)", "O(n log n)", "O(n!)"),
            correctIndex = 0,
            patternTag = "Subsets",
            difficulty = Difficulty.BEGINNER,
            explanation = "Each element is in or out, so there are 2ⁿ subsets. Any algorithm that must emit them all is bounded below by the output size.",
            linkedTopicId = "subsets_pattern",
            linkedTopicLabel = "Subsets & Combinations",
        ),
        QuizQuestion(
            prompt = "When generating permutations of an array containing duplicates, the standard fix is to:",
            options = listOf(
                "Sort first, then skip a candidate equal to its predecessor at the same depth",
                "Store every permutation in a set at the end",
                "Recurse only on the distinct prefix",
                "Swap in reverse order",
            ),
            correctIndex = 0,
            patternTag = "Permutations",
            difficulty = Difficulty.ADVANCED,
            explanation = "Sorting groups equal values together; skipping a repeat at the same recursion level emits each distinct arrangement once. De-duplicating at the end works but wastes exponential effort first.",
            linkedTopicId = "permutation_generation",
            linkedTopicLabel = "Permutation Generation",
        ),
    ),
)

internal val bitManipulationQuiz = Quiz(
    id = "bit_manipulation_quiz",
    title = "Bit Manipulation",
    description = "Masks, XOR pairing, low-bit tricks and bitmask states.",
    questions = listOf(
        QuizQuestion(
            prompt = "x & (x - 1) evaluates to:",
            options = listOf(
                "x with its lowest set bit cleared",
                "x with its lowest set bit isolated",
                "x with every bit flipped",
                "x doubled",
            ),
            correctIndex = 0,
            patternTag = "Low-bit Tricks",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Subtracting 1 flips the lowest set bit to 0 and everything below it to 1; the AND then clears that bit. Looping on it counts set bits in O(popcount) steps.",
            linkedTopicId = "count_set_bits",
            linkedTopicLabel = "Count Set Bits",
        ),
        QuizQuestion(
            prompt = "In an array where every value appears twice except one, XOR-ing all values yields:",
            options = listOf(
                "The unique value — pairs cancel to 0",
                "Zero",
                "The sum of the duplicates",
                "The largest value",
            ),
            correctIndex = 0,
            patternTag = "XOR Tricks",
            difficulty = Difficulty.BEGINNER,
            explanation = "XOR is associative and commutative with a ^ a = 0 and a ^ 0 = a, so every pair vanishes and only the lone value survives. O(n) time, O(1) space.",
            linkedTopicId = "xor_tricks",
            linkedTopicLabel = "XOR Tricks",
        ),
        QuizQuestion(
            prompt = "To test whether bit i of x is set:",
            options = listOf("(x >> i) & 1", "x & i", "x | (1 << i)", "x ^ (1 << i)"),
            correctIndex = 0,
            patternTag = "Bit Basics",
            difficulty = Difficulty.BEGINNER,
            explanation = "Shift the bit down to position 0 and mask it. `x | (1 << i)` sets the bit and `x ^ (1 << i)` toggles it — neither reports its current value.",
            linkedTopicId = "bit_basics",
            linkedTopicLabel = "Bit Basics",
        ),
        QuizQuestion(
            prompt = "x & -x isolates the lowest set bit because two's complement negation:",
            options = listOf(
                "Inverts every bit then adds 1, leaving the lowest set bit and everything above it inverted",
                "Only changes the sign bit",
                "Shifts the value right by one",
                "Is identical to bitwise NOT",
            ),
            correctIndex = 0,
            patternTag = "Low-bit Tricks",
            difficulty = Difficulty.ADVANCED,
            explanation = "-x = ~x + 1. The carry from the +1 stops at the lowest set bit, so x and -x agree on exactly that bit — the AND leaves it alone and zeroes the rest. Fenwick trees use it to walk parents.",
            linkedTopicId = "fenwick_tree",
            linkedTopicLabel = "Fenwick Tree",
        ),
        QuizQuestion(
            prompt = "A bitmask DP over n items typically has how many states?",
            options = listOf("2ⁿ — one per subset of items", "n²", "n log n", "n!"),
            correctIndex = 0,
            patternTag = "Bitmask DP",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The mask encodes which items are already used, so the state space is every subset. That is why bitmask DP is practical only for roughly n ≤ 20.",
            linkedTopicId = "bitmask_dp",
            linkedTopicLabel = "Bitmask DP",
        ),
        QuizQuestion(
            prompt = "Which check tells you a positive integer x is a power of two?",
            options = listOf(
                "(x & (x - 1)) == 0",
                "(x % 2) == 0",
                "(x ^ (x - 1)) == 0",
                "(x | (x - 1)) == x",
            ),
            correctIndex = 0,
            patternTag = "Bit Basics",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A power of two has exactly one set bit, and clearing the lowest set bit then leaves zero. `x % 2 == 0` only tests evenness — 6 passes it and is not a power of two.",
            linkedTopicId = "subsets_bitmask",
            linkedTopicLabel = "Subsets via Bitmask",
        ),
    ),
)

internal val stringMatchingQuiz = Quiz(
    id = "string_matching_quiz",
    title = "String Matching",
    description = "Prefix functions, rolling hashes, palindromes and tries.",
    questions = listOf(
        QuizQuestion(
            prompt = "Naive substring search of a pattern of length m in text of length n is worst-case:",
            options = listOf("O(n · m)", "O(n + m)", "O(n log m)", "O(m log n)"),
            correctIndex = 0,
            patternTag = "String Search",
            difficulty = Difficulty.BEGINNER,
            explanation = "Every one of ~n alignments can compare up to m characters before failing — \"aaaa…ab\" in \"aaaa…a\" hits exactly that. Smarter algorithms reuse the failed comparisons instead of discarding them.",
            linkedTopicId = "naive_string_search",
            linkedTopicLabel = "Naive String Search",
        ),
        QuizQuestion(
            prompt = "KMP's prefix table stores, for each position, the length of:",
            options = listOf(
                "The longest proper prefix that is also a suffix",
                "The longest repeated character run",
                "The remaining pattern",
                "The hash of the prefix",
            ),
            correctIndex = 0,
            patternTag = "KMP",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "That length says how far the pattern can slide on a mismatch without re-checking characters already matched, giving O(n + m) overall with no backtracking in the text.",
            linkedTopicId = "kmp",
            linkedTopicLabel = "KMP Algorithm",
        ),
        QuizQuestion(
            prompt = "Rabin-Karp degrades to O(n · m) when:",
            options = listOf(
                "Hash collisions are frequent, forcing a character-by-character verify each time",
                "The pattern is short",
                "The alphabet is large",
                "The text is already sorted",
            ),
            correctIndex = 0,
            patternTag = "Rabin-Karp",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The rolling hash makes each window O(1), but equal hashes must still be verified. A bad modulus or an adversarial text turns every window into a full comparison.",
            linkedTopicId = "rabin_karp",
            linkedTopicLabel = "Rabin-Karp",
        ),
        QuizQuestion(
            prompt = "Manacher's algorithm finds the longest palindromic substring in:",
            options = listOf(
                "O(n), by reusing mirrored radii inside the current palindrome",
                "O(n log n), via binary search",
                "O(n²), same as expand-around-center",
                "O(n · m)",
            ),
            correctIndex = 0,
            patternTag = "Palindromes",
            difficulty = Difficulty.ADVANCED,
            explanation = "Each center's radius starts from its mirror's already-known radius, so the right boundary only moves forward — total work is linear. Expand-around-center is the O(n²) fallback.",
            linkedTopicId = "manacher",
            linkedTopicLabel = "Manacher's Algorithm",
        ),
        QuizQuestion(
            prompt = "A trie holding k words of average length L answers a prefix query in:",
            options = listOf(
                "O(prefix length) — independent of k",
                "O(k)",
                "O(k · L)",
                "O(log k)",
            ),
            correctIndex = 0,
            patternTag = "Trie",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Lookup walks one node per prefix character, so the dictionary size does not enter the cost. The price is memory: a node per distinct prefix.",
            linkedTopicId = "trie",
            linkedTopicLabel = "Trie",
        ),
        QuizQuestion(
            prompt = "To search a text for many patterns at once in one pass, use:",
            options = listOf(
                "Aho-Corasick — a trie of all patterns plus failure links",
                "KMP, run once per pattern",
                "Binary search over the text",
                "A suffix array of each pattern",
            ),
            correctIndex = 0,
            patternTag = "Multi-pattern Search",
            difficulty = Difficulty.ADVANCED,
            explanation = "Failure links generalise KMP's prefix table to a whole trie, so one scan reports every occurrence of every pattern in O(n + total pattern length + matches).",
            linkedTopicId = "aho_corasick",
            linkedTopicLabel = "Aho-Corasick",
        ),
    ),
)

internal val mathNumberTheoryQuiz = Quiz(
    id = "math_number_theory_quiz",
    title = "Math & Number Theory",
    description = "GCD, modular arithmetic, fast power and primes.",
    questions = listOf(
        QuizQuestion(
            prompt = "The Euclidean algorithm computes gcd(a, b) in:",
            options = listOf(
                "O(log min(a, b)) — the remainder at least halves every two steps",
                "O(min(a, b))",
                "O(√a)",
                "O(a · b)",
            ),
            correctIndex = 0,
            patternTag = "GCD",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "gcd(a, b) = gcd(b, a mod b), and a mod b < a/2 whenever b ≤ a/2 — otherwise the next step drops it. Either way two iterations halve the pair.",
            linkedTopicId = "euclid_gcd",
            linkedTopicLabel = "Euclidean GCD",
        ),
        QuizQuestion(
            prompt = "Fast exponentiation computes aⁿ using about how many multiplications?",
            options = listOf("log₂ n", "n", "√n", "n log n"),
            correctIndex = 0,
            patternTag = "Fast Power",
            difficulty = Difficulty.BEGINNER,
            explanation = "Square-and-multiply halves the exponent each step: a^n = (a^(n/2))² for even n, times one extra a for odd n. One squaring per bit of n.",
            linkedTopicId = "fast_power",
            linkedTopicLabel = "Fast Exponentiation",
        ),
        QuizQuestion(
            prompt = "Products are taken modulo a prime at every step of a computation mainly to:",
            options = listOf(
                "Keep intermediate values inside machine word range and avoid overflow",
                "Make the result larger",
                "Speed up addition",
                "Guarantee the result is prime",
            ),
            correctIndex = 0,
            patternTag = "Modular Arithmetic",
            difficulty = Difficulty.BEGINNER,
            explanation = "Modular reduction distributes over + and ×, so reducing early gives the same answer while bounding every intermediate below the modulus.",
            linkedTopicId = "modular_arithmetic",
            linkedTopicLabel = "Modular Arithmetic",
        ),
        QuizQuestion(
            prompt = "The Sieve of Eratosthenes marks all primes below n in:",
            options = listOf("O(n log log n)", "O(n)", "O(n log n)", "O(n √n)"),
            correctIndex = 0,
            patternTag = "Primes",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Each prime p crosses out n/p entries, and the sum of 1/p over primes below n grows like log log n. Trial division per number would be O(n √n).",
            linkedTopicId = "sieve_of_eratosthenes",
            linkedTopicLabel = "Sieve of Eratosthenes",
        ),
        QuizQuestion(
            prompt = "With prime modulus p, the modular inverse of a is a^(p-2) mod p because of:",
            options = listOf(
                "Fermat's little theorem — a^(p-1) ≡ 1 (mod p)",
                "The Chinese remainder theorem",
                "The binomial theorem",
                "Wilson's theorem",
            ),
            correctIndex = 0,
            patternTag = "Modular Inverse",
            difficulty = Difficulty.ADVANCED,
            explanation = "From a^(p-1) ≡ 1, multiplying both sides by a⁻¹ gives a⁻¹ ≡ a^(p-2). Combined with fast power that is an O(log p) inverse — the usual trick for division under a modulus.",
            linkedTopicId = "fermats_little_theorem",
            linkedTopicLabel = "Fermat's Little Theorem",
        ),
        QuizQuestion(
            prompt = "Karatsuba multiplies two n-digit numbers in O(n^1.585) by:",
            options = listOf(
                "Replacing four half-size multiplications with three plus additions",
                "Using a lookup table of digit products",
                "Converting both numbers to binary first",
                "Multiplying digit by digit in parallel",
            ),
            correctIndex = 0,
            patternTag = "Divide & Conquer",
            difficulty = Difficulty.ADVANCED,
            explanation = "T(n) = 3T(n/2) + O(n) solves to n^log₂3 ≈ n^1.585. The saved multiplication is recovered from the other two products with cheap additions.",
            linkedTopicId = "karatsubas_algorithm",
            linkedTopicLabel = "Karatsuba's Algorithm",
        ),
    ),
)
