package com.algora.app.feature.interviewprep.quiz

import com.algora.app.core.data.model.Difficulty
import com.algora.app.core.data.model.Figure
import com.algora.app.core.data.model.FigureEdge
import com.algora.app.core.data.model.FigureGraphNode
import com.algora.app.core.data.model.FigurePoint
import com.algora.app.core.data.model.FigurePointer
import com.algora.app.core.data.model.FigureSeries
import com.algora.app.core.data.model.FigureShape
import com.algora.app.core.data.model.FigureSpan
import com.algora.app.core.data.model.FigureStack

internal val timedMockInterview = Quiz(
    id = "timed_mock_interview",
    title = "Timed Mock Interview",
    description = "Mixed-pattern questions across the core interview toolkit. Pick the best approach for each.",
    questions = listOf(
        QuizQuestion(
            prompt = "Longest substring without repeating characters — the optimal approach is:",
            options = listOf(
                "A sliding window with a last-seen index map",
                "Sort the string, then scan for duplicates",
                "Check every substring for uniqueness",
                "Binary search on the answer length",
            ),
            correctIndex = 0,
            patternTag = "Sliding Window",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Expand the window's right edge; when a repeat appears, jump the left edge past the previous occurrence. O(n) time, O(min(n, alphabet)) space.",
            linkedTopicId = "sliding_window",
            linkedTopicLabel = "Sliding Window",
        ),
        QuizQuestion(
            prompt = "In a sorted array, find two numbers summing to a target in O(n) time and O(1) space:",
            options = listOf(
                "Two pointers, one from each end",
                "A hash map of complements",
                "Two nested loops",
                "Binary search for each element",
            ),
            correctIndex = 0,
            patternTag = "Two Pointer",
            difficulty = Difficulty.BEGINNER,
            explanation = "Move the left pointer right when the sum is too small and the right pointer left when it's too big. The hash-map answer is O(n) time but O(n) space.",
            linkedTopicId = "two_pointer",
            linkedTopicLabel = "Two Pointer Technique",
        ),
        QuizQuestion(
            prompt = "Worst-case comparisons to binary-search a sorted array of ~1,000,000 elements:",
            options = listOf("About 20", "About 1,000", "About 500,000", "About 1,000,000"),
            correctIndex = 0,
            patternTag = "Binary Search",
            difficulty = Difficulty.BEGINNER,
            explanation = "Binary search is O(log₂ n). log₂(1,000,000) ≈ 20, so at most ~20 comparisons.",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
        ),
        QuizQuestion(
            prompt = "Maximum contiguous subarray sum in a single O(n) pass:",
            options = listOf(
                "Kadane's algorithm",
                "Sort then take the suffix",
                "All-pairs prefix sums",
                "Depth-first search",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Kadane keeps a running best-ending-here sum, resetting when it drops below zero. O(n) time, O(1) space.",
            linkedTopicId = "kadanes_algorithm",
            linkedTopicLabel = "Kadane's Algorithm",
        ),
        QuizQuestion(
            prompt = "Detect a cycle in a linked list using O(1) extra space:",
            options = listOf(
                "Floyd's fast & slow pointers",
                "Store every visited node in a hash set",
                "Reverse the list and compare",
                "Sort the node addresses",
            ),
            correctIndex = 0,
            patternTag = "Fast & Slow Pointers",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A slow pointer moving one step and a fast pointer moving two will meet inside any cycle. The hash-set approach works but costs O(n) space.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Fewest coins to make an amount with unlimited denominations:",
            options = listOf(
                "Dynamic programming (coin change)",
                "Always take the largest coin (greedy)",
                "Two pointers over sorted coins",
                "Breadth-first search only",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.ADVANCED,
            explanation = "Greedy fails for coin systems like {1, 3, 4} making 6. DP over subamounts guarantees the optimum in O(amount × coins).",
            linkedTopicId = "coin_change",
            linkedTopicLabel = "Coin Change",
        ),
    ),
)

// Id stays faang_set: attempt history is keyed by it, and the acronym named five specific
// companies while the set tags none of them.
internal val bigTechSet = Quiz(
    id = "faang_set",
    title = "Big Tech Set",
    description = "Big-tech-style favourites, then real problems at scale — maps, feeds, sync, sharding. Pick the technique for each.",
    questions = listOf(
        QuizQuestion(
            prompt = "Clone an undirected graph given a node reference:",
            options = listOf(
                "BFS/DFS with an original→copy visited map",
                "Topological sort then rebuild",
                "Union-Find over the edges",
                "Dijkstra from the given node",
            ),
            correctIndex = 0,
            patternTag = "Graph Traversal",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Traverse once, creating a copy on first visit and wiring neighbours through the visited map to avoid infinite loops on cycles.",
            linkedTopicId = "bfs",
            linkedTopicLabel = "Breadth-First Search",
        ),
        QuizQuestion(
            prompt = "Minimum window substring of S that contains all characters of T:",
            options = listOf(
                "Sliding window with a need/have count",
                "Sort both strings and diff them",
                "Build a trie of T",
                "Binary search the window size",
            ),
            correctIndex = 0,
            patternTag = "Sliding Window",
            difficulty = Difficulty.ADVANCED,
            explanation = "Grow the window until it covers T, then shrink from the left while it still covers T, tracking the smallest. O(|S| + |T|).",
            linkedTopicId = "sliding_window",
            linkedTopicLabel = "Sliding Window",
        ),
        QuizQuestion(
            prompt = "Return the K points closest to the origin:",
            options = listOf(
                "A size-K max-heap (or Quickselect)",
                "Fully sort all points every time",
                "Breadth-first search",
                "Dynamic programming",
            ),
            correctIndex = 0,
            patternTag = "Top-K / Heap",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A size-K max-heap gives O(n log K); Quickselect gives O(n) average. A full sort is O(n log n) — more work than needed.",
            linkedTopicId = "top_k_elements",
            linkedTopicLabel = "Top-K Elements",
        ),
        QuizQuestion(
            prompt = "Search for a target in a rotated sorted array in O(log n):",
            options = listOf(
                "Modified binary search on the sorted half",
                "Linear scan from the pivot",
                "Hash every element first",
                "Merge sort then binary search",
            ),
            correctIndex = 0,
            patternTag = "Binary Search",
            difficulty = Difficulty.ADVANCED,
            explanation = "At each step one half is sorted; decide whether the target lies in it and recurse there, keeping O(log n).",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
        ),
        QuizQuestion(
            prompt = "Container With Most Water — maximum area between two lines:",
            options = listOf(
                "Two pointers moving the shorter wall inward",
                "Check every pair of lines",
                "Sort the heights first",
                "A segment tree of heights",
            ),
            correctIndex = 0,
            patternTag = "Two Pointer",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Start at both ends; the area is bounded by the shorter wall, so moving it inward is the only way the area can grow. O(n).",
            linkedTopicId = "two_pointer",
            linkedTopicLabel = "Two Pointer Technique",
        ),
        QuizQuestion(
            prompt = "Scenario: a photo app gets millions of uploads a day, and exact duplicates of stored photos should not be saved twice.",
            options = listOf(
                "Hash each file's bytes (e.g. SHA-256) and look the digest up in a hash set",
                "Compare each new photo byte by byte with every stored photo",
                "Compare file names",
                "Sort all photos by size every night and compare neighbours",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Hashing",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: digest = sha256(bytes); if digest is already stored, point the upload at the existing file, otherwise store it and the digest. One hash per upload and an O(1) average lookup, whatever the library size. File names say nothing about content. Near-duplicates (resized, re-encoded) need a perceptual hash instead — worth mentioning as a follow-up.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Scenario: a maps app needs the fastest driving route between two intersections. Roads have travel times.",
            options = listOf(
                "Dijkstra on travel time — in practice A* with a straight-line-distance heuristic",
                "BFS, counting roads instead of time",
                "DFS, returning the first route that reaches the destination",
                "Floyd-Warshall over the whole country on every request",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Shortest Path",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: intersections are nodes and roads are weighted edges, so it is weighted shortest path. Travel times are never negative, so Dijkstra is correct; A* expands far fewer nodes by preferring ones closer to the goal (distance ÷ top speed never overestimates). BFS minimises the number of roads, not time. Floyd-Warshall is O(V³) on millions of nodes.",
            linkedTopicId = "dijkstras_algorithm",
            linkedTopicLabel = "Dijkstra's Algorithm",
            figure = Figure(
                caption = "Intersections, minutes per road",
                shape = FigureShape.Graph(
                    nodes = listOf(
                        FigureGraphNode("Home", 0.1f, 0.5f),
                        FigureGraphNode("P", 0.4f, 0.16f),
                        FigureGraphNode("Q", 0.4f, 0.84f),
                        FigureGraphNode("R", 0.68f, 0.5f),
                        FigureGraphNode("Work", 0.92f, 0.5f),
                    ),
                    edges = listOf(
                        FigureEdge(0, 1, "6"),
                        FigureEdge(0, 2, "2"),
                        FigureEdge(2, 1, "3"),
                        FigureEdge(1, 3, "2"),
                        FigureEdge(2, 3, "8"),
                        FigureEdge(3, 4, "3"),
                        FigureEdge(1, 4, "9"),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: suggest \"People you may know\" — people the user is not friends with, ranked by mutual friends.",
            options = listOf(
                "Go two hops out from the user, count how often each second-hop person appears, then take the top k",
                "Suggest random users",
                "Run a DFS over the whole social graph",
                "Compute all-pairs shortest paths",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Graphs",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: for each friend f, for each friend g of f: if g is not the user and not already a friend, count[g]++. count[g] is exactly the number of mutual friends. Then a size-k heap picks the best. Only two levels are touched, which is the whole trick — the full graph has billions of edges.",
            linkedTopicId = "bfs",
            linkedTopicLabel = "Breadth-First Search (BFS)",
            figure = Figure(
                caption = "Friendships around You",
                shape = FigureShape.Graph(
                    nodes = listOf(
                        FigureGraphNode("You", 0.1f, 0.5f),
                        FigureGraphNode("Ann", 0.4f, 0.16f),
                        FigureGraphNode("Bo", 0.4f, 0.84f),
                        FigureGraphNode("Cy", 0.72f, 0.16f),
                        FigureGraphNode("Di", 0.72f, 0.84f),
                        FigureGraphNode("Ed", 0.94f, 0.5f),
                    ),
                    edges = listOf(
                        FigureEdge(0, 1),
                        FigureEdge(0, 2),
                        FigureEdge(1, 3),
                        FigureEdge(2, 3),
                        FigureEdge(2, 4),
                        FigureEdge(3, 5),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: a ride-hailing app must find the nearest available drivers to a rider, among millions of moving drivers.",
            options = listOf(
                "A spatial index — geohash grid cells or a k-d tree — searching the rider's cell and its neighbours",
                "Scan every driver and compute each distance",
                "Sort drivers by latitude only",
                "A hash map keyed by driver id",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Spatial Index",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: bucket drivers by grid cell (geohash) and update a driver's cell as they move. For a rider, check their cell and the 8 around it, widening the ring if too few drivers are found. That touches a few hundred drivers, not millions. Sorting by latitude alone ignores longitude; an id map cannot answer anything about location.",
            linkedTopicId = "kd_tree",
            linkedTopicLabel = "K-D Tree / Quad Tree / Octree",
            figure = Figure(
                caption = "City grid: R = rider, D = free driver",
                shape = FigureShape.Grid(
                    rows = listOf(
                        listOf("·", "D", "·", "·", "·", "·"),
                        listOf("·", "·", "·", "·", "D", "·"),
                        listOf("D", "·", "R", "·", "·", "·"),
                        listOf("·", "·", "·", "·", "·", "D"),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: a cloud drive syncs a 2 GB file after a small edit near its start. How do you upload only what changed?",
            options = listOf(
                "Split it into content-defined chunks with a rolling hash, hash each chunk, and upload only unknown hashes",
                "Upload the whole file every time",
                "Split into fixed 4 MB blocks and compare their hashes",
                "Compare the file size and modification time",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Rolling Hash",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: slide a rolling hash over the bytes and cut a chunk wherever it matches a pattern (e.g. its low 13 bits are 0). Boundaries follow the content, so an insertion only changes the chunks around it. With fixed blocks, one inserted byte shifts every later block and all of them look changed. Size and time only say that something changed, not what.",
            linkedTopicId = "rolling_hash_pattern",
            linkedTopicLabel = "Rolling Hash",
        ),
        QuizQuestion(
            prompt = "Scenario: a spreadsheet app must stop the user creating a circular reference, such as A1 = B1 + 1 and B1 = A1 × 2.",
            options = listOf(
                "DFS over formula references with three states (unvisited, in progress, done) — reaching an in-progress cell is a cycle",
                "Count how many formulas reference each cell",
                "BFS that keeps no visited state",
                "Union-find over the references",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Cycle Detection",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: cells are nodes and \"A1 uses B1\" is a directed edge. DFS from the edited cell; meeting a cell that is still on the current path means a loop. The same graph in topological order is also the order to recalculate cells in. Union-find ignores direction, so it would flag harmless diamonds (two cells both using a third).",
            linkedTopicId = "graph_coloring_pattern",
            linkedTopicLabel = "Two-Colouring & Cycle Detection",
            figure = Figure(
                caption = "Formula references (A → B: A uses B)",
                shape = FigureShape.Graph(
                    nodes = listOf(
                        FigureGraphNode("A1", 0.15f, 0.25f),
                        FigureGraphNode("B1", 0.55f, 0.25f),
                        FigureGraphNode("C1", 0.15f, 0.8f),
                        FigureGraphNode("D1", 0.85f, 0.7f),
                    ),
                    edges = listOf(
                        FigureEdge(0, 1, directed = true),
                        FigureEdge(1, 0, directed = true),
                        FigureEdge(2, 0, directed = true),
                        FigureEdge(3, 1, directed = true),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: find the 1,000 most frequent search queries of the day from 10 billion log lines spread across 1,000 machines.",
            options = listOf(
                "Shard by hash(query) so every copy of a query is counted on one machine, keep a size-1,000 heap per shard, then merge the heaps",
                "Copy every log to one machine and sort it",
                "Have each machine send only its local top 1,000",
                "Take a random sample of 1,000 queries",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Distributed Top-K",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: map — every machine emits (query, count) from a local hash map; shuffle — route by hash(query), so each query's total lands in exactly one place; reduce — each shard keeps its own top 1,000 in a min-heap; finally merge those candidate lists. Local top lists are wrong: a query that is 1,001st on every machine can be first overall.",
            linkedTopicId = "top_k_pattern",
            linkedTopicLabel = "Top-K Pattern",
        ),
        QuizQuestion(
            prompt = "Scenario: design the code generator for a URL shortener that will store billions of links.",
            options = listOf(
                "Encode a unique increasing id in base 62 — 7 characters give 62⁷ ≈ 3.5 × 10¹² codes",
                "Use the first 7 characters of the long URL",
                "Pick a random 3-letter code",
                "Use the full 32-character MD5 of the URL",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Encoding",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: take an id from a counter (hand out ranges to each server so they never clash), then write it in base 62 with 0-9, a-z and A-Z. Codes are unique by construction, with no collision check. URL prefixes collide constantly (every \"https:/\"); 3 letters give only 17,576 codes; a full MD5 is not short.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Scenario: a cache is spread over n servers. When a server is added, as few keys as possible should move.",
            options = listOf(
                "Consistent hashing on a ring, with virtual nodes — only about 1/n of the keys move",
                "Put each key on server hash(key) % n",
                "Assign keys to servers round-robin",
                "Pick a random server on every request",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Consistent Hashing",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: hash servers and keys onto the same ring; a key belongs to the first server clockwise from it. A new server only takes keys from its neighbour's arc. With hash % n, changing n remaps almost every key and the whole cache goes cold at once. Virtual nodes (many ring points per server) even out the load.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
            figure = Figure(
                caption = "Hash ring: servers S and keys k",
                shape = FigureShape.Graph(
                    nodes = listOf(
                        FigureGraphNode("S1", 0.5f, 0.1f),
                        FigureGraphNode("k1", 0.86f, 0.3f),
                        FigureGraphNode("S2", 0.86f, 0.72f),
                        FigureGraphNode("k2", 0.5f, 0.92f),
                        FigureGraphNode("S3", 0.14f, 0.72f),
                        FigureGraphNode("k3", 0.14f, 0.3f),
                    ),
                    edges = listOf(
                        FigureEdge(0, 1),
                        FigureEdge(1, 2),
                        FigureEdge(2, 3),
                        FigureEdge(3, 4),
                        FigureEdge(4, 5),
                        FigureEdge(5, 0),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: a calendar app finds the first free 30-minute slot for 5 people, given each person's busy intervals.",
            options = listOf(
                "Merge everyone's busy intervals (sorted by start), then return the first gap of at least 30 minutes",
                "Pick a random time and check it",
                "Intersect only the first two people's calendars",
                "Take the first person's earliest free slot",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Merge Intervals",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: put all busy intervals into one list, sort by start, and merge any that overlap. The gaps between merged blocks (and before the first one, from the start of the working day) are when everyone is free, so scan for one ≥ 30 minutes. O(N log N) for N intervals. Checking only two people ignores the other three.",
            linkedTopicId = "merge_intervals_pattern",
            linkedTopicLabel = "Merge Intervals",
            figure = Figure(
                caption = "Busy times, hours after 9:00",
                shape = FigureShape.Timeline(
                    spans = listOf(
                        FigureSpan(0, 1, "Ann"),
                        FigureSpan(0, 2, "Bo"),
                        FigureSpan(2, 3, "Cy"),
                        FigureSpan(3, 4, "Di"),
                        FigureSpan(5, 6, "Ed"),
                    ),
                    axisMax = 8,
                ),
            ),
        ),
    ),
)

internal val startupSet = Quiz(
    id = "startup_set",
    title = "Startup Set",
    description = "Practical questions in the style of fast-moving product companies, then real product problems to solve.",
    questions = listOf(
        QuizQuestion(
            prompt = "Design a cache with O(1) get and put that evicts the least-recently-used entry:",
            options = listOf(
                "Hash map + doubly linked list",
                "A sorted array of timestamps",
                "A single hash map with periodic sweeps",
                "A min-heap keyed by access time",
            ),
            correctIndex = 0,
            patternTag = "Design",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The map gives O(1) lookup; the doubly linked list moves a touched node to the front and drops the tail on eviction, both O(1).",
            linkedTopicId = "lru_cache",
            linkedTopicLabel = "LRU Cache",
        ),
        QuizQuestion(
            prompt = "Deduplicate a stream of events while preserving first-seen order:",
            options = listOf(
                "A hash set for membership plus a list for order",
                "Sort the stream and remove neighbours",
                "Nested loops comparing every pair",
                "A balanced BST of all events",
            ),
            correctIndex = 0,
            patternTag = "Hashing",
            difficulty = Difficulty.BEGINNER,
            explanation = "The set answers 'seen before?' in O(1); append to the ordered list only on first sight. O(n) time.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table",
        ),
        QuizQuestion(
            prompt = "Maintain the Kth-largest value in a growing stream:",
            options = listOf(
                "A size-K min-heap",
                "Re-sort the whole stream on each insert",
                "A size-K max-heap",
                "A hash map of counts",
            ),
            correctIndex = 0,
            patternTag = "Top-K / Heap",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Keep only K elements; the heap root is the Kth largest. Push/pop is O(log K). A max-heap would need K pops to answer.",
            linkedTopicId = "top_k_elements",
            linkedTopicLabel = "Top-K Elements",
        ),
        QuizQuestion(
            prompt = "Serve type-ahead suggestions for every prefix of a search box, over a fixed vocabulary:",
            options = listOf(
                "A trie, with the top completions cached at each node",
                "A hash set of the whole vocabulary",
                "Binary search the sorted vocabulary on each keystroke",
                "A max-heap keyed by word frequency",
            ),
            correctIndex = 0,
            patternTag = "Trie / Prefix Search",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A hash set answers 'is this a word?' but cannot enumerate by prefix. Walking the trie costs O(prefix length), and caching each node's best completions makes the suggestion list a single read.",
            linkedTopicId = "trie",
            linkedTopicLabel = "Trie (Prefix Tree)",
        ),
        QuizQuestion(
            prompt = "Maximum profit from a single buy then sell over a price series:",
            options = listOf(
                "One pass tracking the minimum price so far",
                "Check every buy/sell pair",
                "Sort the prices ascending",
                "Binary search the best day",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.BEGINNER,
            explanation = "Track the lowest price seen and the best profit against it in a single O(n) sweep — the same running-best idea as Kadane.",
            linkedTopicId = "kadanes_algorithm",
            linkedTopicLabel = "Kadane's Algorithm",
        ),
        QuizQuestion(
            prompt = "Scenario: roll a new checkout out to 10% of users. Each user must see the same version on every visit and every device.",
            options = listOf(
                "Hash the user id into buckets 0–99 and enable it when the bucket is below 10",
                "Flip a random coin on every request",
                "Enable it for the first 10% of users by signup date",
                "Store a random flag in each browser session",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Hashing",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: bucket = hash(featureName + userId) % 100; enabled = bucket < 10. It is deterministic, so it is stable across sessions and devices with nothing stored, and ramping to 50% is a config change. Adding the feature name keeps the same users from being first in every experiment. Per-request coins flicker; signup date gives a biased group (only old users).",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Scenario: a referral programme pays per signup. Fraudsters create many accounts that share phones or payment cards. Group the accounts that belong together.",
            options = listOf(
                "Union-find: union any two accounts that share a device, card or phone number; each set is one group",
                "Flag accounts created on the same day",
                "Sort accounts by name and compare neighbours",
                "Run a BFS from each account separately, with no shared state",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Union-Find",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: map each device/card/phone → the first account seen with it; when another account shows the same one, union them. Links chain transitively — A shares a phone with B, B a card with C — so one set can be a whole ring. Near O(1) per link, and it works as events stream in.",
            linkedTopicId = "disjoint_set",
            linkedTopicLabel = "Disjoint Set (Union-Find)",
            figure = Figure(
                caption = "Accounts linked by the phone or card they used",
                shape = FigureShape.Graph(
                    nodes = listOf(
                        FigureGraphNode("acct1", 0.1f, 0.2f),
                        FigureGraphNode("phone", 0.36f, 0.5f),
                        FigureGraphNode("acct2", 0.1f, 0.8f),
                        FigureGraphNode("acct3", 0.62f, 0.2f),
                        FigureGraphNode("card", 0.62f, 0.8f),
                        FigureGraphNode("acct4", 0.9f, 0.5f),
                    ),
                    edges = listOf(
                        FigureEdge(0, 1),
                        FigureEdge(2, 1),
                        FigureEdge(3, 1),
                        FigureEdge(3, 4),
                        FigureEdge(5, 4),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: a feed API pages with OFFSET/LIMIT, and users see duplicates on page 2 when new posts arrive. The fix:",
            options = listOf(
                "Cursor pagination: return posts older than the last seen (timestamp, id) pair",
                "Increase the page size",
                "Load the whole feed into the app once",
                "Cache page 1 for an hour",
            ),
            correctIndex = 0,
            patternTag = "Scenario · API Design",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: page 1 returns a cursor = (createdAt, id) of its last post; page 2 asks for WHERE (createdAt, id) < cursor ORDER BY createdAt DESC, id DESC LIMIT 20. New posts land above the cursor, so nothing shifts. The id breaks timestamp ties. It is also faster: an index seek instead of skipping OFFSET rows.",
        ),
        QuizQuestion(
            prompt = "Scenario: generate 1,000,000 single-use coupon codes that customers cannot guess.",
            options = listOf(
                "Random codes from a large alphabet (e.g. 10 base-32 characters ≈ 10¹⁵ options), checked against a set of issued codes",
                "Sequential numbers such as SAVE000001",
                "The first 4 characters of a hash of the customer's email",
                "One shared code for everyone",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Hashing",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: draw each code from a cryptographically secure random source; re-draw on the rare collision with the issued set. With 10¹⁵ possibilities and 10⁶ codes, a guess succeeds about once in a billion tries — add rate limiting to redemption. Sequential codes can be enumerated; 4 hex characters are only 65,536 options.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Scenario: search-as-you-type sends a request on every keystroke, and the search servers are overloaded. The first fix:",
            options = listOf(
                "Debounce: send only after the user pauses for about 300 ms, and cancel requests that are out of date",
                "Add more servers",
                "Send a request only for every tenth keystroke",
                "Search only after the user presses Enter",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Client Design",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: restart a 300 ms timer on each keystroke and fire only when it expires, so typing \"android\" sends 1 request instead of 7. Cancel the in-flight request when a newer one starts, so a slow old response cannot overwrite a newer one. More servers pay for waste; every-tenth-keystroke searches for half-typed words.",
        ),
        QuizQuestion(
            prompt = "Scenario: an expense-splitting app must settle a group's debts with as few payments as possible.",
            options = listOf(
                "Net each person's balance, then match debtors against creditors — at most n − 1 payments",
                "Replay every original IOU as its own payment",
                "Everyone pays whoever paid the most",
                "Split every bill equally again",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Greedy",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: balance = paid − owed for each person; the IOUs themselves no longer matter. Repeatedly let the biggest debtor pay the biggest creditor min(debt, credit); each payment clears at least one person, so n people need at most n − 1. The true minimum (finding subgroups that net to zero) is NP-hard — worth saying out loud.",
            linkedTopicId = "greedy_exchange_pattern",
            linkedTopicLabel = "Greedy & the Exchange Argument",
            figure = Figure(
                caption = "Who owes whom (after a weekend trip)",
                shape = FigureShape.Graph(
                    nodes = listOf(
                        FigureGraphNode("Ann", 0.12f, 0.2f),
                        FigureGraphNode("Bo", 0.88f, 0.2f),
                        FigureGraphNode("Cy", 0.12f, 0.8f),
                        FigureGraphNode("Di", 0.88f, 0.8f),
                    ),
                    edges = listOf(
                        FigureEdge(0, 1, "$30", directed = true),
                        FigureEdge(2, 1, "$10", directed = true),
                        FigureEdge(1, 3, "$20", directed = true),
                        FigureEdge(2, 3, "$15", directed = true),
                        FigureEdge(0, 2, "$5", directed = true),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: a CSV import of 1,000,000 customer rows has repeated emails in different casing. Keep only the latest row per customer.",
            options = listOf(
                "One pass with a map from normalised email (trimmed, lowercased) to the latest row",
                "Compare every row with every other row",
                "Remove rows whose email appears exactly twice",
                "Sort by email as typed and drop neighbours",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Hashing",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: key = email.trim().lowercase(); if the row is newer than map[key], replace it. O(n) time. Without normalising, \"Ann@x.com\" and \"ann@x.com \" count as different people — sorting the raw values misses them. Pairwise comparison is 10¹² operations.",
            linkedTopicId = "hash_table",
            linkedTopicLabel = "Hash Table / Hash Map",
        ),
        QuizQuestion(
            prompt = "Scenario: the app lets users schedule emails for any future time. Send each one on time.",
            options = listOf(
                "A min-heap (priority queue) keyed by send time; the worker sleeps until the top one is due",
                "Scan every scheduled email once a second",
                "A sorted list with a linear scan on every insert",
                "One sleeping timer thread per email",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Heap",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: insert is O(log n). The worker peeks at the top: if it is due, pop and send; otherwise sleep until its time, or until a new, earlier email arrives. Scanning is O(n) every second; a thread per email collapses at a million. Store the jobs durably too, so a restart does not lose them.",
            linkedTopicId = "heap",
            linkedTopicLabel = "Heap (Min / Max)",
        ),
        QuizQuestion(
            prompt = "Scenario: products are ranked by star rating. A product with a single 5-star review beats one with 4.8 from 2,000 reviews. The fix:",
            options = listOf(
                "Rank by the lower bound of a confidence interval (e.g. the Wilson score), not the raw average",
                "Rank by the raw average rating",
                "Rank by the number of reviews only",
                "Hide every product with fewer than 1,000 reviews",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Statistics",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: the lower bound asks \"how good is this product at least, given how few reviews there are?\" One 5-star review gives a wide interval and a low bound; 2,000 reviews at 4.8 give a tight, high one. Review count alone ignores quality, and a hard cutoff hides every new product.",
        ),
        QuizQuestion(
            prompt = "Scenario: a user edits the same note on a phone and a laptop. The later save silently overwrites the other one. The fix:",
            options = listOf(
                "Optimistic locking: each save sends the version it was based on; reject a stale version and ask to merge",
                "Last write wins",
                "Lock the note for 24 hours after it is opened",
                "Save only from whichever device was used most recently",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Concurrency",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: store a version number with the note. UPDATE … SET body = ?, version = version + 1 WHERE id = ? AND version = ?; if zero rows change, someone else saved first, so show both versions to merge. Nothing is held while the user is typing, unlike a lock, and no edit is lost, unlike last-write-wins.",
        ),
    ),
)

internal val financeTradingSet = Quiz(
    id = "finance_trading_set",
    title = "Finance / Trading Set",
    description = "Latency- and math-heavy questions in the flavour of quant and trading interviews, then desk scenarios to solve.",
    questions = listOf(
        QuizQuestion(
            prompt = "Report the running median of a live price stream:",
            options = listOf(
                "Two heaps — a max-heap of the low half, a min-heap of the high half",
                "Re-sort the stream on every tick",
                "A single min-heap",
                "A hash map of price counts",
            ),
            correctIndex = 0,
            patternTag = "Top-K / Heap",
            difficulty = Difficulty.ADVANCED,
            explanation = "Balance the two heaps so their tops straddle the median; each insert is O(log n) and the median is O(1).",
            linkedTopicId = "heap",
            linkedTopicLabel = "Heap (Priority Queue)",
        ),
        QuizQuestion(
            prompt = "Report the highest price in the trailing k ticks, updated on every tick:",
            options = listOf(
                "A monotonic deque of indices, dropping any tick a newer higher one dominates",
                "A max-heap of the last k prices",
                "Rescan the k-tick window on each tick",
                "A running maximum that resets when the window slides",
            ),
            correctIndex = 0,
            patternTag = "Monotonic Deque",
            difficulty = Difficulty.ADVANCED,
            explanation = "Each index is pushed and popped once, so the whole stream costs O(n) with the answer at the deque's front. A heap is O(n log k) and needs lazy deletion; a running max cannot recover when the tick holding the maximum leaves the window.",
            linkedTopicId = "deque",
            linkedTopicLabel = "Deque",
        ),
        QuizQuestion(
            prompt = "Compute a^n for a large integer n as fast as possible:",
            options = listOf(
                "Exponentiation by squaring — O(log n)",
                "Multiply a by itself n times — O(n)",
                "Take the logarithm and exponentiate",
                "A lookup table of all powers",
            ),
            correctIndex = 0,
            patternTag = "Divide & Conquer",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Square the base and halve the exponent each step: a^n = (a^(n/2))². O(log n) multiplications.",
        ),
        QuizQuestion(
            prompt = "Count the number of ways to make an amount from unlimited denominations:",
            options = listOf(
                "DP iterating coins in the outer loop",
                "Greedy — always take the largest coin",
                "Two pointers over sorted coins",
                "Breadth-first search",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.ADVANCED,
            explanation = "Looping coins outer and amounts inner counts combinations without double-counting orderings. Greedy answers the min-coins variant, not the count.",
            linkedTopicId = "coin_change",
            linkedTopicLabel = "Coin Change",
        ),
        QuizQuestion(
            prompt = "Find where a new price would be inserted into a sorted order book, in O(log n):",
            options = listOf(
                "Binary search for the lower bound",
                "Linear scan from the best bid",
                "Hash the price levels",
                "Insertion sort the new price",
            ),
            correctIndex = 0,
            patternTag = "Binary Search",
            difficulty = Difficulty.BEGINNER,
            explanation = "Lower-bound binary search returns the first index whose value is ≥ the target — the insertion point — in O(log n).",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
        ),
        QuizQuestion(
            prompt = "Scenario: design a matching engine's order book — add orders, cancel by id, and always know the best bid and best ask.",
            options = listOf(
                "Per side, a sorted map of price → FIFO queue of orders, plus a map of order id → order for O(1) cancels",
                "One unsorted list of all orders, scanned for every trade",
                "A single hash map from price to quantity",
                "Re-sort every order on each tick",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Order Book",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: bids sorted high to low, asks low to high, so each best price is the first entry. Within a price level a FIFO queue gives time priority — first in, first filled. The id map finds an order for cancellation without searching its level. Adding a new price level is O(log levels); everything else is O(1).",
            linkedTopicId = "avl_red_black_tree",
            linkedTopicLabel = "AVL / Red-Black Tree",
            figure = Figure(
                caption = "Top of the book",
                shape = FigureShape.Stacks(
                    columns = listOf(
                        FigureStack("asks (sell)", listOf("101.10 × 500", "101.20 × 300")),
                        FigureStack("bids (buy)", listOf("100.90 × 400", "100.80 × 200")),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: show the volume-weighted average price (VWAP) of the last 5 minutes, updated on every trade.",
            options = listOf(
                "A queue of recent trades with running sums of price × volume and of volume; evict trades older than 5 minutes",
                "Recompute from every trade of the day on each tick",
                "Average the prices, ignoring volume",
                "Keep a max-heap of prices",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Sliding Window",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: on each trade push it and add p·v to S and v to V; pop from the front while the oldest trade is over 5 minutes old, subtracting it. VWAP = S / V. Each trade enters and leaves once — O(1) amortised. A plain average lets a 1-share trade count as much as a 100,000-share block.",
            linkedTopicId = "sliding_window_pattern",
            linkedTopicLabel = "Sliding Window Pattern",
        ),
        QuizQuestion(
            prompt = "Scenario: given exchange rates between currencies, detect an arbitrage loop (trade round a cycle and end with more than you started).",
            options = listOf(
                "Take −log of every rate; a negative cycle (found with Bellman-Ford) is an arbitrage loop",
                "Dijkstra on the raw rates",
                "Always take the best rate out of each currency",
                "Topologically sort the currencies",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Negative Cycles",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: a loop is profitable when r₁·r₂·…·rₖ > 1. Taking logs turns the product into a sum; negating turns \"> 0\" into \"< 0\". So arbitrage is exactly a negative cycle, which Bellman-Ford detects on its V-th round. Dijkstra breaks on negative edges; currency graphs are full of cycles, so they have no topological order.",
            linkedTopicId = "bellman_ford",
            linkedTopicLabel = "Bellman-Ford Algorithm",
            figure = Figure(
                caption = "Exchange rates",
                shape = FigureShape.Graph(
                    nodes = listOf(
                        FigureGraphNode("USD", 0.12f, 0.5f),
                        FigureGraphNode("EUR", 0.55f, 0.16f),
                        FigureGraphNode("GBP", 0.55f, 0.84f),
                        FigureGraphNode("JPY", 0.9f, 0.5f),
                    ),
                    edges = listOf(
                        FigureEdge(0, 1, "0.92", directed = true),
                        FigureEdge(1, 2, "0.86", directed = true),
                        FigureEdge(2, 0, "1.28", directed = true),
                        FigureEdge(1, 3, "160", directed = true),
                        FigureEdge(3, 2, "0.0053", directed = true),
                    ),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: a payments service stores account balances. Which type should hold money?",
            options = listOf(
                "Integer minor units (cents) or a decimal type — never binary floating point",
                "A double — 64 bits is plenty of precision",
                "A float, rounded to 2 places after each operation",
                "A string, parsed whenever it is needed",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Numerics",
            difficulty = Difficulty.BEGINNER,
            explanation = "Solve: 0.1 has no exact binary representation, so 0.1 + 0.2 == 0.30000000000000004, and those errors add up across millions of transactions. Store 1,050 cents as a Long, or use BigDecimal with an explicit rounding mode. Rounding floats after each step still accumulates error and breaks exact equality checks.",
        ),
        QuizQuestion(
            prompt = "Scenario: report a fund's maximum drawdown — the largest fall from a peak to a later low — over a price history.",
            options = listOf(
                "One pass tracking the running peak and the largest (peak − price) / peak",
                "The overall maximum minus the overall minimum",
                "Sort the prices and compare the ends",
                "The largest single-day fall",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Running Best",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: peak = max(peak, p); dd = max(dd, (peak − p) / peak). O(n), O(1). The drop must come after the peak, so the global max minus min is wrong when the minimum comes first. Several small daily falls can add up to a drawdown far larger than any single day.",
            linkedTopicId = "running_best_pattern",
            linkedTopicLabel = "Running Best (Kadane)",
            figure = Figure(
                caption = "Fund value over a year",
                shape = FigureShape.Plot(
                    series = listOf(
                        FigureSeries(
                            label = "fund",
                            points = listOf(
                                FigurePoint(0.0f, 0.3f),
                                FigurePoint(0.15f, 0.55f),
                                FigurePoint(0.3f, 0.8f),
                                FigurePoint(0.45f, 0.4f),
                                FigurePoint(0.6f, 0.5f),
                                FigurePoint(0.7f, 0.9f),
                                FigurePoint(0.85f, 0.7f),
                                FigurePoint(1.0f, 0.75f),
                            ),
                        ),
                    ),
                    xLabel = "time",
                    yLabel = "value",
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: users have set 1,000,000 price alerts on a stock. Each tick, fire every alert the price just crossed.",
            options = listOf(
                "Keep alert thresholds sorted; on each move, binary search the range between the old and new price and fire those",
                "Check every alert on every tick",
                "A hash map keyed by the exact alert price",
                "Check all alerts once at market close",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Binary Search",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: when the price moves from 101.20 to 101.55, only thresholds in (101.20, 101.55] were crossed. Two binary searches find that slice in O(log n) plus the alerts fired. Checking all of them is 10⁶ comparisons per tick. An exact-price map misses crossings, because the price jumps past most values without ever equalling them.",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
            figure = Figure(
                caption = "Alert thresholds, sorted",
                shape = FigureShape.Strip(
                    cells = listOf("100.95", "101.10", "101.25", "101.40", "101.50", "101.70"),
                    pointers = listOf(FigurePointer(0, "old"), FigurePointer(4, "new")),
                ),
            ),
        ),
        QuizQuestion(
            prompt = "Scenario: you price an option by Monte Carlo simulation and want to halve the estimate's standard error. How many more paths do you need?",
            options = listOf(
                "4× as many — the error shrinks like 1 / √N",
                "2× as many — the error shrinks like 1 / N",
                "The same number, run twice",
                "Any number — the error does not depend on N",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Probability",
            difficulty = Difficulty.ADVANCED,
            explanation = "Solve: standard error = σ / √N, so halving it needs √N to double, which means N × 4. Ten times more precision costs 100 times more paths. That is why variance-reduction tricks (antithetic variates, control variates) matter: they shrink σ instead of growing N.",
            linkedTopicId = "monte_carlo_method",
            linkedTopicLabel = "Monte Carlo Method",
        ),
        QuizQuestion(
            prompt = "Scenario: a latency-critical pricing loop walks the same data millions of times per second. Why is an array usually faster than a linked list here?",
            options = listOf(
                "Contiguous memory is cache-friendly — the CPU prefetches the next elements; list nodes are scattered",
                "Arrays have better Big-O for sequential iteration",
                "Linked lists use more CPU instructions per element",
                "Arrays skip the garbage collector entirely",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Performance",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: both are O(n) to walk, so Big-O cannot explain it. A cache miss costs roughly 100 ns against about 1 ns for a hit; an array brings 8–16 values in per cache line, while each list node can be a fresh miss. In hot loops, memory layout outweighs the instruction count.",
            linkedTopicId = "array",
            linkedTopicLabel = "Array",
        ),
        QuizQuestion(
            prompt = "Brainteaser: roll a fair die and receive the number shown. You may re-roll once and must keep the second roll. What is the expected payout with the best strategy?",
            options = listOf(
                "4.25 — re-roll on 1, 2 or 3",
                "3.5 — the plain average of a die",
                "4.5 — re-roll on anything below 6",
                "5 — keep only 4, 5 or 6",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Expected Value",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: a re-roll is worth 3.5, so keep any first roll above 3.5. P(keep) = 1/2 with an average of 5; otherwise re-roll for 3.5. EV = ½ · 5 + ½ · 3.5 = 4.25. Re-rolling a 4 or 5 swaps a sure 4 or 5 for an average of 3.5, which lowers the payout.",
        ),
        QuizQuestion(
            prompt = "Scenario: sample one trade at random for an audit, with each trade's chance proportional to its volume.",
            options = listOf(
                "Prefix sums of the volumes, then draw r in [0, total) and binary search for the first prefix above r",
                "Pick a trade uniformly at random",
                "Always pick the largest trade",
                "Repeat each trade's id once per share, then pick from that list",
            ),
            correctIndex = 0,
            patternTag = "Scenario · Weighted Sampling",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Solve: prefix = [v₁, v₁ + v₂, …]; r = random(0, total); return the first index with prefix[i] > r. O(n) setup and O(log n) per draw. Repeating ids per share is also correct, but a 1,000,000-share trade becomes a million entries.",
            linkedTopicId = "prefix_sum",
            linkedTopicLabel = "Prefix Sum",
        ),
    ),
)
