package com.algora.app.feature.interviewprep.quiz

import com.algora.app.core.data.model.Difficulty

// Second batch of AI-mode quizzes: the unsupervised, vision and data-prep areas the first batch
// skipped, plus a company-style ML Engineer set that mixes modelling with production concerns the
// way a real screen does.

private const val AI_TIME_LIMIT = 240

internal val unsupervisedLearningQuiz = Quiz(
    id = "unsupervised_learning_quiz",
    title = "Unsupervised Learning",
    description = "Clustering assumptions, cluster counts and dimensionality reduction.",
    questions = listOf(
        QuizQuestion(
            prompt = "k-means implicitly assumes clusters that are:",
            options = listOf(
                "Roughly spherical and similar in size, since it assigns by Euclidean distance to a centroid",
                "Arbitrarily shaped and of any density",
                "Nested inside one another",
                "Linearly separable by a hyperplane",
            ),
            correctIndex = 0,
            patternTag = "Clustering",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Assignment to the nearest centroid carves space into convex cells, so elongated, ring-shaped or wildly unequal clusters get split or merged. Density-based methods handle those.",
            linkedTopicId = "kmeans",
            linkedTopicLabel = "K-Means",
        ),
        QuizQuestion(
            prompt = "Unlike k-means, DBSCAN:",
            options = listOf(
                "Finds arbitrarily shaped clusters and labels low-density points as noise",
                "Requires the cluster count up front",
                "Always assigns every point to a cluster",
                "Only works on two-dimensional data",
            ),
            correctIndex = 0,
            patternTag = "Density Clustering",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "It grows clusters from dense neighbourhoods defined by eps and minPts, so shape is unconstrained and outliers stay unassigned. The cost is sensitivity to eps when densities vary.",
            linkedTopicId = "dbscan",
            linkedTopicLabel = "DBSCAN",
        ),
        QuizQuestion(
            prompt = "A silhouette score near 0 for a point means:",
            options = listOf(
                "It sits on the boundary between two clusters",
                "It is deep inside its cluster",
                "It is definitely misassigned",
                "The clustering is perfect",
            ),
            correctIndex = 0,
            patternTag = "Cluster Evaluation",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Silhouette compares within-cluster distance to nearest-other-cluster distance: ≈1 is well inside, ≈0 is on the border, and negative suggests the point belongs to the neighbouring cluster.",
            linkedTopicId = "silhouette_score",
            linkedTopicLabel = "Silhouette Score",
        ),
        QuizQuestion(
            prompt = "PCA components are chosen to:",
            options = listOf(
                "Be orthogonal directions capturing maximum remaining variance",
                "Maximise class separation using the labels",
                "Preserve pairwise distances exactly",
                "Minimise the number of features to exactly two",
            ),
            correctIndex = 0,
            patternTag = "Dimensionality Reduction",
            difficulty = Difficulty.BEGINNER,
            explanation = "PCA is unsupervised — it never sees labels. Each component is the highest-variance direction orthogonal to those already taken. LDA is the supervised, class-separating counterpart.",
            linkedTopicId = "pca",
            linkedTopicLabel = "PCA",
        ),
        QuizQuestion(
            prompt = "Why must features be standardised before PCA?",
            options = listOf(
                "Variance is scale-dependent, so a large-unit feature would dominate the components",
                "PCA cannot handle negative numbers",
                "It makes the covariance matrix square",
                "It guarantees orthogonality",
            ),
            correctIndex = 0,
            patternTag = "Dimensionality Reduction",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A feature measured in metres versus kilometres changes its variance by 10⁶ without changing the information. Z-scoring puts every feature on comparable footing first.",
            linkedTopicId = "z_score_standardization",
            linkedTopicLabel = "Z-Score Standardisation",
        ),
        QuizQuestion(
            prompt = "t-SNE plots should not be read as showing:",
            options = listOf(
                "Meaningful distances between well-separated clusters",
                "Local neighbourhood structure",
                "Groups of similar points",
                "Possible cluster counts to investigate",
            ),
            correctIndex = 0,
            patternTag = "Visualisation",
            difficulty = Difficulty.ADVANCED,
            explanation = "t-SNE optimises a local neighbourhood objective, so gaps between clusters and cluster sizes carry little meaning and change with perplexity. Use it to explore, not to measure.",
            linkedTopicId = "tsne",
            linkedTopicLabel = "t-SNE",
        ),
    ),
)

internal val computerVisionQuiz = Quiz(
    id = "computer_vision_quiz",
    title = "Computer Vision",
    description = "Convolutions, receptive fields, detection and segmentation.",
    questions = listOf(
        QuizQuestion(
            prompt = "A convolutional layer beats a fully connected one on images mainly because:",
            options = listOf(
                "Shared kernels give translation equivariance with far fewer parameters",
                "It uses a different activation function",
                "It never overfits",
                "Convolution is faster than matrix multiplication in all cases",
            ),
            correctIndex = 0,
            patternTag = "CNN Basics",
            difficulty = Difficulty.BEGINNER,
            explanation = "One small kernel sweeps the whole image, so a feature detected in one corner is detected anywhere, and parameter count depends on kernel size rather than image size.",
            linkedTopicId = "conv_layers",
            linkedTopicLabel = "Convolutional Layers",
        ),
        QuizQuestion(
            prompt = "A 32×32 input through a 3×3 convolution with stride 1 and no padding produces:",
            options = listOf("30×30", "32×32", "16×16", "34×34"),
            correctIndex = 0,
            patternTag = "Shapes",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Output = (W - K + 2P)/S + 1 = (32 - 3 + 0)/1 + 1 = 30. 'Same' padding (P = 1) is what preserves 32×32.",
            linkedTopicId = "padding_strides",
            linkedTopicLabel = "Padding & Strides",
        ),
        QuizQuestion(
            prompt = "Pooling layers are used to:",
            options = listOf(
                "Shrink the spatial map and add small-shift tolerance",
                "Increase the number of channels",
                "Add trainable parameters",
                "Normalise activations across the batch",
            ),
            correctIndex = 0,
            patternTag = "CNN Basics",
            difficulty = Difficulty.BEGINNER,
            explanation = "Max pooling keeps the strongest response in each window, halving height and width with no parameters and widening the receptive field of later layers.",
            linkedTopicId = "pooling_layers",
            linkedTopicLabel = "Pooling Layers",
        ),
        QuizQuestion(
            prompt = "ResNet's skip connections help train very deep networks because they:",
            options = listOf(
                "Give gradients a short path back, so identity is easy to learn",
                "Reduce the parameter count to zero in deep layers",
                "Replace the need for an activation function",
                "Force every layer to learn a different feature",
            ),
            correctIndex = 0,
            patternTag = "Architectures",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "With y = F(x) + x, a block that learns nothing still passes x through unchanged, and the additive path carries gradient without repeated multiplication through weights.",
            linkedTopicId = "resnet",
            linkedTopicLabel = "ResNet",
        ),
        QuizQuestion(
            prompt = "YOLO is faster than Faster R-CNN because it:",
            options = listOf(
                "Predicts boxes and classes in a single pass instead of proposing regions first",
                "Uses a smaller input image",
                "Skips the convolutional backbone",
                "Runs only on GPUs",
            ),
            correctIndex = 0,
            patternTag = "Detection",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Single-stage detectors regress boxes directly on a grid; two-stage detectors run a proposal network and then classify each region. The trade has historically been speed versus small-object accuracy.",
            linkedTopicId = "yolo",
            linkedTopicLabel = "YOLO",
        ),
        QuizQuestion(
            prompt = "Semantic segmentation differs from instance segmentation in that it:",
            options = listOf(
                "Labels every pixel by class without separating individual objects",
                "Outputs bounding boxes only",
                "Works on video rather than images",
                "Requires no labelled data",
            ),
            correctIndex = 0,
            patternTag = "Segmentation",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Semantic segmentation gives all three sheep one 'sheep' mask; instance segmentation (Mask R-CNN) separates sheep 1, 2 and 3. Panoptic combines both.",
            linkedTopicId = "segmentation_types",
            linkedTopicLabel = "Segmentation Types",
        ),
    ),
)

internal val dataPreprocessingQuiz = Quiz(
    id = "data_preprocessing_quiz",
    title = "Data Preprocessing",
    description = "Imputation, encoding, scaling, imbalance and leakage.",
    questions = listOf(
        QuizQuestion(
            prompt = "Fitting the scaler on the full dataset before splitting into train and test causes:",
            options = listOf(
                "Data leakage — test statistics inform the training transform",
                "Nothing; scaling is label-independent",
                "Underfitting",
                "A shape mismatch at predict time",
            ),
            correctIndex = 0,
            patternTag = "Leakage",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "The mean and standard deviation carry information from held-out rows, so the reported test score is optimistic. Fit on train, then transform both.",
            linkedTopicId = "z_score_standardization",
            linkedTopicLabel = "Z-Score Standardisation",
        ),
        QuizQuestion(
            prompt = "Label-encoding a nominal feature like city for a linear model is wrong because it:",
            options = listOf(
                "Invents an ordering and a distance between categories",
                "Produces too many columns",
                "Cannot handle unseen categories",
                "Makes the feature continuous-valued and therefore unscalable",
            ),
            correctIndex = 0,
            patternTag = "Encoding",
            difficulty = Difficulty.BEGINNER,
            explanation = "Mapping to 0, 1, 2 tells the model city 2 is 'twice' city 1 and closer to city 3. One-hot removes the false ordering; tree models are less affected but still split arbitrarily.",
            linkedTopicId = "one_hot_encoding",
            linkedTopicLabel = "One-Hot Encoding",
        ),
        QuizQuestion(
            prompt = "Min-max scaling is preferred over z-scoring when:",
            options = listOf(
                "A bounded range is required and outliers are already handled",
                "The data has heavy outliers",
                "The feature is normally distributed",
                "The model is a decision tree",
            ),
            correctIndex = 0,
            patternTag = "Scaling",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Min-max maps to [0, 1] using the extremes, so a single outlier compresses everything else into a sliver. Z-scoring is the more robust default; trees need neither.",
            linkedTopicId = "min_max_normalization",
            linkedTopicLabel = "Min-Max Normalisation",
        ),
        QuizQuestion(
            prompt = "SMOTE addresses class imbalance by:",
            options = listOf(
                "Synthesising minority examples along segments between neighbours",
                "Deleting majority rows at random",
                "Reweighting the loss function",
                "Duplicating minority rows exactly",
            ),
            correctIndex = 0,
            patternTag = "Imbalance",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Interpolating between a minority point and its k nearest minority neighbours adds variety that plain duplication cannot. Apply it inside the training fold only, never before the split.",
            linkedTopicId = "smote",
            linkedTopicLabel = "SMOTE",
        ),
        QuizQuestion(
            prompt = "Median imputation is preferred over mean imputation when the feature:",
            options = listOf(
                "Is skewed or has outliers",
                "Is perfectly symmetric",
                "Has no missing values",
                "Is categorical",
            ),
            correctIndex = 0,
            patternTag = "Missing Data",
            difficulty = Difficulty.BEGINNER,
            explanation = "The mean is dragged by extreme values, so imputed rows land somewhere no real row sits. The median is robust; categoricals get the mode or an explicit 'missing' level.",
            linkedTopicId = "missing_value_imputation",
            linkedTopicLabel = "Missing Value Imputation",
        ),
        QuizQuestion(
            prompt = "Recursive feature elimination selects features by:",
            options = listOf(
                "Repeatedly fitting the model and dropping the weakest features",
                "Ranking features by correlation once",
                "Random sampling of feature subsets",
                "Removing features with missing values",
            ),
            correctIndex = 0,
            patternTag = "Feature Selection",
            difficulty = Difficulty.ADVANCED,
            explanation = "RFE is a wrapper method: it uses the model's own importances, refits after each removal, and therefore captures interactions that one-shot filters like chi-square miss — at a much higher compute cost.",
            linkedTopicId = "rfe",
            linkedTopicLabel = "Recursive Feature Elimination",
        ),
    ),
)

// Company-style set for ML engineer screens: modelling questions mixed with the production concerns
// (leakage, serving, monitoring) that separate an ML engineer round from a pure ML quiz.
internal val mlEngineerSet = Quiz(
    id = "ml_engineer_set",
    title = "ML Engineer Set",
    description = "ML-engineer screen questions — modelling plus production reality.",
    questions = listOf(
        QuizQuestion(
            prompt = "A fraud model scores 99.5% accuracy on data where 0.5% of transactions are fraud. The right reaction is:",
            options = listOf(
                "Accuracy is meaningless here — report precision, recall and PR-AUC",
                "Ship it; the accuracy is excellent",
                "Increase the training set size",
                "Switch to mean squared error",
            ),
            correctIndex = 0,
            patternTag = "Evaluation",
            difficulty = Difficulty.BEGINNER,
            explanation = "Predicting 'not fraud' always scores 99.5%. Under heavy imbalance the minority class needs precision/recall, and PR-AUC discriminates better than ROC-AUC.",
            linkedTopicId = "precision_recall",
            linkedTopicLabel = "Precision & Recall",
        ),
        QuizQuestion(
            prompt = "Offline AUC improved but the online click-through rate dropped after rollout. The first thing to check is:",
            options = listOf(
                "Training/serving skew and leakage in the offline evaluation",
                "Whether the learning rate was too high",
                "The number of hidden layers",
                "Whether the GPU was saturated",
            ),
            correctIndex = 0,
            patternTag = "Production",
            difficulty = Difficulty.ADVANCED,
            explanation = "The classic causes are features computed differently online than offline, and an offline split that leaked future information. Both inflate offline scores without any real gain.",
            linkedTopicId = "model_evaluation",
            linkedTopicLabel = "Model Evaluation",
        ),
        QuizQuestion(
            prompt = "For a time-series forecasting model, the correct validation split is:",
            options = listOf(
                "Chronological — train on the past, validate on the future",
                "Random k-fold across all rows",
                "Stratified by the target value",
                "Leave-one-out over the whole series",
            ),
            correctIndex = 0,
            patternTag = "Validation",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Random folds let the model see future points while predicting the past — leakage that random splits hide. Rolling-origin (walk-forward) validation mirrors deployment.",
            linkedTopicId = "arima",
            linkedTopicLabel = "ARIMA",
        ),
        QuizQuestion(
            prompt = "Gradient-boosted trees usually beat a deep net on mid-size tabular data because they:",
            options = listOf(
                "Handle mixed feature types and non-linear splits with little tuning or data",
                "Have more parameters",
                "Train on GPUs more efficiently",
                "Are immune to overfitting",
            ),
            correctIndex = 0,
            patternTag = "Model Choice",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Boosted trees are scale-invariant, need no encoding of monotone relationships and fit sharp thresholds from thousands of rows — where a net would need far more data and tuning.",
            linkedTopicId = "xgboost",
            linkedTopicLabel = "XGBoost",
        ),
        QuizQuestion(
            prompt = "Serving a large model under a tight latency budget most directly calls for:",
            options = listOf(
                "Quantisation or distillation into a smaller student model",
                "A larger batch size at training time",
                "More dropout",
                "Switching the optimiser to Adam",
            ),
            correctIndex = 0,
            patternTag = "Serving",
            difficulty = Difficulty.ADVANCED,
            explanation = "Both shrink inference cost: quantisation lowers numeric precision, distillation trains a small model on the large one's outputs. Caching and batching help too — training-time knobs do not.",
            linkedTopicId = "transfer_learning",
            linkedTopicLabel = "Transfer Learning",
        ),
        QuizQuestion(
            prompt = "Input feature distributions shifted but labels have not arrived yet. This is:",
            options = listOf(
                "Data drift — detectable without labels, and an early warning for accuracy loss",
                "Concept drift, which needs no monitoring",
                "Overfitting",
                "A leakage bug",
            ),
            correctIndex = 0,
            patternTag = "Monitoring",
            difficulty = Difficulty.ADVANCED,
            explanation = "Data drift is a change in P(x); concept drift is a change in P(y|x) and needs labels to see. Watching inputs and prediction distributions buys warning time while labels lag.",
            linkedTopicId = "outlier_detection",
            linkedTopicLabel = "Outlier Detection",
        ),
    ),
)
